[package]
name = "sheaf"
description = "A minimal static blog generator written in Wado"
repository-directory = "package-sheaf"
# version / repository / namespace / license / authors inherited from [workspace.package]

[world]
"wasi:cli/command" = "src/main.wado"
