[package]
name = "wado-lsp"
version = "0.1.0"
edition = "2024"
description = "Language service engine for the Wado programming language"
license = { workspace = true }

[dependencies]
wado-compiler = { path = "../wado-compiler" }
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[lints]
workspace = true
