SELECT 1
SELECT a, b FROM t
SELECT * FROM t WHERE x BETWEEN 1 AND 10
SELECT a FROM t1 JOIN t2 ON t1.id = t2.id
SELECT count(*) FROM t GROUP BY a HAVING count(*) > 1
SELECT a FROM t ORDER BY a DESC LIMIT 10
SELECT a FROM t UNION SELECT b FROM u
SELECT CASE WHEN a > 0 THEN 1 ELSE 2 END FROM t
INSERT INTO t (a, b) VALUES (1, 2)
DELETE FROM t WHERE id = 1
UPDATE t SET a = 1 WHERE id = 2
CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT NOT NULL)
CREATE INDEX idx ON t (a, b)
SELECT a + b * c FROM t
SELECT a FROM t UNION SELECT b FROM u ORDER BY a LIMIT 1
SELECT a FROM t UNION ALL SELECT b FROM u
SELECT a FROM t INTERSECT SELECT b FROM u EXCEPT SELECT c FROM v
SELECT * FROM (SELECT a FROM t UNION SELECT b FROM u)
VALUES (1, 2)
WITH c AS (SELECT 1) SELECT * FROM c
WITH RECURSIVE c(a) AS (SELECT 1 UNION ALL SELECT a + 1 FROM c) SELECT * FROM c
DELETE FROM t WHERE id IN (SELECT id FROM u LIMIT 1)
DELETE FROM t WHERE id = 1 LIMIT 2
DELETE FROM t ORDER BY a LIMIT 1 OFFSET 2
UPDATE t SET a = 1 WHERE b IN (SELECT x FROM y LIMIT 1)
UPDATE OR REPLACE t SET a = 1 LIMIT 3
DELETE FROM db.t INDEXED BY i WHERE a = 1
UPDATE t NOT INDEXED SET a = 1
SELECT (a)
SELECT ((a))
SELECT (1)
SELECT (a + 1)
SELECT * FROM (t)
SELECT * FROM t (x)
SELECT * FROM f(1)
SELECT * FROM f()
SELECT * FROM s.f(1, 2)
SELECT * FROM f(1) AS x
SELECT * FROM a, b
SELECT * FROM a, b JOIN c ON a.x = c.x
SELECT * FROM a NATURAL LEFT OUTER JOIN b USING (x)
SELECT * FROM a JOIN b
SELECT * FROM a CROSS JOIN b ON 1
SELECT * FROM (a JOIN b ON 1)
SELECT * FROM (a, b)
CREATE TABLE t (a UNSIGNED BIG INT)
CREATE TABLE t (a VARCHAR(10), b DECIMAL(10, 2))
CREATE TABLE t (a NOT NULL)
CREATE TABLE t (a CONSTRAINT c NOT NULL DEFAULT 1)
CREATE TABLE t (a INTEGER, b INTEGER, PRIMARY KEY (a, b))
CREATE TABLE t (a INTEGER, CONSTRAINT ck CHECK (a > 0))
CREATE TABLE t (a INTEGER, FOREIGN KEY (a) REFERENCES u (x) ON DELETE CASCADE)
CREATE TABLE t (a INTEGER) WITHOUT ROWID
CREATE TABLE t AS SELECT 1
CREATE TABLE t (a INTEGER)
CREATE TABLE users (id INTEGER, name TEXT, PRIMARY KEY (id))
SELECT a - b - c
SELECT NOT a AND b
SELECT -a * b
SELECT a IS NOT NULL
SELECT a NOT NULL
SELECT a NOT BETWEEN 1 AND 2 AND b
SELECT a NOT IN (1, 2)
SELECT a IN t
SELECT a IN db.t
SELECT a LIKE 'x' ESCAPE 'y'
SELECT CAST(a AS INTEGER)
SELECT EXISTS (SELECT 1)
SELECT NOT EXISTS (SELECT 1)
SELECT RAISE(ABORT, 'e')
SELECT a COLLATE NOCASE
SELECT CASE WHEN a THEN CASE WHEN b THEN 1 END ELSE 2 END
SELECT a || b || c
SELECT a = b = c
SELECT COUNT(DISTINCT a) FROM t
SELECT CASE WHEN x > 1 THEN 1 END FROM t
SELECT CASE x WHEN 1 THEN 1 END FROM t
SELECT CASE 1 WHEN 1 THEN 1 ELSE 0 END
SELECT c.id
SELECT f(c.id)
SELECT COUNT(c.id) AS comment_count FROM comments c
SELECT * FROM users WHERE is_active = 1
ANALYZE x
ANALYZE a.b
REINDEX x
REINDEX a.b
INSERT OR REPLACE INTO t VALUES (1)
REPLACE INTO t (a) VALUES (1)
INSERT INTO t DEFAULT VALUES
INSERT INTO t SELECT 1
INSERT INTO t VALUES (1), (2)
SELECT t.* FROM t
SELECT a b FROM t
SELECT a AS b FROM t
SELECT DISTINCT a FROM t
SELECT 1;;SELECT 2
SELECT 1;
;SELECT 1;;SELECT 2;;
EXPLAIN QUERY PLAN SELECT 1
EXPLAIN SELECT 1
CREATE TRIGGER tr AFTER INSERT ON t BEGIN SELECT 1; END
CREATE VIEW v AS SELECT 1
CREATE VIRTUAL TABLE t USING fts5(a, b)
CREATE VIRTUAL TABLE t USING m(a INTEGER)
PRAGMA db.x = 1
PRAGMA x(1)
PRAGMA x = 'foo'
BEGIN DEFERRED TRANSACTION tn
ALTER TABLE t ADD COLUMN c INTEGER
ATTACH DATABASE 'f' AS d
RELEASE SAVEPOINT s
ROLLBACK TO SAVEPOINT s
