SELECT 1
SELECT a, b FROM t
SELECT * FROM t WHERE x BETWEEN 1 AND 10
SELECT a FROM t1 JOIN t2 ON t1.id = t2.id
SELECT count(*) FROM t GROUP BY a HAVING count(*) > 1
SELECT a FROM t ORDER BY a DESC LIMIT 10
SELECT a FROM t UNION SELECT b FROM u
SELECT CASE WHEN a > 0 THEN 1 ELSE 2 END FROM t
INSERT INTO t (a, b) VALUES (1, 2)
DELETE FROM t WHERE id = 1
UPDATE t SET a = 1 WHERE id = 2
CREATE TABLE t (id INTEGER PRIMARY KEY, name TEXT NOT NULL)
CREATE INDEX idx ON t (a, b)
SELECT a + b * c FROM t
