[workspace]
members = ["wado-compiler", "wado-cli", "wado-from-wit", "wado-bundled-libm", "wado-manifest"]
resolver = "3" # v3 resolver

[workspace.package]
license = "MIT"
rust-version = "1.94"

[workspace.dependencies]
datatest-mini = { version = "0.2" }
anyhow = { version = "1" }
fluent-uri = { version = "0.4" }
glob = { version = "0.3" }
indexmap = { version = "2" }
rustc-hash = { version = "2" }
libm = { version = "0.2" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync"] }
wat = { version = "1.244" }
wasm-encoder = { version = "0.244" }
wasmparser = { version = "0.244" }
wasmprinter = { version = "0.244" }
walrus = { version = "0.24" }
wit-parser = { version = "0.244" }
wasmtime = { version = "42", features = ["async", "component-model", "component-model-async"] }
wasmtime-wasi = { version = "42", features = ["p3"] }
wasmtime-wasi-http = { version = "42", features = ["p3"] }
bytes = { version = "1" }
futures = { version = "0.3" }
http = { version = "1" }
http-body-util = { version = "0.1" }
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio", "http1", "server"] }
assert_cmd = { version = "2" }
heck = { version = "0.5" }
lexopt = { version = "0.3.1" }
predicates = { version = "3" }
regex = { version = "1" }
tempfile = { version = "3" }
jsonschema = { version = "0.39" }
zlib-rs = { version = "0.6" }
flate2 = { version = "1", default-features = false, features = ["zlib-rs"] }
crc32fast = { version = "1" }
adler = { version = "1" }
toml = { version = "0.8", default-features = false, features = ["parse", "display"] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
disallowed_types = "warn"
mod_module_files = "deny"
