[workspace]
<<<<<<< HEAD
members = ["package-cm-catalog", "package-gale", "package-marl", "package-sheaf"]
||||||| b9480803d
members = ["package-cm-catalog", "package-gale"]
=======
members = ["package-cm-catalog", "package-gale", "package-jade"]
>>>>>>> origin/main

[workspace.package]
version = "0.0.9"
repository = "https://github.com/wado-lang/wado"
namespace = "wado-lang"
license = "MIT"
authors = ["FUJI Goro <g.psy.va@gmail.com>"]

[registries]
default = "oci://ghcr.io"
