[workspace]
members = ["package-cm-catalog", "package-gale", "package-jade", "package-marl", "package-sheaf"]

[workspace.package]
version = "0.0.9"
repository = "https://github.com/wado-lang/wado"
namespace = "wado-lang"
license = "MIT"
authors = ["FUJI Goro <g.psy.va@gmail.com>"]

[registries]
default = "oci://ghcr.io"
