use wado_manifest::{LockFile, LockFileError, LockedPackage};

#[test]
fn full_lock_file_from_wep() {
    let toml = r#"
# This file is auto-generated by wado. Do not edit manually.
version = 1
deps-hash = "sha256:9f8e7d6c5b4a"

[[package]]
id = "git+https://gitlab.com/user/bench.git/bench-tool"
version = "0.1.0"
resolved-ref = "def5678901234567890abcdef12345678abc1234d"
dev = true
command = "src/main.wado"
deps = []

[[package]]
id = "registry+https://wa.dev/docs:regex"
version = "0.1.2"
integrity = "sha256:a1b2c3d4e5f6"
lib = "src/lib.wado"
deps = ["registry+https://wa.dev/docs:regex-utils@0.3.0"]

[[package]]
id = "registry+https://wa.dev/docs:regex-utils"
version = "0.3.0"
integrity = "sha256:f6e5d4c3b2a1"
lib = "src/lib.wado"
deps = []

[[package]]
id = "registry+https://wa.dev/std:json"
version = "1.2.0"
integrity = "sha256:c3d4e5f6a1b2"
lib = "src/lib.wado"
deps = []

[[package]]
id = "registry+https://wa.dev/tools:utils"
version = "0.5.1"
integrity = "sha256:b2c3d4e5f6a1"
lib = "src/lib.wado"
deps = []

[[package]]
id = "git+https://github.com/user/router.git/user:router"
version = "1.0.2"
resolved-ref = "abc1234def5678901234567890abcdef12345678"
lib = "src/lib.wado"
deps = ["registry+https://wa.dev/tools:utils@0.5.1", "registry+https://wa.dev/std:json@1.2.0"]
"#;
    let lock: LockFile = toml.parse().unwrap();
    assert_eq!(lock.version, 1);
    assert_eq!(lock.deps_hash, "sha256:9f8e7d6c5b4a");
    assert_eq!(lock.packages.len(), 6);

    // Dev dependency
    let bench = &lock.packages[0];
    assert!(bench.dev);
    assert_eq!(bench.command.as_deref(), Some("src/main.wado"));
    assert!(bench.resolved_ref.is_some());
    assert!(bench.integrity.is_none());

    // Registry dependency with transitive dep
    let regex = &lock.packages[1];
    assert!(!regex.dev);
    assert_eq!(regex.integrity.as_deref(), Some("sha256:a1b2c3d4e5f6"));
    assert_eq!(regex.lib.as_deref(), Some("src/lib.wado"));
    assert_eq!(regex.deps.len(), 1);
    assert_eq!(
        regex.deps[0],
        "registry+https://wa.dev/docs:regex-utils@0.3.0"
    );

    // Git dependency with multiple deps
    let router = &lock.packages[5];
    assert_eq!(router.deps.len(), 2);
}

#[test]
fn roundtrip_preserves_data() {
    let lock = LockFile {
        version: 1,
        deps_hash: "sha256:abc123".to_string(),
        packages: vec![
            LockedPackage {
                id: "registry+https://wa.dev/ns:pkg".to_string(),
                version: "1.0.0".to_string(),
                resolved_ref: None,
                integrity: Some("sha256:def456".to_string()),
                dev: false,
                command: None,
                service: Some("src/server.wado".to_string()),
                lib: None,
                deps: vec!["registry+https://wa.dev/ns:dep@0.1.0".to_string()],
            },
            LockedPackage {
                id: "git+https://github.com/user/tool.git/user:tool".to_string(),
                version: "2.0.0".to_string(),
                resolved_ref: Some("abcdef1234567890".to_string()),
                integrity: None,
                dev: true,
                command: Some("src/main.wado".to_string()),
                service: None,
                lib: None,
                deps: vec![],
            },
        ],
        build_dependencies: vec![],
        generator_cache: vec![],
    };

    let serialized = lock.to_toml();
    let reparsed: LockFile = serialized.parse().unwrap();

    assert_eq!(reparsed.version, 1);
    assert_eq!(reparsed.deps_hash, "sha256:abc123");
    assert_eq!(reparsed.packages.len(), 2);

    // Packages are sorted in output, so git comes before registry alphabetically
    let git_pkg = reparsed
        .packages
        .iter()
        .find(|p| p.id.starts_with("git+"))
        .unwrap();
    assert!(git_pkg.dev);
    assert_eq!(git_pkg.resolved_ref.as_deref(), Some("abcdef1234567890"));
    assert_eq!(git_pkg.command.as_deref(), Some("src/main.wado"));

    let reg_pkg = reparsed
        .packages
        .iter()
        .find(|p| p.id.starts_with("registry+"))
        .unwrap();
    assert!(!reg_pkg.dev);
    assert_eq!(reg_pkg.integrity.as_deref(), Some("sha256:def456"));
    assert_eq!(reg_pkg.service.as_deref(), Some("src/server.wado"));
    assert_eq!(reg_pkg.deps.len(), 1);
}

#[test]
fn empty_packages() {
    let toml = r#"
version = 1
deps-hash = "sha256:empty"
"#;
    let lock: LockFile = toml.parse().unwrap();
    assert!(lock.packages.is_empty());
}

#[test]
fn missing_version_header() {
    let toml = r#"
deps-hash = "sha256:abc"
"#;
    let err = toml.parse::<LockFile>().unwrap_err();
    assert!(matches!(err, LockFileError::MissingField { .. }));
}

#[test]
fn missing_deps_hash() {
    let toml = r"
version = 1
";
    let err = toml.parse::<LockFile>().unwrap_err();
    assert!(matches!(err, LockFileError::MissingField { .. }));
}

#[test]
fn missing_package_id() {
    let toml = r#"
version = 1
deps-hash = "sha256:abc"

[[package]]
version = "1.0.0"
deps = []
"#;
    let err = toml.parse::<LockFile>().unwrap_err();
    assert!(matches!(err, LockFileError::MissingField { .. }));
}

#[test]
fn missing_package_version() {
    let toml = r#"
version = 1
deps-hash = "sha256:abc"

[[package]]
id = "registry+https://wa.dev/ns:pkg"
deps = []
"#;
    let err = toml.parse::<LockFile>().unwrap_err();
    assert!(matches!(err, LockFileError::MissingField { .. }));
}

#[test]
fn error_display() {
    let err = LockFileError::InvalidVersion {
        expected: 1,
        found: 42,
    };
    let msg = err.to_string();
    assert!(msg.contains("42"));
    assert!(msg.contains('1'));
}
