[package]
name = "wado-manifest"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true

[dependencies]
indexmap = { workspace = true, features = ["serde"] }
serde = { workspace = true }
toml = { version = "0.8", default-features = false, features = ["parse", "display"] }

[dev-dependencies]

[lints]
workspace = true
