;; Golden WAT: test with -O2
;; Source: wado-compiler/tests/fixtures/hello_test.wado
;; Generated by: make update-golden-wat-fixtures

(component
  (type $types-instance-type (;0;)
    (instance
      (type (;0;) (enum "io" "illegal-byte-sequence" "pipe"))
      (export (;1;) "error-code" (type (eq 0)))
    )
  )
  (import "wasi:cli/types@0.3.0-rc-2026-01-06" (instance $wasi:cli/types@0.3.0-rc-2026-01-06 (;0;) (type $types-instance-type)))
  (alias export $wasi:cli/types@0.3.0-rc-2026-01-06 "error-code" (type $error-code (;1;)))
  (type $stderr-instance-type (;2;)
    (instance
      (type (;0;) (stream u8))
      (alias outer 1 $error-code (type (;1;)))
      (type (;2;) (result (error 1)))
      (type (;3;) (func async (param "data" 0) (result 2)))
      (export (;0;) "write-via-stream" (func (type 3)))
    )
  )
  (import "wasi:cli/stderr@0.3.0-rc-2026-01-06" (instance $wasi:cli/stderr@0.3.0-rc-2026-01-06 (;1;) (type $stderr-instance-type)))
  (alias export $wasi:cli/stderr@0.3.0-rc-2026-01-06 "write-via-stream" (func $write-via-stream (;0;)))
  (type $stream-u8 (;3;) (stream u8))
  (type $result-unit (;4;) (result))
  (core module $mem-mod (;0;)
    (type $realloc (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (memory (;0;) 17)
    (global (;0;) (mut i32) (i32.const 1024))
    (export "memory" (memory 0))
    (export "realloc" (func $realloc))
    (func $realloc (;0;) (type $realloc) (param i32 i32 i32 i32) (result i32)
      (local i32)
      (local.set 4
        (i32.and
          (i32.sub
            (i32.add
              (global.get 0)
              (local.get 2))
            (i32.const 1))
          (i32.sub
            (i32.const 0)
            (local.get 2))))
      (global.set 0
        (i32.add
          (local.get 4)
          (local.get 3)))
      (local.get 4)
    )
  )
  (core instance $mem (;0;) (instantiate $mem-mod))
  (alias core export $mem "memory" (core memory $memory (;0;)))
  (alias core export $mem "realloc" (core func $realloc (;0;)))
  (core func $stream.drop-writable (;1;) (canon stream.drop-writable $stream-u8))
  (core func $stream.new (;2;) (canon stream.new $stream-u8))
  (core func $stream.write (;3;) (canon stream.write $stream-u8 (memory $memory) (realloc $realloc)))
  (core func $subtask.drop (;4;) (canon subtask.drop))
  (core func $task.return (;5;) (canon task.return (result $result-unit) (memory $memory)))
  (core func $waitable.join (;6;) (canon waitable.join))
  (core func $waitable-set.new (;7;) (canon waitable-set.new))
  (core func $waitable-set.wait (;8;) (canon waitable-set.wait (memory $memory)))
  (core func $wasi:cli/Stderr::write_via_stream (;9;) (canon lower (func $write-via-stream) async (memory $memory) (realloc $realloc)))
  (core module $main-mod (;1;)
    (rec
      (type (;0;) (sub (struct (field (mut i32)))))
      (type (;1;) (array (mut i8)))
      (type (;2;) (sub (struct (field (mut (ref null 1))) (field (mut i32)))))
      (type (;3;) (sub (struct (field (mut i32)) (field (mut i32)) (field (mut i8)) (field (mut i8)) (field (mut i8)) (field (mut i32)) (field (mut i32)) (field (mut (ref null 2))))))
    )
    (type (;4;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;5;) (func (param i32)))
    (type (;6;) (func (result i64)))
    (type (;7;) (func (param i32 i32 i32) (result i32)))
    (type (;8;) (func (param i32)))
    (type (;9;) (func (param i32)))
    (type (;10;) (func (param i32 i32)))
    (type (;11;) (func (result i32)))
    (type (;12;) (func (param i32 i32) (result i32)))
    (type (;13;) (func (param i32 i32) (result i32)))
    (type (;14;) (func))
    (type (;15;) (func))
    (type (;16;) (func))
    (type (;17;) (func))
    (type (;18;) (func (param (ref null 1) i32 i32)))
    (type (;19;) (func (param i32 (ref null 2) i32)))
    (type (;20;) (func (param i32)))
    (type (;21;) (func (param (ref null 2))))
    (type (;22;) (func (param (ref null 2))))
    (type (;23;) (func (param i64) (result i32)))
    (type (;24;) (func (param (ref null 1) i32 i64 i32)))
    (type (;25;) (func (param i32 (ref null 3))))
    (type (;26;) (func (param (ref null 2) i32)))
    (type (;27;) (func (param (ref null 2) i32) (result i32)))
    (type (;28;) (func (param (ref null 2) (ref null 2))))
    (type (;29;) (func (param (ref null 2) i32)))
    (type (;30;) (func (param (ref null 3) i32 i32)))
    (type (;31;) (func (param (ref null 3) i32 (ref null 2) i32) (result i32)))
    (import "mem" "realloc" (func (;0;) (type 4)))
    (import "wasi" "stream-drop-writable" (func (;1;) (type 5)))
    (import "wasi" "stream-new" (func (;2;) (type 6)))
    (import "wasi" "stream-write" (func (;3;) (type 7)))
    (import "wasi" "subtask-drop" (func (;4;) (type 8)))
    (import "wasi" "task-return" (func (;5;) (type 9)))
    (import "wasi" "waitable-join" (func (;6;) (type 10)))
    (import "wasi" "waitable-set-new" (func (;7;) (type 11)))
    (import "wasi" "waitable-set-wait" (func (;8;) (type 12)))
    (import "wasi" "wasi:cli/Stderr::write_via_stream" (func (;9;) (type 13)))
    (import "mem" "memory" (memory (;0;) 1))
    (export "__test_0_greeting" (func 12))
    (export "__test_1" (func 13))
    (func (;10;) (type 14)
      (local i32 i32 (ref null 2) (ref null 3) i32 (ref null 2) (ref null 0) (ref null 3) (ref null 2) (ref null 0) (ref null 3) (ref null 3) (ref null 3))
      (block ;; label = @1
        (local.set 1
          (i32.eq
            (i32.const 2)
            (i32.const 2)))
        (if ;; label = @2
          (i32.eqz
            (local.get 1))
          (then
            (call 18
              (block (result (ref null 2)) ;; label = @3
                (local.set 2
                  (struct.new 2
                    (array.new_default 1
                      (i32.const 120))
                    (i32.const 0)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 0
                      (i32.const 0)
                      (i32.const 20))
                    (i32.const 20)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 1
                      (i32.const 0)
                      (i32.const 17))
                    (i32.const 17)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 2
                      (i32.const 0)
                      (i32.const 4))
                    (i32.const 4)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 3
                      (i32.const 0)
                      (i32.const 60))
                    (i32.const 60)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 4
                      (i32.const 0)
                      (i32.const 1))
                    (i32.const 1)))
                (local.set 12
                  (block (result (ref null 3)) ;; label = @4
                    (local.set 5
                      (local.get 2))
                    (br 0 (;@4;)
                      (struct.new 3
                        (i32.const 32)
                        (i32.const 2)
                        (i32.const 0)
                        (i32.const 0)
                        (i32.const 0)
                        (i32.const -1)
                        (i32.const -1)
                        (local.get 5)))))
                (local.set 3
                  (if (result (ref null 3)) ;; label = @4
                    (ref.is_null
                      (local.get 12))
                    (then
                      (ref.null 3))
                    (else
                      (struct.new 3
                        (struct.get 3 0
                          (local.get 12))
                        (struct.get 3 1
                          (local.get 12))
                        (struct.get_u 3 2
                          (local.get 12))
                        (struct.get_u 3 3
                          (local.get 12))
                        (struct.get_u 3 4
                          (local.get 12))
                        (struct.get 3 5
                          (local.get 12))
                        (struct.get 3 6
                          (local.get 12))
                        (struct.get 3 7
                          (local.get 12))))))
                (block ;; label = @4
                  (local.set 6
                    (struct.new 0
                      (i32.const 8)))
                  (local.set 7
                    (local.get 3))
                  (call 21
                    (struct.get 0 0
                      (local.get 6))
                    (local.get 7)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 5
                      (i32.const 0)
                      (i32.const 23))
                    (i32.const 23)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 6
                      (i32.const 0)
                      (i32.const 7))
                    (i32.const 7)))
                (local.set 12
                  (block (result (ref null 3)) ;; label = @4
                    (local.set 8
                      (local.get 2))
                    (br 0 (;@4;)
                      (struct.new 3
                        (i32.const 32)
                        (i32.const 2)
                        (i32.const 0)
                        (i32.const 0)
                        (i32.const 0)
                        (i32.const -1)
                        (i32.const -1)
                        (local.get 8)))))
                (local.set 3
                  (if (result (ref null 3)) ;; label = @4
                    (ref.is_null
                      (local.get 12))
                    (then
                      (ref.null 3))
                    (else
                      (struct.new 3
                        (struct.get 3 0
                          (local.get 12))
                        (struct.get 3 1
                          (local.get 12))
                        (struct.get_u 3 2
                          (local.get 12))
                        (struct.get_u 3 3
                          (local.get 12))
                        (struct.get_u 3 4
                          (local.get 12))
                        (struct.get 3 5
                          (local.get 12))
                        (struct.get 3 6
                          (local.get 12))
                        (struct.get 3 7
                          (local.get 12))))))
                (block ;; label = @4
                  (local.set 9
                    (struct.new 0
                      (i32.const 2)))
                  (local.set 10
                    (local.get 3))
                  (call 21
                    (struct.get 0 0
                      (local.get 9))
                    (local.get 10)))
                (call 24
                  (local.get 2)
                  (struct.new 2
                    (array.new_data 1 7
                      (i32.const 0)
                      (i32.const 1))
                    (i32.const 1)))
                (br 0 (;@3;)
                  (local.get 2))))
            (unreachable))))
    )
    (func (;11;) (type 15)
      (local i32 (ref null 2) (ref null 3) i32 (ref null 2) (ref null 0) (ref null 3) (ref null 3))
      (block ;; label = @1
        (if ;; label = @2
          (i32.eqz
            (i32.const 1))
          (then
            (call 18
              (block (result (ref null 2)) ;; label = @3
                (local.set 1
                  (struct.new 2
                    (array.new_default 1
                      (i32.const 90))
                    (i32.const 0)))
                (call 24
                  (local.get 1)
                  (struct.new 2
                    (array.new_data 1 0
                      (i32.const 0)
                      (i32.const 20))
                    (i32.const 20)))
                (call 24
                  (local.get 1)
                  (struct.new 2
                    (array.new_data 1 8
                      (i32.const 0)
                      (i32.const 8))
                    (i32.const 8)))
                (call 24
                  (local.get 1)
                  (struct.new 2
                    (array.new_data 1 2
                      (i32.const 0)
                      (i32.const 4))
                    (i32.const 4)))
                (call 24
                  (local.get 1)
                  (struct.new 2
                    (array.new_data 1 3
                      (i32.const 0)
                      (i32.const 60))
                    (i32.const 60)))
                (call 24
                  (local.get 1)
                  (struct.new 2
                    (array.new_data 1 4
                      (i32.const 0)
                      (i32.const 1))
                    (i32.const 1)))
                (local.set 7
                  (block (result (ref null 3)) ;; label = @4
                    (local.set 4
                      (local.get 1))
                    (br 0 (;@4;)
                      (struct.new 3
                        (i32.const 32)
                        (i32.const 2)
                        (i32.const 0)
                        (i32.const 0)
                        (i32.const 0)
                        (i32.const -1)
                        (i32.const -1)
                        (local.get 4)))))
                (local.set 2
                  (if (result (ref null 3)) ;; label = @4
                    (ref.is_null
                      (local.get 7))
                    (then
                      (ref.null 3))
                    (else
                      (struct.new 3
                        (struct.get 3 0
                          (local.get 7))
                        (struct.get 3 1
                          (local.get 7))
                        (struct.get_u 3 2
                          (local.get 7))
                        (struct.get_u 3 3
                          (local.get 7))
                        (struct.get_u 3 4
                          (local.get 7))
                        (struct.get 3 5
                          (local.get 7))
                        (struct.get 3 6
                          (local.get 7))
                        (struct.get 3 7
                          (local.get 7))))))
                (block ;; label = @4
                  (local.set 5
                    (struct.new 0
                      (i32.const 12)))
                  (local.set 6
                    (local.get 2))
                  (call 21
                    (struct.get 0 0
                      (local.get 5))
                    (local.get 6)))
                (call 24
                  (local.get 1)
                  (struct.new 2
                    (array.new_data 1 9
                      (i32.const 0)
                      (i32.const 17))
                    (i32.const 17)))
                (br 0 (;@3;)
                  (local.get 1))))
            (unreachable))))
    )
    (func (;12;) (type 16)
      (call 10)
      (call 5
        (i32.const 0))
    )
    (func (;13;) (type 17)
      (call 11)
      (call 5
        (i32.const 0))
    )
    (func (;14;) (type 18) (param (ref null 1) i32 i32)
      (local i32)
      (block ;; label = @1
        (local.set 3
          (i32.const 0))
        (block ;; label = @2
          (loop ;; label = @3
            (if ;; label = @4
              (i32.eqz
                (i32.lt_s
                  (local.get 3)
                  (local.get 2)))
              (then
                (br 3 (;@1;))))
            (block ;; label = @4
              (i32.store8
                (i32.add
                  (local.get 1)
                  (local.get 3))
                (array.get_u 1
                  (local.get 0)
                  (local.get 3))))
            (local.set 3
              (i32.add
                (local.get 3)
                (i32.const 1)))
            (br 0 (;@3;)))))
    )
    (func (;15;) (type 19) (param i32 (ref null 2) i32)
      (local i32 (ref null 1) i32 i32 (ref null 2) (ref null 2))
      (local.set 3
        (struct.get 2 1
          (local.get 1)))
      (local.set 4
        (struct.get 2 0
          (local.get 1)))
      (local.set 5
        (if (result i32) ;; label = @1
          (local.get 2)
          (then
            (i32.add
              (local.get 3)
              (i32.const 1)))
          (else
            (local.get 3))))
      (local.set 6
        (call 0
          (i32.const 0)
          (i32.const 0)
          (i32.const 1)
          (local.get 5)))
      (call 14
        (local.get 4)
        (local.get 6)
        (local.get 3))
      (if ;; label = @1
        (local.get 2)
        (then
          (i32.store8
            (i32.add
              (local.get 6)
              (local.get 3))
            (i32.const 10))))
      (drop
        (call 3
          (local.get 0)
          (local.get 6)
          (local.get 5)))
      (drop
        (call 0
          (local.get 6)
          (local.get 5)
          (i32.const 1)
          (i32.const 0)))
      (call 1
        (local.get 0))
    )
    (func (;16;) (type 20) (param i32)
      (local i32 i32)
      (if ;; label = @1
        (i32.eq
          (i32.and
            (local.get 0)
            (i32.const 1))
          (i32.const 0))
        (then
          (local.set 1
            (call 7))
          (call 6
            (local.get 1)
            (local.get 0))
          (local.set 2
            (call 0
              (i32.const 0)
              (i32.const 0)
              (i32.const 4)
              (i32.const 8)))
          (drop
            (call 8
              (local.get 1)
              (local.get 2)))
          (drop
            (call 0
              (local.get 2)
              (i32.const 8)
              (i32.const 4)
              (i32.const 0)))
          (call 4
            (local.get 0))))
    )
    (func (;17;) (type 21) (param (ref null 2))
      (local i64 i32 i32 i32)
      (local.set 1
        (call 2))
      (local.set 2
        (i32.wrap_i64
          (local.get 1)))
      (local.set 3
        (i32.wrap_i64
          (i64.shr_s
            (local.get 1)
            (i64.const 32))))
      (local.set 4
        (call 9
          (local.get 2)
          (i32.const 2048)))
      (call 15
        (local.get 3)
        (local.get 0)
        (i32.const 1))
      (call 16
        (local.get 4))
    )
    (func (;18;) (type 22) (param (ref null 2))
      (call 17
        (local.get 0))
      (unreachable)
      (unreachable)
    )
    (func (;19;) (type 23) (param i64) (result i32)
      (local i64 i64 i32 i64)
      (if ;; label = @1
        (i64.eq
          (local.get 0)
          (i64.const 0))
        (then
          (return
            (i32.const 1))))
      (local.set 3
        (i32.const 0))
      (block ;; label = @1
        (local.set 4
          (local.get 0))
        (block ;; label = @2
          (loop ;; label = @3
            (if ;; label = @4
              (i32.eqz
                (i64.gt_s
                  (local.get 4)
                  (i64.const 0)))
              (then
                (br 3 (;@1;))))
            (block ;; label = @4
              (local.set 3
                (i32.add
                  (local.get 3)
                  (i32.const 1))))
            (local.set 4
              (i64.div_s
                (local.get 4)
                (i64.const 10)))
            (br 0 (;@3;)))))
      (return
        (local.get 3))
      (unreachable)
    )
    (func (;20;) (type 24) (param (ref null 1) i32 i64 i32)
      (local i64 i64 i32 i64)
      (local.set 6
        (i32.add
          (local.get 1)
          (local.get 3)))
      (if ;; label = @1
        (i64.eq
          (local.get 2)
          (i64.const 0))
        (then
          (array.set 1
            (local.get 0)
            (local.get 1)
            (i32.const 48)))
        (else
          (block ;; label = @2
            (local.set 7
              (local.get 2))
            (block ;; label = @3
              (loop ;; label = @4
                (if ;; label = @5
                  (i32.eqz
                    (i64.gt_s
                      (local.get 7)
                      (i64.const 0)))
                  (then
                    (br 3 (;@2;))))
                (block ;; label = @5
                  (local.set 6
                    (i32.sub
                      (local.get 6)
                      (i32.const 1)))
                  (array.set 1
                    (local.get 0)
                    (local.get 6)
                    (i32.add
                      (i32.const 48)
                      (i32.wrap_i64
                        (i64.rem_s
                          (local.get 7)
                          (i64.const 10))))))
                (local.set 7
                  (i64.div_s
                    (local.get 7)
                    (i64.const 10)))
                (br 0 (;@4;)))))))
    )
    (func (;21;) (type 25) (param i32 (ref null 3))
      (local i32 i64 i32 i32 (ref null 2))
      (local.set 2
        (i32.lt_s
          (local.get 0)
          (i32.const 0)))
      (local.set 3
        (if (result i64) ;; label = @1
          (local.get 2)
          (then
            (i64.sub
              (i64.const 0)
              (i64.extend_i32_s
                (local.get 0))))
          (else
            (i64.extend_i32_s
              (local.get 0)))))
      (local.set 4
        (call 19
          (local.get 3)))
      (local.set 5
        (call 27
          (local.get 1)
          (local.get 2)
          (struct.new 2
            (array.new_default 1
              (i32.const 0))
            (i32.const 0))
          (local.get 4)))
      (call 20
        (block (result (ref null 1)) ;; label = @1
          (local.set 6
            (struct.get 3 7
              (local.get 1)))
          (br 0 (;@1;)
            (struct.get 2 0
              (local.get 6))))
        (local.get 5)
        (local.get 3)
        (local.get 4))
    )
    (func (;22;) (type 26) (param (ref null 2) i32)
      (local i32 i32 (ref null 1) i32 i32 i32 (ref null 1))
      (local.set 2
        (array.len
          (struct.get 2 0
            (local.get 0))))
      (if ;; label = @1
        (i32.le_s
          (local.get 1)
          (local.get 2))
        (then
          (return)))
      (local.set 3
        (i32.mul
          (local.get 2)
          (i32.const 2)))
      (if ;; label = @1
        (i32.lt_s
          (local.get 3)
          (local.get 1))
        (then
          (local.set 3
            (local.get 1))))
      (if ;; label = @1
        (i32.lt_s
          (local.get 3)
          (i32.const 8))
        (then
          (local.set 3
            (i32.const 8))))
      (local.set 4
        (array.new_default 1
          (local.get 3)))
      (block ;; label = @1
        (local.set 5
          (i32.const 0))
        (local.set 7
          (struct.get 2 1
            (local.get 0)))
        (local.set 8
          (struct.get 2 0
            (local.get 0)))
        (block ;; label = @2
          (loop ;; label = @3
            (if ;; label = @4
              (i32.eqz
                (i32.lt_s
                  (local.get 5)
                  (local.get 7)))
              (then
                (br 3 (;@1;))))
            (block ;; label = @4
              (local.set 6
                (array.get_u 1
                  (local.get 8)
                  (local.get 5)))
              (array.set 1
                (local.get 4)
                (local.get 5)
                (local.get 6)))
            (local.set 5
              (i32.add
                (local.get 5)
                (i32.const 1)))
            (br 0 (;@3;)))))
      (struct.set 2 0
        (local.get 0)
        (local.get 4))
    )
    (func (;23;) (type 27) (param (ref null 2) i32) (result i32)
      (local i32 i32)
      (local.set 2
        (i32.add
          (struct.get 2 1
            (local.get 0))
          (local.get 1)))
      (if ;; label = @1
        (i32.gt_s
          (local.get 2)
          (array.len
            (struct.get 2 0
              (local.get 0))))
        (@metadata.code.branch_hint "\00")
        (then
          (call 22
            (local.get 0)
            (local.get 2))))
      (local.set 3
        (struct.get 2 1
          (local.get 0)))
      (struct.set 2 1
        (local.get 0)
        (local.get 2))
      (return
        (local.get 3))
      (unreachable)
    )
    (func (;24;) (type 28) (param (ref null 2) (ref null 2))
      (local i32 i32 (ref null 1) i32 i32 (ref null 2) (ref null 2) (ref null 1) i32)
      (local.set 2
        (struct.get 2 1
          (local.get 1)))
      (if ;; label = @1
        (i32.eq
          (local.get 2)
          (i32.const 0))
        (then
          (return)))
      (local.set 3
        (i32.add
          (struct.get 2 1
            (local.get 0))
          (local.get 2)))
      (if ;; label = @1
        (i32.gt_s
          (local.get 3)
          (array.len
            (struct.get 2 0
              (local.get 0))))
        (@metadata.code.branch_hint "\00")
        (then
          (call 22
            (local.get 0)
            (local.get 3))))
      (local.set 4
        (struct.get 2 0
          (local.get 1)))
      (block ;; label = @1
        (local.set 5
          (i32.const 0))
        (local.set 9
          (struct.get 2 0
            (local.get 0)))
        (local.set 10
          (struct.get 2 1
            (local.get 0)))
        (block ;; label = @2
          (loop ;; label = @3
            (if ;; label = @4
              (i32.eqz
                (i32.lt_s
                  (local.get 5)
                  (local.get 2)))
              (then
                (br 3 (;@1;))))
            (block ;; label = @4
              (local.set 6
                (array.get_u 1
                  (local.get 4)
                  (local.get 5)))
              (array.set 1
                (local.get 9)
                (i32.add
                  (local.get 10)
                  (local.get 5))
                (local.get 6)))
            (local.set 5
              (i32.add
                (local.get 5)
                (i32.const 1)))
            (br 0 (;@3;)))))
      (struct.set 2 1
        (local.get 0)
        (local.get 3))
    )
    (func (;25;) (type 29) (param (ref null 2) i32)
      (local i32)
      (local.set 2
        (local.get 1))
      (if ;; label = @1
        (i32.gt_s
          (i32.add
            (struct.get 2 1
              (local.get 0))
            (i32.const 4))
          (array.len
            (struct.get 2 0
              (local.get 0))))
        (@metadata.code.branch_hint "\00")
        (then
          (call 22
            (local.get 0)
            (i32.add
              (struct.get 2 1
                (local.get 0))
              (i32.const 4)))))
      (if ;; label = @1
        (i32.lt_u
          (local.get 2)
          (i32.const 128))
        (then
          (array.set 1
            (struct.get 2 0
              (local.get 0))
            (struct.get 2 1
              (local.get 0))
            (local.get 2))
          (struct.set 2 1
            (local.get 0)
            (i32.add
              (struct.get 2 1
                (local.get 0))
              (i32.const 1))))
        (else
          (if ;; label = @2
            (i32.lt_u
              (local.get 2)
              (i32.const 2048))
            (then
              (array.set 1
                (struct.get 2 0
                  (local.get 0))
                (struct.get 2 1
                  (local.get 0))
                (i32.or
                  (i32.const 192)
                  (i32.shr_u
                    (local.get 2)
                    (i32.const 6))))
              (array.set 1
                (struct.get 2 0
                  (local.get 0))
                (i32.add
                  (struct.get 2 1
                    (local.get 0))
                  (i32.const 1))
                (i32.or
                  (i32.const 128)
                  (i32.and
                    (local.get 2)
                    (i32.const 63))))
              (struct.set 2 1
                (local.get 0)
                (i32.add
                  (struct.get 2 1
                    (local.get 0))
                  (i32.const 2))))
            (else
              (if ;; label = @3
                (i32.lt_u
                  (local.get 2)
                  (i32.const 65536))
                (then
                  (array.set 1
                    (struct.get 2 0
                      (local.get 0))
                    (struct.get 2 1
                      (local.get 0))
                    (i32.or
                      (i32.const 224)
                      (i32.shr_u
                        (local.get 2)
                        (i32.const 12))))
                  (array.set 1
                    (struct.get 2 0
                      (local.get 0))
                    (i32.add
                      (struct.get 2 1
                        (local.get 0))
                      (i32.const 1))
                    (i32.or
                      (i32.const 128)
                      (i32.and
                        (i32.shr_u
                          (local.get 2)
                          (i32.const 6))
                        (i32.const 63))))
                  (array.set 1
                    (struct.get 2 0
                      (local.get 0))
                    (i32.add
                      (struct.get 2 1
                        (local.get 0))
                      (i32.const 2))
                    (i32.or
                      (i32.const 128)
                      (i32.and
                        (local.get 2)
                        (i32.const 63))))
                  (struct.set 2 1
                    (local.get 0)
                    (i32.add
                      (struct.get 2 1
                        (local.get 0))
                      (i32.const 3))))
                (else
                  (array.set 1
                    (struct.get 2 0
                      (local.get 0))
                    (struct.get 2 1
                      (local.get 0))
                    (i32.or
                      (i32.const 240)
                      (i32.shr_u
                        (local.get 2)
                        (i32.const 18))))
                  (array.set 1
                    (struct.get 2 0
                      (local.get 0))
                    (i32.add
                      (struct.get 2 1
                        (local.get 0))
                      (i32.const 1))
                    (i32.or
                      (i32.const 128)
                      (i32.and
                        (i32.shr_u
                          (local.get 2)
                          (i32.const 12))
                        (i32.const 63))))
                  (array.set 1
                    (struct.get 2 0
                      (local.get 0))
                    (i32.add
                      (struct.get 2 1
                        (local.get 0))
                      (i32.const 2))
                    (i32.or
                      (i32.const 128)
                      (i32.and
                        (i32.shr_u
                          (local.get 2)
                          (i32.const 6))
                        (i32.const 63))))
                  (array.set 1
                    (struct.get 2 0
                      (local.get 0))
                    (i32.add
                      (struct.get 2 1
                        (local.get 0))
                      (i32.const 3))
                    (i32.or
                      (i32.const 128)
                      (i32.and
                        (local.get 2)
                        (i32.const 63))))
                  (struct.set 2 1
                    (local.get 0)
                    (i32.add
                      (struct.get 2 1
                        (local.get 0))
                      (i32.const 4)))))))))
    )
    (func (;26;) (type 30) (param (ref null 3) i32 i32)
      (local i32 (ref null 2))
      (block ;; label = @1
        (local.set 3
          (i32.const 0))
        (local.set 4
          (struct.get 3 7
            (local.get 0)))
        (block ;; label = @2
          (loop ;; label = @3
            (if ;; label = @4
              (i32.eqz
                (i32.lt_s
                  (local.get 3)
                  (local.get 2)))
              (then
                (br 3 (;@1;))))
            (block ;; label = @4
              (call 25
                (local.get 4)
                (local.get 1)))
            (local.set 3
              (i32.add
                (local.get 3)
                (i32.const 1)))
            (br 0 (;@3;)))))
    )
    (func (;27;) (type 31) (param (ref null 3) i32 (ref null 2) i32) (result i32)
      (local (ref null 2) i32 i32 i32 i32 i32 i32 i32 i32 i32 (ref null 2) (ref null 2) i32 i32)
      (local.set 4
        (struct.new 2
          (array.new_default 1
            (i32.const 0))
          (i32.const 0)))
      (if ;; label = @1
        (local.get 1)
        (then
          (local.set 4
            (struct.new 2
              (array.new_data 1 11
                (i32.const 0)
                (i32.const 1))
              (i32.const 1))))
        (else
          (if ;; label = @2
            (struct.get_u 3 2
              (local.get 0))
            (then
              (local.set 4
                (struct.new 2
                  (array.new_data 1 12
                    (i32.const 0)
                    (i32.const 1))
                  (i32.const 1)))))))
      (local.set 5
        (struct.get 2 1
          (local.get 4)))
      (local.set 6
        (struct.get 2 1
          (local.get 2)))
      (local.set 7
        (i32.add
          (i32.add
            (local.get 5)
            (local.get 6))
          (local.get 3)))
      (if ;; label = @1
        (if (result i32) ;; label = @1
          (i32.le_s
            (struct.get 3 5
              (local.get 0))
            (i32.const 0))
          (then
            (i32.const 1))
          (else
            (i32.ge_s
              (local.get 7)
              (struct.get 3 5
                (local.get 0)))))
        (then
          (if ;; label = @2
            (i32.gt_s
              (local.get 5)
              (i32.const 0))
            (then
              (call 24
                (struct.get 3 7
                  (local.get 0))
                (local.get 4))))
          (if ;; label = @2
            (i32.gt_s
              (local.get 6)
              (i32.const 0))
            (then
              (call 24
                (struct.get 3 7
                  (local.get 0))
                (local.get 2))))
          (return
            (call 23
              (struct.get 3 7
                (local.get 0))
              (local.get 3)))))
      (local.set 8
        (i32.sub
          (struct.get 3 5
            (local.get 0))
          (local.get 7)))
      (if ;; label = @1
        (struct.get_u 3 4
          (local.get 0))
        (then
          (if ;; label = @2
            (i32.gt_s
              (local.get 5)
              (i32.const 0))
            (then
              (call 24
                (struct.get 3 7
                  (local.get 0))
                (local.get 4))))
          (if ;; label = @2
            (i32.gt_s
              (local.get 6)
              (i32.const 0))
            (then
              (call 24
                (struct.get 3 7
                  (local.get 0))
                (local.get 2))))
          (call 26
            (local.get 0)
            (i32.const 48)
            (local.get 8))
          (return
            (call 23
              (struct.get 3 7
                (local.get 0))
              (local.get 3)))))
      (local.set 9
        (struct.get 3 1
          (local.get 0)))
      (local.set 16
        (local.get 9))
      (if ;; label = @1
        (if (result i32) ;; label = @1
          (i32.eq
            (local.get 16)
            (i32.const 0))
          (then
            (i32.const 1))
          (else
            (i32.const 0)))
        (then
          (if ;; label = @2
            (i32.gt_s
              (local.get 5)
              (i32.const 0))
            (then
              (call 24
                (struct.get 3 7
                  (local.get 0))
                (local.get 4))))
          (if ;; label = @2
            (i32.gt_s
              (local.get 6)
              (i32.const 0))
            (then
              (call 24
                (struct.get 3 7
                  (local.get 0))
                (local.get 2))))
          (local.set 10
            (call 23
              (struct.get 3 7
                (local.get 0))
              (local.get 3)))
          (call 26
            (local.get 0)
            (struct.get 3 0
              (local.get 0))
            (local.get 8))
          (return
            (local.get 10)))
        (else
          (local.set 17
            (local.get 9))
          (if ;; label = @2
            (if (result i32) ;; label = @2
              (i32.eq
                (local.get 17)
                (i32.const 1))
              (then
                (i32.const 1))
              (else
                (i32.const 0)))
            (then
              (local.set 11
                (i32.div_s
                  (local.get 8)
                  (i32.const 2)))
              (local.set 12
                (i32.sub
                  (local.get 8)
                  (local.get 11)))
              (call 26
                (local.get 0)
                (struct.get 3 0
                  (local.get 0))
                (local.get 11))
              (if ;; label = @3
                (i32.gt_s
                  (local.get 5)
                  (i32.const 0))
                (then
                  (call 24
                    (struct.get 3 7
                      (local.get 0))
                    (local.get 4))))
              (if ;; label = @3
                (i32.gt_s
                  (local.get 6)
                  (i32.const 0))
                (then
                  (call 24
                    (struct.get 3 7
                      (local.get 0))
                    (local.get 2))))
              (local.set 13
                (call 23
                  (struct.get 3 7
                    (local.get 0))
                  (local.get 3)))
              (call 26
                (local.get 0)
                (struct.get 3 0
                  (local.get 0))
                (local.get 12))
              (return
                (local.get 13)))
            (else
              (call 26
                (local.get 0)
                (struct.get 3 0
                  (local.get 0))
                (local.get 8))
              (if ;; label = @3
                (i32.gt_s
                  (local.get 5)
                  (i32.const 0))
                (then
                  (call 24
                    (struct.get 3 7
                      (local.get 0))
                    (local.get 4))))
              (if ;; label = @3
                (i32.gt_s
                  (local.get 6)
                  (i32.const 0))
                (then
                  (call 24
                    (struct.get 3 7
                      (local.get 0))
                    (local.get 2))))
              (return
                (call 23
                  (struct.get 3 7
                    (local.get 0))
                  (local.get 3)))))))
      (unreachable)
    )
    (data (;0;) "Assertion failed in ")
    (data (;1;) "__test_0_greeting")
    (data (;2;) " at ")
    (data (;3;) "/home/user/wado/wado-compiler/tests/fixtures/hello_test.wado")
    (data (;4;) ":")
    (data (;5;) "\0acondition: 1 + 1 == 2\0a")
    (data (;6;) "1 + 1: ")
    (data (;7;) "\0a")
    (data (;8;) "__test_1")
    (data (;9;) "\0acondition: true\0a")
    (data (;10;) "")
    (data (;11;) "-")
    (data (;12;) "+")
  )
  (core instance $wasi-instance (;1;)
    (export "stream-drop-writable" (func $stream.drop-writable))
    (export "stream-new" (func $stream.new))
    (export "stream-write" (func $stream.write))
    (export "subtask-drop" (func $subtask.drop))
    (export "task-return" (func $task.return))
    (export "waitable-join" (func $waitable.join))
    (export "waitable-set-new" (func $waitable-set.new))
    (export "waitable-set-wait" (func $waitable-set.wait))
    (export "wasi:cli/Stderr::write_via_stream" (func $wasi:cli/Stderr::write_via_stream))
  )
  (core instance $mem-instance (;2;)
    (export "memory" (memory $memory))
    (export "realloc" (func $realloc))
  )
  (core instance $main (;3;) (instantiate $main-mod
      (with "wasi" (instance $wasi-instance))
      (with "mem" (instance $mem-instance))
    )
  )
  (alias core export $main "__test_0_greeting" (core func $test-0-greeting-core (;10;)))
  (type $test-0-greeting-func-type (;5;) (func async (result $result-unit)))
  (func $test-0-greeting (;1;) (type $test-0-greeting-func-type) (canon lift (core func $test-0-greeting-core) async (memory $memory)))
  (export $"#func2 test-0-greeting" (@name "test-0-greeting") (;2;) "test-0-greeting" (func $test-0-greeting))
  (alias core export $main "__test_1" (core func $test-1-core (;11;)))
  (type $test-1-func-type (;6;) (func async (result $result-unit)))
  (func $test-1 (;3;) (type $test-1-func-type) (canon lift (core func $test-1-core) async (memory $memory)))
  (export $"#func4 test-1" (@name "test-1") (;4;) "test-1" (func $test-1))
)

