;; Golden WAT: wasi:cli/command with -O2
;; Source: wado-compiler/tests/fixtures/hello.wado
;; Generated by: make update-golden-wat-fixtures

(component
  (type $types-instance-type (;0;)
    (instance
      (type (;0;) (enum "io" "illegal-byte-sequence" "pipe"))
      (export (;1;) "error-code" (type (eq 0)))
    )
  )
  (import "wasi:cli/types@0.3.0-rc-2026-01-06" (instance $wasi:cli/types@0.3.0-rc-2026-01-06 (;0;) (type $types-instance-type)))
  (alias export $wasi:cli/types@0.3.0-rc-2026-01-06 "error-code" (type $error-code (;1;)))
  (type $stdout-instance-type (;2;)
    (instance
      (type (;0;) (stream u8))
      (alias outer 1 $error-code (type (;1;)))
      (type (;2;) (result (error 1)))
      (type (;3;) (func async (param "data" 0) (result 2)))
      (export (;0;) "write-via-stream" (func (type 3)))
    )
  )
  (import "wasi:cli/stdout@0.3.0-rc-2026-01-06" (instance $wasi:cli/stdout@0.3.0-rc-2026-01-06 (;1;) (type $stdout-instance-type)))
  (alias export $wasi:cli/stdout@0.3.0-rc-2026-01-06 "write-via-stream" (func $write-via-stream (;0;)))
  (type $stream-u8 (;3;) (stream u8))
  (type $result-unit (;4;) (result))
  (core module $mem-mod (;0;)
    (type $realloc (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (memory (;0;) 17)
    (global (;0;) (mut i32) (i32.const 1024))
    (export "memory" (memory 0))
    (export "realloc" (func $realloc))
    (func $realloc (;0;) (type $realloc) (param i32 i32 i32 i32) (result i32)
      (local i32)
      (local.set 4
        (i32.and
          (i32.sub
            (i32.add
              (global.get 0)
              (local.get 2))
            (i32.const 1))
          (i32.sub
            (i32.const 0)
            (local.get 2))))
      (global.set 0
        (i32.add
          (local.get 4)
          (local.get 3)))
      (local.get 4)
    )
  )
  (core instance $mem (;0;) (instantiate $mem-mod))
  (alias core export $mem "memory" (core memory $memory (;0;)))
  (alias core export $mem "realloc" (core func $realloc (;0;)))
  (core func $stream.drop-writable (;1;) (canon stream.drop-writable $stream-u8))
  (core func $stream.new (;2;) (canon stream.new $stream-u8))
  (core func $stream.write (;3;) (canon stream.write $stream-u8 (memory $memory) (realloc $realloc)))
  (core func $subtask.drop (;4;) (canon subtask.drop))
  (core func $task.return (;5;) (canon task.return (result $result-unit) (memory $memory)))
  (core func $waitable.join (;6;) (canon waitable.join))
  (core func $waitable-set.new (;7;) (canon waitable-set.new))
  (core func $waitable-set.wait (;8;) (canon waitable-set.wait (memory $memory)))
  (core func $wasi:cli/Stdout::write_via_stream (;9;) (canon lower (func $write-via-stream) async (memory $memory) (realloc $realloc)))
  (core module $main-mod (;1;)
    (rec
      (type (;0;) (sub (struct (field (mut i32)))))
      (type (;1;) (array (mut i8)))
      (type (;2;) (sub (struct (field (mut (ref 1))) (field (mut i32)))))
      (type (;3;) (array (mut i64)))
      (type (;4;) (sub (struct (field (mut (ref 3))) (field (mut i32)))))
    )
    (type (;5;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;6;) (func (param i32)))
    (type (;7;) (func (result i64)))
    (type (;8;) (func (param i32 i32 i32) (result i32)))
    (type (;9;) (func (param i32)))
    (type (;10;) (func (param i32)))
    (type (;11;) (func (param i32 i32)))
    (type (;12;) (func (result i32)))
    (type (;13;) (func (param i32 i32) (result i32)))
    (type (;14;) (func (param i32 i32) (result i32)))
    (type (;15;) (func))
    (type (;16;) (func))
    (type (;17;) (func (param i32 (ref null 2) i32)))
    (type (;18;) (func (param (ref null 2))))
    (type (;19;) (func (param i32)))
    (type (;20;) (func))
    (import "mem" "realloc" (func (;0;) (type 5)))
    (import "wasi" "stream-drop-writable" (func (;1;) (type 6)))
    (import "wasi" "stream-new" (func (;2;) (type 7)))
    (import "wasi" "stream-write" (func (;3;) (type 8)))
    (import "wasi" "subtask-drop" (func (;4;) (type 9)))
    (import "wasi" "task-return" (func (;5;) (type 10)))
    (import "wasi" "waitable-join" (func (;6;) (type 11)))
    (import "wasi" "waitable-set-new" (func (;7;) (type 12)))
    (import "wasi" "waitable-set-wait" (func (;8;) (type 13)))
    (import "wasi" "wasi:cli/Stdout::write_via_stream" (func (;9;) (type 14)))
    (import "mem" "memory" (memory (;0;) 1))
    (global (;0;) (mut (ref null 4)) (ref.null none))
    (global (;1;) (mut i32) (i32.const 0))
    (export "run" (func 11))
    (func (;10;) (type 15)
      (block ;; label = @1
        (if ;; label = @2
          (global.get 1)
          (then
            (br 1 (;@1;))))
        (call 15)
        (global.set 1
          (i32.const 1)))
      (call 13
        (struct.new 2
          (ref.as_non_null
            (array.new_data 1 0
              (i32.const 0)
              (i32.const 13)))
          (i32.const 13)))
    )
    (func (;11;) (type 16)
      (call 10)
      (call 5
        (i32.const 0))
    )
    (func (;12;) (type 17) (param i32 (ref null 2) i32)
      (local i32 (ref null 1) i32 i32 i32 i32 (ref null 2) (ref null 2))
      (local.set 3
        (struct.get 2 1
          (local.get 1)))
      (local.set 4
        (struct.get 2 0
          (local.get 1)))
      (local.set 5
        (if (result i32) ;; label = @1
          (local.get 2)
          (then
            (i32.add
              (local.get 3)
              (i32.const 1)))
          (else
            (local.get 3))))
      (local.set 6
        (call 0
          (i32.const 0)
          (i32.const 0)
          (i32.const 1)
          (local.get 5)))
      (block ;; label = @1
        (local.set 7
          (i32.const 0))
        (block ;; label = @2
          (loop ;; label = @3
            (if ;; label = @4
              (i32.eqz
                (i32.lt_s
                  (local.get 7)
                  (local.get 3)))
              (then
                (br 3 (;@1;))))
            (block ;; label = @4
              (local.set 8
                (array.get_u 1
                  (local.get 4)
                  (local.get 7)))
              (i32.store8
                (i32.add
                  (local.get 6)
                  (local.get 7))
                (local.get 8)))
            (local.set 7
              (i32.add
                (local.get 7)
                (i32.const 1)))
            (br 0 (;@3;)))))
      (if ;; label = @1
        (local.get 2)
        (then
          (i32.store8
            (i32.add
              (local.get 6)
              (local.get 3))
            (i32.const 10))))
      (drop
        (call 3
          (local.get 0)
          (local.get 6)
          (local.get 5)))
      (call 1
        (local.get 0))
    )
    (func (;13;) (type 18) (param (ref null 2))
      (local i64 i32 i32 i32)
      (local.set 1
        (call 2))
      (local.set 2
        (i32.wrap_i64
          (local.get 1)))
      (local.set 3
        (i32.wrap_i64
          (i64.shr_s
            (local.get 1)
            (i64.const 32))))
      (local.set 4
        (call 9
          (local.get 2)
          (i32.const 2048)))
      (call 12
        (local.get 3)
        (local.get 0)
        (i32.const 1))
      (call 14
        (local.get 4))
    )
    (func (;14;) (type 19) (param i32)
      (local i32 i32 i32)
      (local.set 1
        (i32.shr_s
          (local.get 0)
          (i32.const 4)))
      (if ;; label = @1
        (i32.ne
          (local.get 1)
          (i32.const 0))
        (then
          (local.set 2
            (call 7))
          (call 6
            (local.get 1)
            (local.get 2))
          (local.set 3
            (call 0
              (i32.const 0)
              (i32.const 0)
              (i32.const 4)
              (i32.const 8)))
          (drop
            (call 8
              (local.get 2)
              (local.get 3)))
          (drop
            (call 0
              (local.get 3)
              (i32.const 8)
              (i32.const 4)
              (i32.const 0)))
          (call 4
            (local.get 1))))
    )
    (func (;15;) (type 20)
      (global.set 0
        (struct.new 4
          (ref.as_non_null
            (array.new_fixed 3 20
              (i64.const 1)
              (i64.const 10)
              (i64.const 100)
              (i64.const 1000)
              (i64.const 10000)
              (i64.const 100000)
              (i64.const 1000000)
              (i64.const 10000000)
              (i64.const 100000000)
              (i64.const 1000000000)
              (i64.const 10000000000)
              (i64.const 100000000000)
              (i64.const 1000000000000)
              (i64.const 10000000000000)
              (i64.const 100000000000000)
              (i64.const 1000000000000000)
              (i64.const 10000000000000000)
              (i64.const 100000000000000000)
              (i64.const 1000000000000000000)
              (i64.const -8446744073709551616)))
          (i32.const 20)))
    )
    (data (;0;) "Hello, world!")
  )
  (core instance $wasi-instance (;1;)
    (export "stream-drop-writable" (func $stream.drop-writable))
    (export "stream-new" (func $stream.new))
    (export "stream-write" (func $stream.write))
    (export "subtask-drop" (func $subtask.drop))
    (export "task-return" (func $task.return))
    (export "waitable-join" (func $waitable.join))
    (export "waitable-set-new" (func $waitable-set.new))
    (export "waitable-set-wait" (func $waitable-set.wait))
    (export "wasi:cli/Stdout::write_via_stream" (func $wasi:cli/Stdout::write_via_stream))
  )
  (core instance $mem-instance (;2;)
    (export "memory" (memory $memory))
    (export "realloc" (func $realloc))
  )
  (core instance $main (;3;) (instantiate $main-mod
      (with "wasi" (instance $wasi-instance))
      (with "mem" (instance $mem-instance))
    )
  )
  (alias core export $main "run" (core func $run-core (;10;)))
  (type $run-func-type (;5;) (func async (result $result-unit)))
  (func $run (;1;) (type $run-func-type) (canon lift (core func $run-core) async (memory $memory)))
  (export $"#func2 run" (@name "run") (;2;) "run" (func $run))
)

