;; Golden WAT: test with -O2
;; Source: wado-compiler/tests/fixtures/hello_test.wado
;; Generated by: make update-golden-wat-fixtures

(component
  (type $types-instance-type (;0;)
    (instance
      (type (;0;) (enum "io" "illegal-byte-sequence" "pipe"))
      (export (;1;) "error-code" (type (eq 0)))
    )
  )
  (import "wasi:cli/types@0.3.0-rc-2026-01-06" (instance $wasi:cli/types@0.3.0-rc-2026-01-06 (;0;) (type $types-instance-type)))
  (alias export $wasi:cli/types@0.3.0-rc-2026-01-06 "error-code" (type $error-code (;1;)))
  (type $stream-u8 (;2;) (stream u8))
  (type $result-unit (;3;) (result))
  (core module $mem-mod (;0;)
    (type $realloc (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (memory (;0;) 17)
    (global (;0;) (mut i32) (i32.const 1024))
    (export "memory" (memory 0))
    (export "realloc" (func $realloc))
    (func $realloc (;0;) (type $realloc) (param i32 i32 i32 i32) (result i32)
      (local i32)
      (local.set 4
        (i32.and
          (i32.sub
            (i32.add
              (global.get 0)
              (local.get 2))
            (i32.const 1))
          (i32.sub
            (i32.const 0)
            (local.get 2))))
      (global.set 0
        (i32.add
          (local.get 4)
          (local.get 3)))
      (local.get 4)
    )
  )
  (core instance $mem (;0;) (instantiate $mem-mod))
  (alias core export $mem "memory" (core memory $memory (;0;)))
  (alias core export $mem "realloc" (core func $realloc (;0;)))
  (core func $task.return (;1;) (canon task.return (result $result-unit) (memory $memory)))
  (core module $main-mod (;1;)
    (rec
      (type (;0;) (sub (struct (field (mut i32)))))
      (type (;1;) (array (mut i8)))
      (type (;2;) (sub (struct (field (mut (ref 1))) (field (mut i32)))))
      (type (;3;) (sub (struct (field (mut i32)) (field (mut i32)) (field (mut i8)) (field (mut i8)) (field (mut i8)) (field (mut i32)) (field (mut i32)) (field (mut (ref 2))))))
      (type (;4;) (array (mut i64)))
      (type (;5;) (sub (struct (field (mut (ref 4))) (field (mut i32)))))
    )
    (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;7;) (func (param i32)))
    (type (;8;) (func))
    (type (;9;) (func))
    (type (;10;) (func))
    (type (;11;) (func))
    (type (;12;) (func))
    (type (;13;) (func (param (ref null 5) i64)))
    (import "mem" "realloc" (func (;0;) (type 6)))
    (import "wasi" "task-return" (func (;1;) (type 7)))
    (import "mem" "memory" (memory (;0;) 1))
    (global (;0;) (mut i32) (i32.const 0))
    (export "__test_0_greeting" (func 4))
    (export "__test_1" (func 5))
    (func (;2;) (type 8)
      (local i32 i32 (ref null 2) (ref null 3) i32 (ref null 2) (ref null 0) (ref null 3) (ref null 0) (ref null 3) (ref null 2) (ref null 0) (ref null 3) (ref null 0) (ref null 3))
      (block ;; label = @1
        (if ;; label = @2
          (global.get 0)
          (then
            (br 1 (;@1;))))
        (call 6)
        (global.set 0
          (i32.const 1)))
    )
    (func (;3;) (type 9)
      (local i32 (ref null 2) (ref null 3) i32 (ref null 2) (ref null 0) (ref null 3) (ref null 0) (ref null 3))
      (block ;; label = @1
        (if ;; label = @2
          (global.get 0)
          (then
            (br 1 (;@1;))))
        (call 6)
        (global.set 0
          (i32.const 1)))
    )
    (func (;4;) (type 10)
      (local i32 i32 (ref null 2) (ref null 3) i32 (ref null 2) (ref null 0) (ref null 3) (ref null 0) (ref null 3) (ref null 2) (ref null 0) (ref null 3) (ref null 0) (ref null 3))
      (block ;; label = @1
        (block ;; label = @2
          (if ;; label = @3
            (global.get 0)
            (then
              (br 1 (;@2;))))
          (call 6)
          (global.set 0
            (i32.const 1))))
      (call 1
        (i32.const 0))
    )
    (func (;5;) (type 11)
      (local i32 (ref null 2) (ref null 3) i32 (ref null 2) (ref null 0) (ref null 3) (ref null 0) (ref null 3))
      (block ;; label = @1
        (block ;; label = @2
          (if ;; label = @3
            (global.get 0)
            (then
              (br 1 (;@2;))))
          (call 6)
          (global.set 0
            (i32.const 1))))
      (call 1
        (i32.const 0))
    )
    (func (;6;) (type 12)
      (local (ref null 5) i32 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i64 (ref null 5) i32)
    )
    (func (;7;) (type 13) (param (ref null 5) i64)
      (local i32 i32 i32 (ref null 4) i32 i32)
      (local.set 2
        (struct.get 5 1
          (local.get 0)))
      (local.set 3
        (array.len
          (struct.get 5 0
            (local.get 0))))
      (if ;; label = @1
        (i32.ge_s
          (local.get 2)
          (local.get 3))
        (@metadata.code.branch_hint "\00")
        (then
          (local.set 4
            (block (result i32) ;; label = @2
              (local.set 6
                (i32.mul
                  (local.get 3)
                  (i32.const 2)))
              (br 0 (;@2;)
                (select (result i32)
                  (local.get 6)
                  (i32.const 4)
                  (i32.gt_s
                    (local.get 6)
                    (i32.const 4))))))
          (local.set 5
            (array.new_default 4
              (local.get 4)))
          (array.copy 4 4
            (local.get 5)
            (i32.const 0)
            (struct.get 5 0
              (local.get 0))
            (i32.const 0)
            (local.get 2))
          (struct.set 5 0
            (local.get 0)
            (ref.as_non_null
              (local.get 5)))))
      (array.set 4
        (struct.get 5 0
          (local.get 0))
        (local.get 2)
        (local.get 1))
      (struct.set 5 1
        (local.get 0)
        (i32.add
          (local.get 2)
          (i32.const 1)))
    )
    (data (;0;) "Assertion failed in ")
    (data (;1;) "__test_0_greeting")
    (data (;2;) " at ")
    (data (;3;) "wado-compiler/tests/fixtures/hello_test.wado")
    (data (;4;) ":")
    (data (;5;) "\0acondition: 1 + 1 == 2\0a")
    (data (;6;) "1 + 1: ")
    (data (;7;) "\0a")
    (data (;8;) "__test_1")
    (data (;9;) "\0acondition: true\0a")
  )
  (core instance $wasi-instance (;1;)
    (export "task-return" (func $task.return))
  )
  (core instance $mem-instance (;2;)
    (export "memory" (memory $memory))
    (export "realloc" (func $realloc))
  )
  (core instance $main (;3;) (instantiate $main-mod
      (with "wasi" (instance $wasi-instance))
      (with "mem" (instance $mem-instance))
    )
  )
  (alias core export $main "__test_0_greeting" (core func $test-0-greeting-core (;2;)))
  (type $test-0-greeting-func-type (;4;) (func async (result $result-unit)))
  (func $test-0-greeting (;0;) (type $test-0-greeting-func-type) (canon lift (core func $test-0-greeting-core) async (memory $memory)))
  (export $"#func1 test-0-greeting" (@name "test-0-greeting") (;1;) "test-0-greeting" (func $test-0-greeting))
  (alias core export $main "__test_1" (core func $test-1-core (;3;)))
  (type $test-1-func-type (;5;) (func async (result $result-unit)))
  (func $test-1 (;2;) (type $test-1-func-type) (canon lift (core func $test-1-core) async (memory $memory)))
  (export $"#func3 test-1" (@name "test-1") (;3;) "test-1" (func $test-1))
)

