;; Golden WAT: wasi:cli/command with -O2
;; Source: wado-compiler/tests/fixtures/hello.wado
;; Generated by: make update-golden-wat-fixtures

(component
  (type $types-instance-type (;0;)
    (instance
      (type (;0;) (enum "io" "illegal-byte-sequence" "pipe"))
      (export (;1;) "error-code" (type (eq 0)))
    )
  )
  (import "wasi:cli/types@0.3.0-rc-2026-01-06" (instance $wasi:cli/types@0.3.0-rc-2026-01-06 (;0;) (type $types-instance-type)))
  (alias export $wasi:cli/types@0.3.0-rc-2026-01-06 "error-code" (type $error-code (;1;)))
  (type $stdout-instance-type (;2;)
    (instance
      (type (;0;) (stream u8))
      (alias outer 1 $error-code (type (;1;)))
      (type (;2;) (result (error 1)))
      (type (;3;) (func async (param "data" 0) (result 2)))
      (export (;0;) "write-via-stream" (func (type 3)))
    )
  )
  (import "wasi:cli/stdout@0.3.0-rc-2026-01-06" (instance $wasi:cli/stdout@0.3.0-rc-2026-01-06 (;1;) (type $stdout-instance-type)))
  (alias export $wasi:cli/stdout@0.3.0-rc-2026-01-06 "write-via-stream" (func $write-via-stream (;0;)))
  (type $stream-u8 (;3;) (stream u8))
  (type $result-unit (;4;) (result))
  (core module $mem-mod (;0;)
    (type $realloc (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (memory (;0;) 17)
    (global (;0;) (mut i32) (i32.const 1024))
    (export "memory" (memory 0))
    (export "realloc" (func $realloc))
    (func $realloc (;0;) (type $realloc) (param i32 i32 i32 i32) (result i32)
      (local i32)
      (local.set 4
        (i32.and
          (i32.sub
            (i32.add
              (global.get 0)
              (local.get 2))
            (i32.const 1))
          (i32.sub
            (i32.const 0)
            (local.get 2))))
      (global.set 0
        (i32.add
          (local.get 4)
          (local.get 3)))
      (local.get 4)
    )
  )
  (core instance $mem (;0;) (instantiate $mem-mod))
  (alias core export $mem "memory" (core memory $memory (;0;)))
  (alias core export $mem "realloc" (core func $realloc (;0;)))
  (core func $stream.drop-writable (;1;) (canon stream.drop-writable $stream-u8))
  (core func $stream.new (;2;) (canon stream.new $stream-u8))
  (core func $stream.write (;3;) (canon stream.write $stream-u8 (memory $memory) (realloc $realloc)))
  (core func $task.return (;4;) (canon task.return (result $result-unit) (memory $memory)))
  (core func $wasi:cli/Stdout::write_via_stream (;5;) (canon lower (func $write-via-stream) async (memory $memory) (realloc $realloc)))
  (core module $main-mod (;1;)
    (rec
      (type (;0;) (sub (struct (field (mut i32)))))
      (type (;1;) (array (mut i8)))
      (type (;2;) (sub (struct (field (mut (ref null 1))) (field (mut i32)))))
    )
    (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;4;) (func (param i32)))
    (type (;5;) (func (result i64)))
    (type (;6;) (func (param i32 i32 i32) (result i32)))
    (type (;7;) (func (param i32)))
    (type (;8;) (func (param i32 i32) (result i32)))
    (type (;9;) (func))
    (type (;10;) (func (param i32)))
    (type (;11;) (func))
    (type (;12;) (func (param i32 (ref null 2) i32)))
    (type (;13;) (func (param (ref null 2))))
    (import "mem" "realloc" (func (;0;) (type 3)))
    (import "wasi" "stream-drop-writable" (func (;1;) (type 4)))
    (import "wasi" "stream-new" (func (;2;) (type 5)))
    (import "wasi" "stream-write" (func (;3;) (type 6)))
    (import "wasi" "task-return" (func (;4;) (type 7)))
    (import "wasi" "wasi:cli/Stdout::write_via_stream" (func (;5;) (type 8)))
    (import "mem" "memory" (memory (;0;) 1))
    (export "run" (func 8))
    (func (;6;) (type 9)
      (call 10
        (struct.new 2
          (array.new_data 1 0
            (i32.const 0)
            (i32.const 13))
          (i32.const 13)))
    )
    (func (;7;) (type 10) (param i32)
      (drop
        (call 5
          (local.get 0)
          (i32.const 2048)))
    )
    (func (;8;) (type 11)
      (call 6)
      (call 4
        (i32.const 0))
    )
    (func (;9;) (type 12) (param i32 (ref null 2) i32)
      (local i32 (ref null 1) i32 i32 i32 i32 (ref null 2) (ref null 2))
      (local.set 3
        (struct.get 2 1
          (local.get 1)))
      (local.set 4
        (struct.get 2 0
          (local.get 1)))
      (local.set 5
        (if (result i32) ;; label = @1
          (local.get 2)
          (then
            (i32.add
              (local.get 3)
              (i32.const 1)))
          (else
            (local.get 3))))
      (local.set 6
        (call 0
          (i32.const 0)
          (i32.const 0)
          (i32.const 1)
          (local.get 5)))
      (block ;; label = @1
        (local.set 7
          (i32.const 0))
        (block ;; label = @2
          (loop ;; label = @3
            (if ;; label = @4
              (i32.eqz
                (i32.lt_s
                  (local.get 7)
                  (local.get 3)))
              (then
                (br 3 (;@1;))))
            (block ;; label = @4
              (local.set 8
                (array.get_u 1
                  (local.get 4)
                  (local.get 7)))
              (i32.store8
                (i32.add
                  (local.get 6)
                  (local.get 7))
                (local.get 8)))
            (local.set 7
              (i32.add
                (local.get 7)
                (i32.const 1)))
            (br 0 (;@3;)))))
      (if ;; label = @1
        (local.get 2)
        (then
          (i32.store8
            (i32.add
              (local.get 6)
              (local.get 3))
            (i32.const 10))))
      (drop
        (call 3
          (local.get 0)
          (local.get 6)
          (local.get 5)))
      (call 1
        (local.get 0))
    )
    (func (;10;) (type 13) (param (ref null 2))
      (local i64 i32 i32)
      (local.set 1
        (call 2))
      (local.set 2
        (i32.wrap_i64
          (local.get 1)))
      (local.set 3
        (i32.wrap_i64
          (i64.shr_s
            (local.get 1)
            (i64.const 32))))
      (call 7
        (local.get 2))
      (call 9
        (local.get 3)
        (local.get 0)
        (i32.const 1))
    )
    (data (;0;) "Hello, world!")
  )
  (core instance $wasi-instance (;1;)
    (export "stream-drop-writable" (func $stream.drop-writable))
    (export "stream-new" (func $stream.new))
    (export "stream-write" (func $stream.write))
    (export "task-return" (func $task.return))
    (export "wasi:cli/Stdout::write_via_stream" (func $wasi:cli/Stdout::write_via_stream))
  )
  (core instance $mem-instance (;2;)
    (export "memory" (memory $memory))
    (export "realloc" (func $realloc))
  )
  (core instance $main (;3;) (instantiate $main-mod
      (with "wasi" (instance $wasi-instance))
      (with "mem" (instance $mem-instance))
    )
  )
  (alias core export $main "run" (core func $run-core (;6;)))
  (type $run-func-type (;5;) (func async (result $result-unit)))
  (func $run (;1;) (type $run-func-type) (canon lift (core func $run-core) async (memory $memory)))
  (export $"#func2 run" (@name "run") (;2;) "run" (func $run))
)

