[package]
name = "wado-cli"
version = "0.1.0"
edition = "2024"
description = "CLI for the Wado programming language"
license = { workspace = true }

[[bin]]
name = "wado"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
wado-compiler = { path = "../wado-compiler" }
wasmprinter = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
