[package]
name = "wado-cli"
version = "0.1.0"
edition = "2024"
description = "CLI for the Wado programming language"
license = { workspace = true }

[lib]
name = "wado_cli"
path = "src/lib.rs"

[[bin]]
name = "wado"
path = "src/main.rs"

[dependencies]
wado-compiler = { path = "../wado-compiler" }
wado-lsp = { path = "../wado-lsp" }
wado-manifest = { path = "../wado-manifest" }
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
indexmap = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
webpki-roots = { workspace = true }
rustls-pemfile = { workspace = true }
lexopt = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true, features = ["net"] }
wasmprinter = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }
wasmtime-wasi-tls = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
jsonschema = { workspace = true }
predicates = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
