//! Golden file tests for lowered TIR output
//!
//! These tests verify that the optimized TIR output matches expected golden files.
//! Golden files are generated by `make update-golden-fixtures` and stored in
//! `tests/fixtures.golden/*.lowered.wado`.
//!
//! If a test fails, the optimizer or unparser behavior may have changed.
//! Review the diff and if the change is intentional, run `make update-golden-fixtures`
//! to regenerate the golden files.

use std::path::{Path, PathBuf};
use std::sync::Mutex;
use wado_compiler::{CompilerHost, OptLevel};

// ============================================================================
// Test Compiler Host (Filesystem-based)
// ============================================================================

/// A simple filesystem-based CompilerHost for tests
struct TestCompilerHost {
    base_path: PathBuf,
    diagnostics: Mutex<Vec<wado_compiler::Diagnostic>>,
}

impl TestCompilerHost {
    fn new(base_path: PathBuf) -> Self {
        Self {
            base_path,
            diagnostics: Mutex::new(Vec::new()),
        }
    }
}

impl CompilerHost for TestCompilerHost {
    fn load_source(
        &self,
        path: &str,
    ) -> impl std::future::Future<Output = Result<String, wado_compiler::SourceError>> + Send {
        let full_path = self.base_path.join(path);
        async move {
            std::fs::read_to_string(&full_path).map_err(|e| wado_compiler::SourceError::IoError {
                path: full_path.to_string_lossy().to_string(),
                message: e.to_string(),
            })
        }
    }

    fn emit_diagnostic(
        &self,
        diagnostic: wado_compiler::Diagnostic,
    ) -> impl std::future::Future<Output = ()> + Send {
        let diagnostics = &self.diagnostics;
        async move {
            diagnostics.lock().unwrap().push(diagnostic);
        }
    }
}

// ============================================================================
// Golden File Test Logic
// ============================================================================

/// Extract the entry module (empty path "") from the unparsed TIR modules
fn extract_entry_module(project: &wado_compiler::Project) -> String {
    for (path, module) in &project.tir_modules {
        // Entry module has empty path
        if path.is_empty() {
            return wado_compiler::unparse::unparse_tir(module);
        }
    }
    panic!("Entry module not found in project");
}

/// Run a golden file test
async fn run_golden_test(golden_path: &Path) {
    // Read the golden file
    let golden_content = std::fs::read_to_string(golden_path)
        .unwrap_or_else(|e| panic!("Failed to read golden file {:?}: {}", golden_path, e));

    // Extract the source filename from the header
    // Format: "// Source: tests/fixtures/opt_inline_simple.wado"
    let source_line = golden_content
        .lines()
        .find(|line| line.starts_with("// Source:"))
        .expect("Golden file must have a '// Source:' header line");
    let source_relative = source_line.strip_prefix("// Source:").unwrap().trim();

    // Construct full source path
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let source_path = PathBuf::from(manifest_dir).join(source_relative);

    // Read the source file
    let source = std::fs::read_to_string(&source_path)
        .unwrap_or_else(|e| panic!("Failed to read source file {:?}: {}", source_path, e));

    // Create compiler host
    let base_path = source_path.parent().unwrap().to_path_buf();
    let host = TestCompilerHost::new(base_path);

    // Run dump_with_host with O2 optimization
    let result = wado_compiler::dump_with_host(
        &source,
        &host,
        Some(source_path.to_str().unwrap()),
        OptLevel::Full,
    )
    .await
    .unwrap_or_else(|e| panic!("Compilation failed for {:?}: {}", source_path, e));

    // Extract entry module from optimized project
    let project = result
        .optimized_project
        .expect("Optimized project should be available");
    let actual_module = extract_entry_module(&project);

    // Extract expected content (skip header lines)
    let expected_lines: Vec<&str> = golden_content
        .lines()
        .skip_while(|line| line.starts_with("//") || line.is_empty())
        .collect();
    let expected = expected_lines.join("\n");

    // Compare
    if actual_module.trim() != expected.trim() {
        // Print a diff-like output for debugging
        eprintln!("=== EXPECTED (from golden file) ===");
        eprintln!("{}", expected);
        eprintln!("=== ACTUAL (from compiler) ===");
        eprintln!("{}", actual_module);
        eprintln!("=== END ===");
        panic!(
            "Golden file mismatch for {:?}\nRun `make update-golden-fixtures` if the change is intentional.",
            golden_path
        );
    }
}

// ============================================================================
// Test Discovery
// ============================================================================

/// Find all golden files in the fixtures.golden directory
fn find_golden_files() -> Vec<PathBuf> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let golden_dir = PathBuf::from(manifest_dir).join("tests/fixtures.golden");

    if !golden_dir.exists() {
        return Vec::new();
    }

    std::fs::read_dir(&golden_dir)
        .unwrap_or_else(|e| panic!("Failed to read golden directory {:?}: {}", golden_dir, e))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().map(|ext| ext == "wado").unwrap_or(false))
        .collect()
}

// ============================================================================
// Tests
// ============================================================================

#[tokio::test]
async fn golden_file_tests() {
    let golden_files = find_golden_files();

    if golden_files.is_empty() {
        eprintln!(
            "Warning: No golden files found. Run `make update-golden-fixtures` to generate them."
        );
        return;
    }

    for golden_path in golden_files {
        let test_name = golden_path.file_stem().unwrap().to_string_lossy();
        eprintln!("Running golden test: {}", test_name);
        run_golden_test(&golden_path).await;
    }
}
