//! Golden file tests for lowered TIR output
//!
//! These tests verify that the optimized TIR output matches expected golden files.
//! Golden files are generated by `make update-golden-fixtures` and stored in
//! `tests/fixtures.golden/*.lowered.wado`.
//!
//! If a test fails, the optimizer or unparser behavior may have changed.
//! Review the diff and if the change is intentional, run `make update-golden-fixtures`
//! to regenerate the golden files.

use std::path::{Path, PathBuf};
use std::sync::Mutex;
use wado_compiler::{CompilerHost, OptLevel};

// ============================================================================
// Test Compiler Host (Filesystem-based)
// ============================================================================

/// A simple filesystem-based CompilerHost for tests
struct TestCompilerHost {
    base_path: PathBuf,
    diagnostics: Mutex<Vec<wado_compiler::Diagnostic>>,
}

impl TestCompilerHost {
    fn new(base_path: PathBuf) -> Self {
        Self {
            base_path,
            diagnostics: Mutex::new(Vec::new()),
        }
    }
}

impl CompilerHost for TestCompilerHost {
    fn load_source(
        &self,
        path: &str,
    ) -> impl std::future::Future<Output = Result<String, wado_compiler::SourceError>> + Send {
        let full_path = self.base_path.join(path);
        async move {
            std::fs::read_to_string(&full_path).map_err(|e| wado_compiler::SourceError::IoError {
                path: full_path.to_string_lossy().to_string(),
                message: e.to_string(),
            })
        }
    }

    fn emit_diagnostic(&self, diagnostic: wado_compiler::Diagnostic) {
        self.diagnostics.lock().unwrap().push(diagnostic);
    }
}

// ============================================================================
// Golden File Test Logic
// ============================================================================

/// Extract the entry module from the unparsed TIR modules
fn extract_entry_module(project: &wado_compiler::Project) -> String {
    for (module_source, module) in &project.tir_modules {
        // Entry module is ModuleSource::EntryPoint
        if module_source.is_entry_point() {
            return wado_compiler::unparse::unparse_tir(module);
        }
    }
    panic!("Entry module not found in project");
}

/// Run a golden file test
fn run_golden_test(golden_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    // Create tokio runtime for async operations
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()?;

    rt.block_on(async {
        // Read the golden file
        let golden_content = std::fs::read_to_string(golden_path)
            .unwrap_or_else(|e| panic!("Failed to read golden file {:?}: {}", golden_path, e));

        // Extract the source filename from the header
        // Format: "// Source: wado-compiler/tests/fixtures/opt_inline_simple.wado"
        let source_line = golden_content
            .lines()
            .find(|line| line.starts_with("// Source:"))
            .expect("Golden file must have a '// Source:' header line");
        let source_from_header = source_line.strip_prefix("// Source:").unwrap().trim();

        // Strip "wado-compiler/" prefix if present (CLI runs from repo root)
        let source_relative = source_from_header
            .strip_prefix("wado-compiler/")
            .unwrap_or(source_from_header);

        // Construct full source path
        let manifest_dir = env!("CARGO_MANIFEST_DIR");
        let source_path = PathBuf::from(manifest_dir).join(source_relative);

        // Read the source file
        let source = std::fs::read_to_string(&source_path)
            .unwrap_or_else(|e| panic!("Failed to read source file {:?}: {}", source_path, e));

        // Create compiler host
        let base_path = source_path.parent().unwrap().to_path_buf();
        let host = TestCompilerHost::new(base_path);

        // Run dump_with_host with O2 optimization
        // Use the original path from header to match expected #file output
        let result = wado_compiler::dump_with_host(
            &source,
            &host,
            Some(source_from_header),
            OptLevel::Full,
        )
        .await
        .unwrap_or_else(|e| panic!("Compilation failed for {:?}: {}", source_path, e));

        // Extract entry module from optimized project
        let project = result
            .optimized_project
            .expect("Optimized project should be available");
        let actual_module_raw = extract_entry_module(&project);

        // Remove __DATA__ section if present (not part of TIR)
        let actual_module = if let Some(pos) = actual_module_raw.find("\n__DATA__\n") {
            actual_module_raw[..pos].to_string()
        } else {
            actual_module_raw
        };

        // Extract expected content (skip header lines)
        let expected_lines: Vec<&str> = golden_content
            .lines()
            .skip_while(|line| line.starts_with("//") || line.is_empty())
            .collect();
        let expected = expected_lines.join("\n");

        // Compare
        if actual_module.trim() != expected.trim() {
            // Print a diff-like output for debugging
            eprintln!("=== EXPECTED (from golden file) ===");
            eprintln!("{}", expected);
            eprintln!("=== ACTUAL (from compiler) ===");
            eprintln!("{}", actual_module);
            eprintln!("=== END ===");
            panic!(
                "Golden file mismatch for {:?}\nRun `make update-golden-fixtures` if the change is intentional.",
                golden_path
            );
        }

        Ok(())
    })
}

// ============================================================================
// Tests
// ============================================================================

datatest_mini::harness! {
    // Run golden file tests for all .lowered.wado files in tests/fixtures.golden/
    { test = run_golden_test, root = "tests/fixtures.golden", pattern = r"\.lowered\.wado$" },
}
