//! Golden file tests for lowered TIR output
//!
//! These tests verify that the optimized TIR output matches expected golden files.
//! Golden files are generated by `make update-golden-fixtures` and stored in
//! `tests/fixtures.golden/*.lowered.wado`.
//!
//! If a test fails, the optimizer or unparser behavior may have changed.
//! Review the diff and if the change is intentional, run `make update-golden-fixtures`
//! to regenerate the golden files.

mod common;

use std::path::{Path, PathBuf};
use wado_compiler::OptLevel;

/// Extract the entry module from the unparsed TIR modules
fn extract_entry_module(project: &wado_compiler::Project) -> String {
    for (module_source, module) in &project.tir_modules {
        // Entry module is ModuleSource::EntryPoint
        if module_source.is_entry_point() {
            return wado_compiler::unparse::unparse_tir(module);
        }
    }
    panic!("Entry module not found in project");
}

/// Run a golden file test
fn run_golden_test(
    golden_path: &Path,
    golden_content: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    common::runtime().block_on(async {

        // Extract the source filename from the header
        // Format: "// Source: wado-compiler/tests/fixtures/opt_inline_simple.wado"
        let source_line = golden_content
            .lines()
            .find(|line| line.starts_with("// Source:"))
            .expect("Golden file must have a '// Source:' header line");
        let source_from_header = source_line.strip_prefix("// Source:").unwrap().trim();

        // Strip "wado-compiler/" prefix if present (CLI runs from repo root)
        let source_relative = source_from_header
            .strip_prefix("wado-compiler/")
            .unwrap_or(source_from_header);

        // Construct full source path
        let manifest_dir = env!("CARGO_MANIFEST_DIR");
        let source_path = PathBuf::from(manifest_dir).join(source_relative);

        // Read the source file
        let source = std::fs::read_to_string(&source_path)
            .unwrap_or_else(|e| panic!("Failed to read source file {:?}: {}", source_path, e));

        // Extract target world from __DATA__ section
        let target_world = common::extract_data_section(&source).and_then(|data| {
            let json: serde_json::Value = serde_json::from_str(data.trim()).ok()?;
            json.get("world")?.as_str().map(String::from)
        });

        // Create compiler host
        let base_path = source_path.parent().unwrap().to_path_buf();
        let host = common::FilesystemHost::new(base_path);

        // Run dump with O2 optimization and the target world from __DATA__
        // Use the original path from header to match expected #file output
        let result = wado_compiler::dump_with_host_and_world(
            &source,
            &host,
            Some(source_from_header),
            OptLevel::O2,
            target_world.as_deref(),
        )
        .await
        .unwrap_or_else(|e| panic!("Compilation failed for {:?}: {}", source_path, e));

        // Extract entry module from optimized project
        let project = result
            .optimized_project
            .expect("Optimized project should be available");
        let actual_module_raw = extract_entry_module(&project);

        // Remove __DATA__ section if present (not part of TIR)
        let actual_module = if let Some(pos) = actual_module_raw.find("\n__DATA__\n") {
            actual_module_raw[..pos].to_string()
        } else {
            actual_module_raw
        };

        // Extract expected content (skip only the 3 header lines and the blank line after)
        // Header format:
        // // Golden file: Lowered TIR with -O2 optimization
        // // Source: wado-compiler/tests/fixtures/...
        // // Generated by: make update-golden-fixtures
        // (blank line)
        let expected_lines: Vec<&str> = golden_content
            .lines()
            .skip(4) // Skip 3 header comment lines + 1 blank line
            .collect();
        let expected = expected_lines.join("\n");

        // Compare
        if actual_module.trim() != expected.trim() {
            // Print a diff-like output for debugging
            eprintln!("=== EXPECTED (from golden file) ===");
            eprintln!("{}", expected);
            eprintln!("=== ACTUAL (from compiler) ===");
            eprintln!("{}", actual_module);
            eprintln!("=== END ===");
            panic!(
                "Golden file mismatch for {:?}\nRun `make update-golden-fixtures` if the change is intentional.",
                golden_path
            );
        }

        Ok(())
    })
}

datatest_mini::harness! {
    // Run golden file tests for all .lowered.wado files in tests/fixtures.golden/
    { test = run_golden_test, root = "tests/fixtures.golden", pattern = r"\.lowered\.wado$" },
}
