//! Generator for golden WAT fixture files.
//!
//! Run with: `cargo test -p wado-compiler --test wat_golden_gen -- --ignored`
//! Or via: `make update-golden-wat-fixtures`

mod common;

use std::path::PathBuf;
use wado_compiler::{CompilerOptions, OptLevel};

/// WAT fixture definitions: (`source_file`, `target_world`)
const FIXTURES: &[(&str, Option<&str>)] = &[
    ("hello.wado", None),
    ("hello_test.wado", Some("test")),
];

fn wasm_to_wat(wasm: &[u8]) -> String {
    let mut config = wasmprinter::Config::new();
    config.fold_instructions(true);
    let mut wat = String::new();
    config
        .print(wasm, &mut wasmprinter::PrintFmtWrite(&mut wat))
        .unwrap_or_else(|e| panic!("Failed to print WAT: {e}"));
    wat
}

fn world_display_name(world: Option<&str>) -> &str {
    world.unwrap_or("wasi:cli/command")
}

fn world_suffix(world: Option<&str>) -> &str {
    match world {
        None => "command",
        Some("test") => "test",
        Some(w) => panic!("unsupported world for golden WAT: {w}"),
    }
}

fn compile_to_wat(source_filename: &str, world: Option<&str>) -> String {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let source_path =
        PathBuf::from(manifest_dir).join(format!("tests/fixtures/{source_filename}"));

    let source = std::fs::read_to_string(&source_path).unwrap_or_else(|e| {
        panic!(
            "Failed to read source file {}: {e}",
            source_path.display()
        )
    });

    let options = CompilerOptions {
        opt_level: OptLevel::O2,
        target_world: world.map(String::from),
        skip_validation: false,
    };

    let result = common::compile_source_with_compiler_options(&source_path, &source, options)
        .unwrap_or_else(|e| {
            panic!(
                "Compilation failed for {}: {e}",
                source_path.display()
            )
        });

    wasm_to_wat(&result.wasm)
}

#[test]
#[ignore = "run via `make update-golden-wat-fixtures`"]
fn generate_all() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let output_dir = PathBuf::from(manifest_dir).join("tests/fixtures.golden.wat");
    std::fs::create_dir_all(&output_dir).unwrap_or_else(|e| {
        panic!(
            "Failed to create output dir {}: {e}",
            output_dir.display()
        )
    });

    for &(source_filename, world) in FIXTURES {
        let wat = compile_to_wat(source_filename, world);

        let stem = source_filename
            .strip_suffix(".wado")
            .unwrap_or(source_filename);
        let suffix = world_suffix(world);
        let output_filename = format!("{stem}.{suffix}.wat");
        let output_path = output_dir.join(&output_filename);

        let header = format!(
            ";; Golden WAT: {} with -O2\n\
             ;; Source: wado-compiler/tests/fixtures/{}\n\
             ;; Generated by: make update-golden-wat-fixtures\n",
            world_display_name(world),
            source_filename,
        );
        let content = format!("{header}\n{wat}\n");
        std::fs::write(&output_path, content).unwrap_or_else(|e| {
            panic!(
                "Failed to write {}: {e}",
                output_path.display()
            )
        });

        eprintln!("Generated: {output_filename}");
    }
}
