//! Golden file tests for WAT output
//!
//! These tests verify that the WAT output from the compiler matches expected golden files.
//! Golden files are generated by `make update-golden-wat-fixtures` and stored in
//! `tests/fixtures.golden.wat/*.wat`.
//!
//! Each golden file has a header that specifies:
//! - The target world (e.g., "wasi:cli/command" or "test")
//! - The source fixture file path
//!
//! If a test fails, the codegen or optimizer may have changed.
//! Review the diff and if the change is intentional, run `make update-golden-wat-fixtures`
//! to regenerate the golden files.

mod common;

use std::path::{Path, PathBuf};
use wado_compiler::{CompilerOptions, OptLevel};

/// Number of header lines (3 comment lines + 1 blank separator)
const HEADER_LINES: usize = 4;

/// Convert Wasm binary to folded WAT text
fn wasm_to_wat(wasm: &[u8]) -> String {
    let mut config = wasmprinter::Config::new();
    config.fold_instructions(true);
    let mut wat = String::new();
    config
        .print(wasm, &mut wasmprinter::PrintFmtWrite(&mut wat))
        .unwrap_or_else(|e| panic!("Failed to print WAT: {e}"));
    wat
}

/// Compile a fixture and return WAT output
fn compile_to_wat(source_filename: &str, world: Option<&str>) -> String {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let source_path = PathBuf::from(manifest_dir).join(format!("tests/fixtures/{source_filename}"));

    let source = std::fs::read_to_string(&source_path)
        .unwrap_or_else(|e| panic!("Failed to read source file {}: {e}", source_path.display()));

    let options = CompilerOptions {
        opt_level: OptLevel::O2,
        target_world: world.map(String::from),
        skip_validation: false,
    };

    let result = common::compile_source_with_compiler_options(&source_path, &source, options)
        .unwrap_or_else(|e| panic!("Compilation failed for {}: {e}", source_path.display()));

    wasm_to_wat(&result.wasm)
}

/// Run a golden file test: compare current WAT output against the golden file
fn run_wat_golden_test(
    golden_path: &Path,
    golden_content: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    // Extract the target world from the header
    // Format: ";; Golden WAT: wasi:cli/command with -O2"
    let world_line = golden_content
        .lines()
        .next()
        .expect("Golden file must not be empty");
    let world_str = world_line
        .strip_prefix(";; Golden WAT: ")
        .expect("Golden file must start with ';; Golden WAT: '");
    let world_name = world_str
        .strip_suffix(" with -O2")
        .expect("Golden file header must end with ' with -O2'");
    let world = match world_name {
        "wasi:cli/command" => None,
        other => Some(other),
    };

    // Extract the source filename from the header
    // Format: ";; Source: wado-compiler/tests/fixtures/hello.wado"
    let source_line = golden_content
        .lines()
        .nth(1)
        .expect("Golden file must have at least 2 lines");
    let source_from_header = source_line
        .strip_prefix(";; Source: wado-compiler/tests/fixtures/")
        .expect("Golden file must have ';; Source: wado-compiler/tests/fixtures/' header");

    // Compile and get actual WAT
    let actual_wat = compile_to_wat(source_from_header, world);

    // Extract expected content (skip header lines)
    let expected_lines: Vec<&str> = golden_content.lines().skip(HEADER_LINES).collect();
    let expected = expected_lines.join("\n");

    // Compare
    if actual_wat.trim() != expected.trim() {
        eprintln!("=== EXPECTED (from golden file) ===");
        for (i, line) in expected.lines().take(50).enumerate() {
            eprintln!("{:>4} | {line}", i + 1);
        }
        if expected.lines().count() > 50 {
            eprintln!("     ... ({} more lines)", expected.lines().count() - 50);
        }
        eprintln!("=== ACTUAL (from compiler) ===");
        for (i, line) in actual_wat.lines().take(50).enumerate() {
            eprintln!("{:>4} | {line}", i + 1);
        }
        if actual_wat.lines().count() > 50 {
            eprintln!("     ... ({} more lines)", actual_wat.lines().count() - 50);
        }
        eprintln!("=== END ===");
        return Err(format!(
            "Golden WAT mismatch for {}\n\
             Run `make update-golden-wat-fixtures` if the change is intentional.",
            golden_path.display()
        )
        .into());
    }

    Ok(())
}

datatest_mini::harness! {
    { test = run_wat_golden_test, root = "tests/fixtures.golden.wat", pattern = r"\.wat$" },
}
