//! Golden file tests for WIR output
//!
//! These tests verify that the WIR output matches expected golden files.
//! Golden files are generated by `make update-golden-wir-fixtures` and stored in
//! `tests/fixtures.golden.wir/*.wir.wado`.
//!
//! If a test fails, the codegen (tir_to_wir / wir_build / wir_emit) behavior may have changed.
//! Review the diff and if the change is intentional, run `make update-golden-wir-fixtures`
//! to regenerate the golden files.

mod common;

use std::path::{Path, PathBuf};
use wado_compiler::OptLevel;

/// Run a WIR golden file test
fn run_golden_test(
    golden_path: &Path,
    golden_content: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    common::runtime().block_on(async {
        // Extract the source filename from the header
        // Format: "// Source: wado-compiler/tests/fixtures/cli_print.wado"
        let source_line = golden_content
            .lines()
            .find(|line| line.starts_with("// Source:"))
            .expect("Golden file must have a '// Source:' header line");
        let source_from_header = source_line.strip_prefix("// Source:").unwrap().trim();

        // Strip "wado-compiler/" prefix if present (CLI runs from repo root)
        let source_relative = source_from_header
            .strip_prefix("wado-compiler/")
            .unwrap_or(source_from_header);

        // Construct full source path
        let manifest_dir = env!("CARGO_MANIFEST_DIR");
        let source_path = PathBuf::from(manifest_dir).join(source_relative);

        // Read the source file
        let source = std::fs::read_to_string(&source_path)
            .unwrap_or_else(|e| panic!("Failed to read source file {:?}: {}", source_path, e));

        // Extract target world from __DATA__ section
        let target_world = common::extract_data_section(&source).and_then(|data| {
            let json: serde_json::Value = serde_json::from_str(data.trim()).ok()?;
            json.get("world")?.as_str().map(String::from)
        });

        // Create compiler host
        let base_path = source_path.parent().unwrap().to_path_buf();
        let host = common::FilesystemHost::new(base_path);

        // Run dump with O2 optimization
        // Use the original path from header so the WIR output is reproducible
        let result = wado_compiler::dump_with_host_and_world(
            &source,
            &host,
            Some(source_from_header),
            OptLevel::O2,
            target_world.as_deref(),
        )
        .await
        .unwrap_or_else(|e| panic!("Compilation failed for {:?}: {}", source_path, e));

        let wir_module = result
            .wir_module
            .expect("WIR module should be available after dump");

        let actual = wado_compiler::wir_unparse::unparse_wir(&wir_module, Some(source_from_header));

        // Extract expected content (skip the 3 header lines and the blank line after)
        // Header format:
        // // Golden file: WIR with -O2 optimization
        // // Source: wado-compiler/tests/fixtures/...
        // // Generated by: make update-golden-wir-fixtures
        // (blank line)
        let expected_lines: Vec<&str> = golden_content
            .lines()
            .skip(4) // Skip 3 header comment lines + 1 blank line
            .collect();
        let expected = expected_lines.join("\n");

        // Compare
        if actual.trim() != expected.trim() {
            eprintln!("=== EXPECTED (from golden file) ===");
            eprintln!("{}", expected);
            eprintln!("=== ACTUAL (from compiler) ===");
            eprintln!("{}", actual);
            eprintln!("=== END ===");
            panic!(
                "Golden file mismatch for {:?}\nRun `make update-golden-wir-fixtures` if the change is intentional.",
                golden_path
            );
        }

        Ok(())
    })
}

datatest_mini::harness! {
    // Run golden file tests for all .wir.wado files in tests/fixtures.golden.wir/
    { test = run_golden_test, root = "tests/fixtures.golden.wir", pattern = r"\.wir\.wado$" },
}
