//! Generator for golden WIR fixture files.
//!
//! Run with: `cargo test -p wado-compiler --test wir_golden_gen -- generate_all --ignored --exact`
//! Or via: `make update-golden-wir-fixtures`

mod common;

use std::path::PathBuf;
use wado_compiler::OptLevel;

/// WIR fixture definitions: (`source_file`, `target_world`)
///
/// Curated set covering distinct codegen patterns:
/// - `cli_print`: basic imports/exports, println call
/// - `array_bounds_check`: GC array operations (array.new, array.set, array.get)
/// - `closure_fn_param_capture`: funcref table, closure struct, indirect calls
/// - `generic_struct_nested`: monomorphized struct types in codegen
/// - `trait_default_basic`: static dispatch, method table
/// - `ref_struct_basic`: Box<T> types, ref field access
/// - `treemap_btree`: recursive types, rec groups
/// - `newtype_basic`: newtype representation (zero-cost)
/// - `match_variant_basic`: variant type layout, discriminant
/// - `enum-match-basic`: enum i32 discriminant representation, match on enum
/// - `flags_basic`: flags bitmask (u32 newtype), bitwise operations
/// - `http-200`: wasi:http/service world, CM adapter for HTTP handler
const FIXTURES: &[(&str, Option<&str>)] = &[
    ("cli_print.wado", None),
    ("array_bounds_check.wado", None),
    ("closure_fn_param_capture.wado", None),
    ("generic_struct_nested.wado", None),
    ("trait_default_basic.wado", None),
    ("ref_struct_basic.wado", None),
    ("treemap_btree.wado", None),
    ("newtype_basic.wado", None),
    ("match_variant_basic.wado", None),
    ("enum-match-basic.wado", None),
    ("flags_basic.wado", None),
    ("http-200.wado", Some("wasi:http/service")),
];

fn compile_to_wir(source_filename: &str, world: Option<&str>) -> String {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let source_path = PathBuf::from(manifest_dir).join(format!("tests/fixtures/{source_filename}"));

    let source = std::fs::read_to_string(&source_path)
        .unwrap_or_else(|e| panic!("Failed to read source file {}: {e}", source_path.display()));

    let base_path = source_path.parent().unwrap().to_path_buf();
    let host = common::FilesystemHost::new(base_path);

    // Use a stable relative filename so the WIR output is reproducible across environments
    let display_filename = format!("wado-compiler/tests/fixtures/{source_filename}");

    let result = common::runtime()
        .block_on(wado_compiler::dump_with_host_and_world(
            &source,
            &host,
            Some(&display_filename),
            OptLevel::O2,
            world,
            None,
            None,
        ))
        .unwrap_or_else(|e| panic!("Compilation failed for {}: {e:?}", source_path.display()));

    let wir_module = result
        .wir_module
        .expect("WIR module should be available after dump");

    wado_compiler::wir_unparse::unparse_wir(&wir_module, Some(&display_filename))
}

#[test]
#[ignore = "run via `make update-golden-wir-fixtures`"]
fn generate_all() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let output_dir = PathBuf::from(manifest_dir).join("tests/fixtures.golden.wir");
    std::fs::create_dir_all(&output_dir)
        .unwrap_or_else(|e| panic!("Failed to create output dir {}: {e}", output_dir.display()));

    for &(source_filename, world) in FIXTURES {
        let wir = compile_to_wir(source_filename, world);

        let stem = source_filename
            .strip_suffix(".wado")
            .unwrap_or(source_filename);
        let output_filename = format!("{stem}.wir.wado");
        let output_path = output_dir.join(&output_filename);

        let header = format!(
            "// Golden file: WIR with -O2 optimization\n\
             // Source: wado-compiler/tests/fixtures/{source_filename}\n\
             // Generated by: make update-golden-wir-fixtures\n"
        );
        let content = format!("{header}\n{wir}\n");
        std::fs::write(&output_path, content)
            .unwrap_or_else(|e| panic!("Failed to write {}: {e}", output_path.display()));

        eprintln!("Generated: {output_filename}");
    }
}
