//! The JavaScript glue serving a `WebIDL` module's imports from the browser's own
//! objects, generated from the same IR as the Wado module.

use std::cmp::Reverse;
use std::fmt::Write;

use heck::ToLowerCamelCase;
use wado_compiler::ast::HandleClasses;
use wado_compiler::name::callback_export_name;

use crate::ir::{WadoFunction, WadoType};
use crate::webidl::{JsMember, WebIdlOutput};

/// Handles are interned, so `==` on two of them is identity. The `$` prefix keeps
/// the runtime's names apart from every `WebIDL` argument name.
const RUNTIME: &str = r#"
const $objects = [];
const $handles = new Map();

function $handle(object) {
  let handle = $handles.get(object);
  if (handle === undefined) {
    const entry = $CLASSES.find(
      ([name]) => globalThis[name] !== undefined && object instanceof globalThis[name],
    );
    if (entry === undefined) {
      throw new TypeError(`${object} is an instance of no interface this package declares`);
    }
    handle = entry[1] * $STRIDE + $objects.push(object) - 1;
    $handles.set(object, handle);
  }
  return handle;
}

const $object = (handle) => $objects[handle % $STRIDE];
const $some = (f) => (value) => (value === undefined ? undefined : f(value));
const $nullable = (f) => (value) => (value === null ? undefined : f(value));
const $someObject = $some($object);
const $nullableHandle = $nullable($handle);
const $someNumber = $some(Number);
const $nullableBigInt = $nullable(BigInt);
const $list = (f) => (values) => Array.from(values, (value) => f(value));

// The component's `wado:callback/callback` export, which calls a closure back.
// The component hands it over once instantiated.
let $callbackExport;

export function $connect(callback) {
  $callbackExport = callback;
}

// One function per closure key, so `removeEventListener` is handed the very
// function `addEventListener` was.
const $callbacks = new Map();

function $callback(key, call) {
  let f = $callbacks.get(key);
  if (f === undefined) {
    f = (...args) => call(key, ...args);
    $callbacks.set(key, f);
  }
  return f;
}
"#;

/// Names JavaScript does not take as a parameter in a module, which is strict code.
const RESERVED: &[&str] = &[
    "arguments",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// The glue module for `output`, naming `source` in its header.
#[must_use]
pub fn generate(output: &WebIdlOutput, source: &str) -> String {
    let module = &output.module;
    let mut out = format!(
        "// Generated by wado-from-idl from {source}. Do not edit.\n\
         // The `{}` module's imports, answered by the browser's own objects.\n\n",
        module.package_name
    );
    writeln!(out, "const $STRIDE = {};", HandleClasses::STRIDE).unwrap();
    let mut classes: Vec<(&str, u16)> = module
        .resources
        .iter()
        .map(|r| {
            let classes = r
                .classes
                .expect("the WebIDL frontend numbers every resource");
            (output.interfaces[&r.name].as_str(), classes.lo)
        })
        .collect();
    classes.sort_by_key(|&(_, lo)| Reverse(lo));
    out.push_str(
        "// Deepest first: a class follows its ancestors in pre-order.\nconst $CLASSES = [\n",
    );
    for (name, class) in classes {
        writeln!(out, "  [{name:?}, {class}],").unwrap();
    }
    out.push_str("];\n");
    out.push_str(RUNTIME);

    let interfaces = module
        .resources
        .iter()
        .map(|r| (&r.cm_attr, &r.methods))
        .chain(
            module
                .interfaces
                .iter()
                .map(|i| (&i.cm_interface, &i.functions)),
        );
    for (path, functions) in interfaces {
        let (_, name) = path
            .split_once('/')
            .expect("a `<package>/<interface>` path");
        writeln!(out, "\nexport const {} = {{", name.to_lower_camel_case()).unwrap();
        for function in functions {
            write_function(&mut out, function, &output.js[&function.cm_attr]);
        }
        out.push_str("};\n");
    }
    out
}

fn write_function(out: &mut String, function: &WadoFunction, member: &JsMember) {
    let (_, name) = function
        .cm_attr
        .split_once('#')
        .expect("a `<interface>#<member>` path");
    let params: Vec<String> = function
        .params
        .iter()
        .map(|p| {
            let name = p.wit_name.to_lower_camel_case();
            if RESERVED.contains(&name.as_str()) {
                format!("{name}_")
            } else {
                name
            }
        })
        .collect();
    let args: Vec<String> = function
        .params
        .iter()
        .zip(&params)
        .map(|(p, name)| from_guest(&p.ty, name))
        .collect();
    let receiver = || args.first().expect("a member of the receiver");
    let call_args = |skip: usize, spread: bool| {
        let mut call = args[skip..].to_vec();
        if spread {
            let last = call
                .last_mut()
                .expect("a variadic operation takes an argument");
            *last = format!("...{last}");
        }
        call.join(", ")
    };
    let value = match member {
        JsMember::Get(attribute) => format!("{}.{attribute}", receiver()),
        JsMember::Set(attribute) => format!("{}.{attribute} = {}", receiver(), args[1]),
        JsMember::Call { name, spread } => {
            format!("{}.{name}({})", receiver(), call_args(1, *spread))
        }
        JsMember::Static {
            interface,
            name,
            spread,
        } => format!("globalThis.{interface}.{name}({})", call_args(0, *spread)),
        JsMember::New { interface, spread } => {
            format!("new globalThis.{interface}({})", call_args(0, *spread))
        }
        JsMember::Global => "globalThis".to_string(),
        JsMember::GlobalGet(attribute) => format!("globalThis.{attribute}"),
    };
    let body = match &function.return_type {
        Some(ty) => format!("return {};", to_guest(ty, &value)),
        None => format!("{value};"),
    };
    writeln!(
        out,
        "  {}({}) {{\n    {body}\n  }},",
        name.to_lower_camel_case(),
        params.join(", ")
    )
    .unwrap();
}

/// `value`, as jco lifts it from the guest, in the form the DOM takes.
fn from_guest(ty: &WadoType, value: &str) -> String {
    if let WadoType::Callback { params, .. } = ty {
        return callback(params, value);
    }
    apply(conversion(ty, Direction::ToDom), value)
}

/// The function calling back the closure `key` names, which takes `params`.
fn callback(params: &[WadoType], key: &str) -> String {
    let export = callback_export_name(params.iter().map(argument_word)).to_lower_camel_case();
    let args: Vec<String> = (0..params.len()).map(|i| format!(", a{i}")).collect();
    let lifted: Vec<String> = params
        .iter()
        .enumerate()
        .map(|(i, ty)| format!(", {}", to_guest(ty, &format!("a{i}"))))
        .collect();
    format!(
        "$callback({key}, (key{}) => $callbackExport.{export}(key{}))",
        args.concat(),
        lifted.concat()
    )
}

fn argument_word(ty: &WadoType) -> &'static str {
    ty.callback_argument_word()
        .unwrap_or_else(|| unreachable!("the WebIDL frontend admits no {ty:?} callback argument"))
}

/// `value`, as the DOM returns it, in the form jco lowers to the guest.
fn to_guest(ty: &WadoType, value: &str) -> String {
    apply(conversion(ty, Direction::ToGuest), value)
}

fn apply(function: Option<String>, value: &str) -> String {
    function.map_or_else(|| value.to_string(), |f| format!("{f}({value})"))
}

#[derive(Clone, Copy)]
enum Direction {
    ToDom,
    ToGuest,
}

/// The function converting a `ty` in `direction`, where jco's own form differs
/// from the DOM's. A `None` crosses as `undefined`, which the DOM reads as `null`.
fn conversion(ty: &WadoType, direction: Direction) -> Option<String> {
    let function = match (ty, direction) {
        (WadoType::Named(_), Direction::ToDom) => "$object",
        (WadoType::Named(_), Direction::ToGuest) => "$handle",
        (WadoType::I64 | WadoType::U64, Direction::ToDom) => "Number",
        (WadoType::I64 | WadoType::U64, Direction::ToGuest) => "BigInt",
        (WadoType::Borrow(inner), _) => return conversion(inner, direction),
        (WadoType::Option(inner), _) => {
            let inner = conversion(inner, direction)?;
            return Some(match (inner.as_str(), direction) {
                ("$object", Direction::ToDom) => "$someObject".to_string(),
                ("Number", Direction::ToDom) => "$someNumber".to_string(),
                ("$handle", Direction::ToGuest) => "$nullableHandle".to_string(),
                ("BigInt", Direction::ToGuest) => "$nullableBigInt".to_string(),
                (_, Direction::ToDom) => format!("$some({inner})"),
                (_, Direction::ToGuest) => format!("$nullable({inner})"),
            });
        }
        (WadoType::List(element), _) => {
            return conversion(element, direction).map(|f| format!("$list({f})"));
        }
        (
            WadoType::Bool
            | WadoType::I8
            | WadoType::I16
            | WadoType::I32
            | WadoType::U8
            | WadoType::U16
            | WadoType::U32
            | WadoType::F32
            | WadoType::F64
            | WadoType::String,
            _,
        ) => return None,
        (
            WadoType::Char
            | WadoType::I128
            | WadoType::U128
            | WadoType::Result { .. }
            | WadoType::TreeMap(..)
            | WadoType::Tuple(_)
            | WadoType::Stream(_)
            | WadoType::Future(_)
            | WadoType::Callback { .. },
            _,
        ) => unreachable!("the WebIDL frontend lowers to no {ty:?} here"),
    };
    Some(function.to_string())
}
