//! The JavaScript glue serving a `web:<package>`'s imports from the browser's own
//! objects, generated from the same IR as the Wado module.

use std::cmp::Reverse;
use std::fmt::Write;

use heck::ToLowerCamelCase;
use wado_compiler::ast::HandleClasses;

use crate::ir::{WadoFunction, WadoType};
use crate::webidl::{JsMember, WebIdlOutput};

/// Handles are interned, so `==` on two of them is identity. The `$` prefix keeps
/// the runtime's names apart from every `WebIDL` argument name.
const RUNTIME: &str = r#"
const $objects = [];
const $handles = new Map();

function $handle(object) {
  let handle = $handles.get(object);
  if (handle === undefined) {
    const entry = $CLASSES.find(
      ([name]) => globalThis[name] !== undefined && object instanceof globalThis[name],
    );
    if (entry === undefined) {
      throw new TypeError(`${object} is an instance of no interface this package declares`);
    }
    handle = entry[1] * $STRIDE + $objects.push(object) - 1;
    $handles.set(object, handle);
  }
  return handle;
}

const $object = (handle) => $objects[handle % $STRIDE];
const $some = (f) => (value) => (value === undefined ? undefined : f(value));
const $nullable = (f) => (value) => (value === null ? undefined : f(value));
const $someObject = $some($object);
const $nullableHandle = $nullable($handle);
const $someNumber = $some(Number);
const $nullableBigInt = $nullable(BigInt);
"#;

/// Names JavaScript does not take as a parameter in a module, which is strict code.
const RESERVED: &[&str] = &[
    "arguments",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// The glue module for `output`, naming `source` in its header.
#[must_use]
pub fn generate(output: &WebIdlOutput, source: &str) -> String {
    let module = &output.module;
    let mut out = format!(
        "// Generated by wado-from-idl from {source}. Do not edit.\n\
         // The `web:{}` imports, answered by the browser's own objects.\n\n",
        module.package_name
    );
    writeln!(out, "const $STRIDE = {};", HandleClasses::STRIDE).unwrap();
    let mut classes: Vec<(&str, u16)> = module
        .resources
        .iter()
        .map(|r| {
            let classes = r
                .classes
                .expect("the WebIDL frontend numbers every resource");
            (output.interfaces[&r.name].as_str(), classes.lo)
        })
        .collect();
    classes.sort_by_key(|&(_, lo)| Reverse(lo));
    out.push_str(
        "// Deepest first: a class follows its ancestors in pre-order.\nconst $CLASSES = [\n",
    );
    for (name, class) in classes {
        writeln!(out, "  [{name:?}, {class}],").unwrap();
    }
    out.push_str("];\n");
    out.push_str(RUNTIME);

    let interfaces = module
        .resources
        .iter()
        .map(|r| (&r.cm_attr, &r.methods))
        .chain(
            module
                .interfaces
                .iter()
                .map(|i| (&i.cm_interface, &i.functions)),
        );
    for (path, functions) in interfaces {
        let (_, name) = path
            .split_once('/')
            .expect("a `web:<package>/<interface>` path");
        writeln!(out, "\nexport const {} = {{", name.to_lower_camel_case()).unwrap();
        for function in functions {
            write_function(&mut out, function, &output.js[&function.cm_attr]);
        }
        out.push_str("};\n");
    }
    out
}

fn write_function(out: &mut String, function: &WadoFunction, member: &JsMember) {
    let (_, name) = function
        .cm_attr
        .split_once('#')
        .expect("a `<interface>#<member>` path");
    let params: Vec<String> = function
        .params
        .iter()
        .map(|p| {
            let name = p.wit_name.to_lower_camel_case();
            if RESERVED.contains(&name.as_str()) {
                format!("{name}_")
            } else {
                name
            }
        })
        .collect();
    let args: Vec<String> = function
        .params
        .iter()
        .zip(&params)
        .map(|(p, name)| from_guest(&p.ty, name))
        .collect();
    let receiver = || args.first().expect("a member of the receiver");
    let call_args = |skip: usize| args[skip..].join(", ");
    let value = match member {
        JsMember::Get(attribute) => format!("{}.{attribute}", receiver()),
        JsMember::Set(attribute) => format!("{}.{attribute} = {}", receiver(), args[1]),
        JsMember::Call(operation) => format!("{}.{operation}({})", receiver(), call_args(1)),
        JsMember::Static { interface, name } => {
            format!("globalThis.{interface}.{name}({})", call_args(0))
        }
        JsMember::New { interface } => format!("new globalThis.{interface}({})", call_args(0)),
        JsMember::Global => "globalThis".to_string(),
        JsMember::GlobalGet(attribute) => format!("globalThis.{attribute}"),
    };
    let body = match &function.return_type {
        Some(ty) => format!("return {};", to_guest(ty, &value)),
        None => format!("{value};"),
    };
    writeln!(
        out,
        "  {}({}) {{\n    {body}\n  }},",
        name.to_lower_camel_case(),
        params.join(", ")
    )
    .unwrap();
}

/// `value`, as jco lifts it from the guest, in the form the DOM takes.
fn from_guest(ty: &WadoType, value: &str) -> String {
    apply(conversion(ty).map(|(to_dom, _)| to_dom), value)
}

/// `value`, as the DOM returns it, in the form jco lowers to the guest.
fn to_guest(ty: &WadoType, value: &str) -> String {
    apply(conversion(ty).map(|(_, to_guest)| to_guest), value)
}

fn apply(function: Option<&str>, value: &str) -> String {
    function.map_or_else(|| value.to_string(), |f| format!("{f}({value})"))
}

/// The functions converting a `ty` to the DOM and back, where jco's own form
/// differs. A `None` crosses as `undefined`, which the DOM reads as `null`.
fn conversion(ty: &WadoType) -> Option<(&'static str, &'static str)> {
    match ty {
        WadoType::Option(inner) => Conversion::of(inner).map(|c| c.functions(true)),
        ty => Conversion::of(ty).map(|c| c.functions(false)),
    }
}

#[derive(Clone, Copy)]
enum Conversion {
    Handle,
    BigInt,
}

impl Conversion {
    fn of(ty: &WadoType) -> Option<Self> {
        match ty {
            WadoType::Named(_) => Some(Self::Handle),
            WadoType::Borrow(inner) => Self::of(inner),
            WadoType::I64 | WadoType::U64 => Some(Self::BigInt),
            WadoType::Bool
            | WadoType::I8
            | WadoType::I16
            | WadoType::I32
            | WadoType::U8
            | WadoType::U16
            | WadoType::U32
            | WadoType::F32
            | WadoType::F64
            | WadoType::String => None,
            WadoType::Option(_)
            | WadoType::Char
            | WadoType::I128
            | WadoType::U128
            | WadoType::Result { .. }
            | WadoType::List(_)
            | WadoType::TreeMap(..)
            | WadoType::Tuple(_)
            | WadoType::Stream(_)
            | WadoType::Future(_) => unreachable!("the WebIDL frontend lowers to no {ty:?} here"),
        }
    }

    const fn functions(self, optional: bool) -> (&'static str, &'static str) {
        match (self, optional) {
            (Self::Handle, false) => ("$object", "$handle"),
            (Self::Handle, true) => ("$someObject", "$nullableHandle"),
            (Self::BigInt, false) => ("Number", "BigInt"),
            (Self::BigInt, true) => ("$someNumber", "$nullableBigInt"),
        }
    }
}
