//! Peephole optimization pass for WIR.
//!
//! Per-function pass that applies local rewrites:
//! - Constant folding on integer comparisons
//! - Dead `If` elimination (constant condition)
//! - Redundant `ValueCopy` elision
//! - Copy-used-only-for-field-reads elision
//! - Multi-value struct elision (`MultiValueStructNew` + `StructGet` → `MultiValueLocalBind`)

use crate::wir::{WirInstr, WirPackage, WirType, WirTypeDef};
use crate::wir_visitor::WirMutVisitor;
use indexmap::IndexMap;

/// Propagate trivial copies (`alias = source`) by replacing all uses of `alias`
/// with `source`, then removing the dead copy. This is a pre-SROA pass that
/// simplifies pattern matching codegen so variant SROA can see direct
/// RefTest/RefCast patterns on the original local.
pub(super) fn propagate_trivial_copies(module: &mut WirPackage) {
    for func in &mut module.functions {
        if let Some(body) = &mut func.body {
            propagate_copies_in_body(body);
        }
    }
}

fn propagate_copies_in_body(instrs: &mut [WirInstr]) {
    // Recurse into nested blocks first (bottom-up)
    struct RecurseIntoBlocks;
    impl WirMutVisitor for RecurseIntoBlocks {
        fn visit_body(&mut self, body: &mut Vec<WirInstr>) {
            propagate_copies_in_body(body);
        }
        // Only recurse into bodies (Block/Loop/If/Seq), not expression children.
        fn visit_instr(&mut self, instr: &mut WirInstr) {
            match instr {
                WirInstr::Block { body, .. }
                | WirInstr::Loop { body, .. }
                | WirInstr::Seq(body) => self.visit_body(body),
                WirInstr::If {
                    then_body,
                    else_body,
                    ..
                } => {
                    self.visit_body(then_body);
                    if let Some(eb) = else_body {
                        self.visit_body(eb);
                    }
                }
                _ => {}
            }
        }
    }
    for instr in instrs.iter_mut() {
        RecurseIntoBlocks.visit_instr(instr);
    }

    // Collect trivial copies: `LocalSet { alias, LocalGet { source } }`
    // Only propagate pattern-matching temporaries that are always safe to inline:
    // - __match_scrut_N: match scrutinee copies
    // - __pattern_temp_N: pattern matching temporaries
    // These are single-def, single-use copies generated by the pattern matching codegen.
    let mut copies: IndexMap<String, String> = IndexMap::default();

    for instr in instrs.iter() {
        if let WirInstr::LocalSet { name, value } = instr
            && let WirInstr::LocalGet { name: source, .. } = value.as_ref()
            && (name.starts_with("__match_scrut_") || name.starts_with("__pattern_temp_"))
        {
            copies.insert(name.clone(), source.clone());
        }
    }

    if copies.is_empty() {
        return;
    }

    // Replace uses of alias with source, and nop the copy instruction
    for instr in instrs.iter_mut() {
        if let WirInstr::LocalSet { name, value } = instr
            && let WirInstr::LocalGet { name: _, .. } = value.as_ref()
            && copies.contains_key(name.as_str())
        {
            *instr = WirInstr::Nop;
            continue;
        }
        rename_locals_in_instr(instr, &copies);
    }
}

fn rename_locals_in_instr(instr: &mut WirInstr, copies: &IndexMap<String, String>) {
    match instr {
        WirInstr::LocalGet { name, .. } => {
            if let Some(source) = copies.get(name.as_str()) {
                *name = source.clone();
            }
        }
        WirInstr::LocalSet { name, .. } if copies.contains_key(name.as_str()) => {
            // Should have been nop'd already, but be safe
        }
        _ => {}
    }
    instr.for_each_boxed_child_mut(&mut |child| rename_locals_in_instr(child, copies));
}

/// Recursively optimize a list of instructions.
///
/// First descends into nested instruction bodies (Block, Loop, If, Seq),
/// then applies flat-level optimizations on the current list.
pub(super) fn run_peephole(instrs: &mut Vec<WirInstr>, types: &[WirTypeDef]) {
    for instr in instrs.iter_mut() {
        optimize_nested(instr, types);
    }
    fold_constant_comparisons(instrs);
    // Re-run dead branch elimination after constant folding may have turned
    // If conditions into I32Const(0)/I32Const(1).
    for instr in instrs.iter_mut() {
        eliminate_const_if(instr);
    }
    fold_eqz_patterns(instrs);
    fold_branchless_increment(instrs);
    elide_redundant_value_copies(instrs);
    elide_copy_used_only_for_field_reads(instrs);
    // Cross-scope copy elision: traces LocalGet through parent scope definitions.
    // Runs after the recursive peephole so nested blocks are already optimized.
    elide_value_copies_cross_scope(instrs, &IndexMap::default());
    elide_multi_value_structs(instrs, types);
    relax_gc_operand_nullability(instrs);
}

/// Recurse into nested instruction bodies and eliminate dead branches.
fn optimize_nested(instr: &mut WirInstr, types: &[WirTypeDef]) {
    match instr {
        WirInstr::Block { body, .. } | WirInstr::Loop { body, .. } => {
            run_peephole(body, types);
        }
        WirInstr::If {
            then_body,
            else_body,
            ..
        } => {
            run_peephole(then_body, types);
            if let Some(eb) = else_body {
                run_peephole(eb, types);
            }
            eliminate_const_if(instr);
        }
        WirInstr::Seq(body) => {
            run_peephole(body, types);
        }
        WirInstr::LocalSet { value, .. } | WirInstr::LocalTee { value, .. } => {
            optimize_nested(value, types);
        }
        WirInstr::ValueCopy { expr, .. } => {
            optimize_nested(expr, types);
        }
        WirInstr::Call { args, .. } => {
            for arg in args {
                optimize_nested(arg, types);
            }
        }
        WirInstr::CallIndirect { index, args, .. } => {
            optimize_nested(index, types);
            for arg in args {
                optimize_nested(arg, types);
            }
        }
        WirInstr::StructNew { fields, .. } => {
            for field in fields {
                optimize_nested(field, types);
            }
        }
        WirInstr::Drop(inner)
        | WirInstr::RefAsNonNull(inner)
        | WirInstr::RefCast { expr: inner, .. }
        | WirInstr::RefTest { expr: inner, .. }
        | WirInstr::StructGet { expr: inner, .. } => {
            optimize_nested(inner, types);
        }
        WirInstr::StructSet { expr, value, .. } => {
            optimize_nested(expr, types);
            optimize_nested(value, types);
        }
        WirInstr::Return { value: Some(v) } => {
            optimize_nested(v, types);
        }
        _ => {}
    }
}

/// Try to evaluate a WIR condition to a boolean constant.
fn try_fold_wir_to_bool(instr: &WirInstr) -> Option<bool> {
    match instr {
        WirInstr::I32Const(v) => Some(*v != 0),
        _ => None,
    }
}

/// Recursively replace `If` with a constant condition by the surviving branch.
fn eliminate_const_if(instr: &mut WirInstr) {
    struct ElimConstIf;
    impl WirMutVisitor for ElimConstIf {
        fn visit_instr(&mut self, instr: &mut WirInstr) {
            self.walk_instr(instr);
            if let WirInstr::If {
                condition,
                then_body,
                else_body,
                result,
            } = instr
                && let Some(const_val) = try_fold_wir_to_bool(condition)
            {
                if const_val {
                    let then_instrs = std::mem::take(then_body);
                    *instr = WirInstr::Block {
                        label: None,
                        result: result.clone(),
                        body: then_instrs,
                    };
                } else if let Some(eb) = else_body {
                    let else_instrs = std::mem::take(eb);
                    *instr = WirInstr::Block {
                        label: None,
                        result: result.clone(),
                        body: else_instrs,
                    };
                } else {
                    *instr = WirInstr::Block {
                        label: None,
                        result: None,
                        body: vec![WirInstr::Nop],
                    };
                }
            }
        }
    }
    ElimConstIf.visit_instr(instr);
}

/// Recursively fold constant integer comparisons to `I32Const`.
fn fold_constant_comparisons(instrs: &mut [WirInstr]) {
    for instr in instrs.iter_mut() {
        fold_constant_comparisons_in_instr(instr);
    }
}

fn fold_constant_comparisons_in_instr(instr: &mut WirInstr) {
    struct FoldConstComparisons;
    impl WirMutVisitor for FoldConstComparisons {
        fn visit_instr(&mut self, instr: &mut WirInstr) {
            self.walk_instr(instr);
            try_fold_comparison(instr);
        }
    }
    FoldConstComparisons.visit_instr(instr);
}

fn try_fold_comparison(instr: &mut WirInstr) {
    // Try to fold this instruction
    let result = match instr {
        WirInstr::I32GeS(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => Some(i32::from(*lv >= *rv)),
            _ => None,
        },
        WirInstr::I32GeU(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => {
                Some(i32::from(lv.cast_unsigned() >= rv.cast_unsigned()))
            }
            _ => None,
        },
        WirInstr::I32LtS(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => Some(i32::from(*lv < *rv)),
            _ => None,
        },
        WirInstr::I32GtS(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => Some(i32::from(*lv > *rv)),
            _ => None,
        },
        WirInstr::I32Eq(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => Some(i32::from(*lv == *rv)),
            _ => None,
        },
        WirInstr::I32Ne(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => Some(i32::from(*lv != *rv)),
            _ => None,
        },
        WirInstr::I32LeS(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => Some(i32::from(*lv <= *rv)),
            _ => None,
        },
        WirInstr::I32LtU(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => {
                Some(i32::from(lv.cast_unsigned() < rv.cast_unsigned()))
            }
            _ => None,
        },
        WirInstr::I32GtU(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => {
                Some(i32::from(lv.cast_unsigned() > rv.cast_unsigned()))
            }
            _ => None,
        },
        WirInstr::I32LeU(l, r) => match (l.as_ref(), r.as_ref()) {
            (WirInstr::I32Const(lv), WirInstr::I32Const(rv)) => {
                Some(i32::from(lv.cast_unsigned() <= rv.cast_unsigned()))
            }
            _ => None,
        },
        _ => None,
    };

    if let Some(val) = result {
        *instr = WirInstr::I32Const(val);
    }
}

/// Replace `I32Eq(expr, I32Const(0))` with `I32Eqz(expr)` (and i64 variant).
/// Also replace `I32Ne(expr, I32Const(0))` with `I32Eqz(I32Eqz(expr))` — this
/// is not done because it's not a win. Instead, only `== 0` patterns are folded.
fn fold_eqz_patterns(instrs: &mut [WirInstr]) {
    for instr in instrs.iter_mut() {
        fold_eqz_in_instr(instr);
    }
}

fn fold_eqz_in_instr(instr: &mut WirInstr) {
    struct FoldEqz;
    impl WirMutVisitor for FoldEqz {
        fn visit_instr(&mut self, instr: &mut WirInstr) {
            self.walk_instr(instr);
            try_fold_eqz(instr);
            try_negate_eqz_comparison(instr);
        }
    }
    FoldEqz.visit_instr(instr);
}

fn try_fold_eqz(instr: &mut WirInstr) {
    // i32.eq(expr, 0) → i32.eqz(expr)
    // i32.eq(0, expr) → i32.eqz(expr)
    match instr {
        WirInstr::I32Eq(l, r) => {
            if matches!(r.as_ref(), WirInstr::I32Const(0)) {
                let operand = std::mem::replace(l, Box::new(WirInstr::Nop));
                *instr = WirInstr::I32Eqz(operand);
            } else if matches!(l.as_ref(), WirInstr::I32Const(0)) {
                let operand = std::mem::replace(r, Box::new(WirInstr::Nop));
                *instr = WirInstr::I32Eqz(operand);
            }
        }
        WirInstr::I64Eq(l, r) => {
            if matches!(r.as_ref(), WirInstr::I64Const(0)) {
                let operand = std::mem::replace(l, Box::new(WirInstr::Nop));
                *instr = WirInstr::I64Eqz(operand);
            } else if matches!(l.as_ref(), WirInstr::I64Const(0)) {
                let operand = std::mem::replace(r, Box::new(WirInstr::Nop));
                *instr = WirInstr::I64Eqz(operand);
            }
        }
        _ => {}
    }
}

/// Fold `I32Eqz(comparison)` into the negated comparison instruction.
///
/// e.g., `i32.eqz(i32.le_s(a, b))` → `i32.gt_s(a, b)`
///
/// This saves one Wasm instruction per negated comparison, which is significant
/// in tight loops (e.g., `while x <= limit` lowers to `if !(x <= limit) break`).
/// Only applies to integer comparisons — float comparisons are excluded due to NaN.
fn try_negate_eqz_comparison(instr: &mut WirInstr) {
    let WirInstr::I32Eqz(inner) = instr else {
        return;
    };
    // Determine which negated constructor to use based on the inner comparison.
    // Take a reference first to decide, then destructure to move operands.
    let ctor: fn(Box<WirInstr>, Box<WirInstr>) -> WirInstr = match inner.as_ref() {
        // i32 signed
        WirInstr::I32LeS(..) => WirInstr::I32GtS,
        WirInstr::I32LtS(..) => WirInstr::I32GeS,
        WirInstr::I32GeS(..) => WirInstr::I32LtS,
        WirInstr::I32GtS(..) => WirInstr::I32LeS,
        // i32 unsigned
        WirInstr::I32LeU(..) => WirInstr::I32GtU,
        WirInstr::I32LtU(..) => WirInstr::I32GeU,
        WirInstr::I32GeU(..) => WirInstr::I32LtU,
        WirInstr::I32GtU(..) => WirInstr::I32LeU,
        // i32 eq/ne
        WirInstr::I32Eq(..) => WirInstr::I32Ne,
        WirInstr::I32Ne(..) => WirInstr::I32Eq,
        // i64 signed
        WirInstr::I64LeS(..) => WirInstr::I64GtS,
        WirInstr::I64LtS(..) => WirInstr::I64GeS,
        WirInstr::I64GeS(..) => WirInstr::I64LtS,
        WirInstr::I64GtS(..) => WirInstr::I64LeS,
        // i64 unsigned
        WirInstr::I64LeU(..) => WirInstr::I64GtU,
        WirInstr::I64LtU(..) => WirInstr::I64GeU,
        WirInstr::I64GeU(..) => WirInstr::I64LtU,
        WirInstr::I64GtU(..) => WirInstr::I64LeU,
        // i64 eq/ne
        WirInstr::I64Eq(..) => WirInstr::I64Ne,
        WirInstr::I64Ne(..) => WirInstr::I64Eq,
        _ => return,
    };
    // Extract the two operands from the inner comparison.
    let (l, r) = match inner.as_mut() {
        WirInstr::I32LeS(l, r)
        | WirInstr::I32LtS(l, r)
        | WirInstr::I32GeS(l, r)
        | WirInstr::I32GtS(l, r)
        | WirInstr::I32LeU(l, r)
        | WirInstr::I32LtU(l, r)
        | WirInstr::I32GeU(l, r)
        | WirInstr::I32GtU(l, r)
        | WirInstr::I32Eq(l, r)
        | WirInstr::I32Ne(l, r)
        | WirInstr::I64LeS(l, r)
        | WirInstr::I64LtS(l, r)
        | WirInstr::I64GeS(l, r)
        | WirInstr::I64GtS(l, r)
        | WirInstr::I64LeU(l, r)
        | WirInstr::I64LtU(l, r)
        | WirInstr::I64GeU(l, r)
        | WirInstr::I64GtU(l, r)
        | WirInstr::I64Eq(l, r)
        | WirInstr::I64Ne(l, r) => (
            std::mem::replace(l, Box::new(WirInstr::Nop)),
            std::mem::replace(r, Box::new(WirInstr::Nop)),
        ),
        _ => return,
    };
    *instr = ctor(l, r);
}

/// Fold `if bool { x += 1 }` → `x += bool` (branchless increment).
///
/// Eliminates a conditional branch in the common counting-loop pattern where a
/// boolean value gates an increment-by-one. Since the condition is guaranteed to
/// be 0 or 1, it can be added directly.
fn fold_branchless_increment(instrs: &mut [WirInstr]) {
    for instr in instrs.iter_mut() {
        fold_branchless_increment_in(instr);
    }
}

fn fold_branchless_increment_in(instr: &mut WirInstr) {
    // Recurse into nested blocks first.
    match instr {
        WirInstr::Block { body, .. } | WirInstr::Loop { body, .. } | WirInstr::Seq(body) => {
            fold_branchless_increment(body);
        }
        WirInstr::If {
            then_body,
            else_body,
            ..
        } => {
            fold_branchless_increment(then_body);
            if let Some(eb) = else_body {
                fold_branchless_increment(eb);
            }
        }
        _ => {}
    }
    // Match: If { cond, then: [LocalSet(x, I32Add(LocalGet(x), I32Const(1)))], else: None }
    let WirInstr::If {
        condition,
        then_body,
        else_body: None,
        result: None,
    } = instr
    else {
        return;
    };
    if then_body.len() != 1 {
        return;
    }
    let WirInstr::LocalSet { name, value } = &then_body[0] else {
        return;
    };
    let WirInstr::I32Add(lhs, rhs) = value.as_ref() else {
        return;
    };
    let WirInstr::LocalGet { name: get_name, .. } = lhs.as_ref() else {
        return;
    };
    if get_name != name {
        return;
    }
    let WirInstr::I32Const(1) = rhs.as_ref() else {
        return;
    };
    if !is_boolean_valued(condition.as_ref()) {
        return;
    }
    // Transform: x = x + condition
    let cond = std::mem::replace(condition, Box::new(WirInstr::Nop));
    let get = Box::new(WirInstr::LocalGet {
        name: name.clone(),
        result_ty: WirType::I32,
    });
    *instr = WirInstr::LocalSet {
        name: name.clone(),
        value: Box::new(WirInstr::I32Add(get, cond)),
    };
}

/// Returns true if the instruction is guaranteed to produce 0 or 1.
fn is_boolean_valued(instr: &WirInstr) -> bool {
    matches!(
        instr,
        // Integer comparisons
        WirInstr::I32Eq(..)
            | WirInstr::I32Ne(..)
            | WirInstr::I32LtS(..)
            | WirInstr::I32LtU(..)
            | WirInstr::I32GtS(..)
            | WirInstr::I32GtU(..)
            | WirInstr::I32LeS(..)
            | WirInstr::I32LeU(..)
            | WirInstr::I32GeS(..)
            | WirInstr::I32GeU(..)
            | WirInstr::I64Eq(..)
            | WirInstr::I64Ne(..)
            | WirInstr::I64LtS(..)
            | WirInstr::I64LtU(..)
            | WirInstr::I64GtS(..)
            | WirInstr::I64GtU(..)
            | WirInstr::I64LeS(..)
            | WirInstr::I64LeU(..)
            | WirInstr::I64GeS(..)
            | WirInstr::I64GeU(..)
            // Float comparisons
            | WirInstr::F32Eq(..)
            | WirInstr::F32Ne(..)
            | WirInstr::F32Lt(..)
            | WirInstr::F32Gt(..)
            | WirInstr::F32Le(..)
            | WirInstr::F32Ge(..)
            | WirInstr::F64Eq(..)
            | WirInstr::F64Ne(..)
            | WirInstr::F64Lt(..)
            | WirInstr::F64Gt(..)
            | WirInstr::F64Le(..)
            | WirInstr::F64Ge(..)
            // Eqz / null checks
            | WirInstr::I32Eqz(..)
            | WirInstr::I64Eqz(..)
            | WirInstr::RefIsNull(..)
            | WirInstr::RefTest { .. }
            // Bool array element (packed i8 with values 0 or 1)
            | WirInstr::ArrayGet {
                result_ty: WirType::Bool,
                ..
            }
            | WirInstr::ArrayGetU {
                result_ty: WirType::Bool,
                ..
            }
    )
}

/// Remove unnecessary `ValueCopy` wrappers from `LocalSet` instructions.
///
/// A `ValueCopy` deep-copies a GC value to maintain Wado's value semantics.
/// This copy is unnecessary when the source expression provably produces a
/// **fresh** value — one with no pre-existing aliases. Fresh values include
/// GC constructors (`StructNew`, `ArrayNew*`), function call return values,
/// and block expressions whose result is itself fresh.
fn elide_redundant_value_copies(instrs: &mut [WirInstr]) {
    for instr in instrs.iter_mut() {
        let WirInstr::LocalSet { value, .. } = instr else {
            continue;
        };
        let is_fresh = if let WirInstr::ValueCopy { expr, .. } = value.as_ref() {
            is_fresh_wir_value(expr)
        } else {
            false
        };
        if is_fresh {
            let old = std::mem::replace(value.as_mut(), WirInstr::Nop);
            if let WirInstr::ValueCopy { expr, .. } = old {
                *value = expr;
            }
        }
    }
}

/// Cross-scope `value_copy` elision.
///
/// Traces `LocalGet` references through definitions in parent scopes to
/// detect fresh values. This handles the `Option::unwrap()` pattern where
/// a `StructNew` is in a parent block and the `value_copy` is in a nested `if`:
///
/// ```text
/// __local_88 = Data { x: 1, y: 2, ... };        // parent scope
/// if ref.is_null(__local_88) == 0 {
///     x = value_copy Data(ref.as_non_null(__local_88));  // nested scope — can elide!
/// };
/// ```
fn elide_value_copies_cross_scope(
    instrs: &mut [WirInstr],
    parent_defs: &IndexMap<String, FreshDef>,
) {
    let mut defs = parent_defs.clone();

    for i in 0..instrs.len() {
        // Track local definitions: record only single-definition fresh values.
        // Use is_fresh_via_defs to trace through LocalGet chains (e.g.,
        // `__local_70 = opt2` where `opt2` is already known to be fresh).
        match &instrs[i] {
            WirInstr::LocalSet { name, value } => {
                if is_fresh_via_defs(value, &defs) {
                    defs.insert(name.clone(), FreshDef::Fresh);
                } else {
                    defs.insert(name.clone(), FreshDef::NotFresh);
                }
            }
            // MultiValueLocalBind distributes a multi-value return into locals.
            // When the source instruction is fresh (e.g. a function call),
            // all bound locals are fresh.
            WirInstr::MultiValueLocalBind { instr, locals } => {
                let fresh = is_fresh_via_defs(instr, &defs);
                for local in locals.iter().flatten() {
                    defs.insert(
                        local.clone(),
                        if fresh {
                            FreshDef::Fresh
                        } else {
                            FreshDef::NotFresh
                        },
                    );
                }
            }
            _ => {}
        }

        // Recurse into all nested instruction bodies (including inside LocalSet values).
        // Pass remaining instructions so the safety check can verify the destination
        // local is never mutated after this point.
        let remaining_start = i + 1;
        let (left, right) = instrs.split_at_mut(remaining_start);
        elide_value_copies_in_instr(&mut left[i], right, &defs);
    }
}

/// Extract the source local name from the inner expression of a `ValueCopy`.
///
/// Traces through `RefAsNonNull`, `RefCast`, and `StructGet` wrappers to find
/// the innermost `LocalGet`. Returns `None` when the inner expression is not
/// rooted at a local variable (e.g. a literal or a call return value).
fn value_copy_source_local<'a>(expr: &'a WirInstr) -> Option<&'a str> {
    match expr {
        WirInstr::LocalGet { name, .. } => Some(name.as_str()),
        WirInstr::RefAsNonNull(inner)
        | WirInstr::RefCast { expr: inner, .. }
        | WirInstr::StructGet { expr: inner, .. } => value_copy_source_local(inner),
        _ => None,
    }
}

/// Recursively walk a single instruction, eliding `value_copies` and descending
/// into nested blocks/ifs/seqs.
fn elide_value_copies_in_instr(
    instr: &mut WirInstr,
    remaining: &[WirInstr],
    defs: &IndexMap<String, FreshDef>,
) {
    match instr {
        WirInstr::LocalSet { name, value } | WirInstr::LocalTee { name, value } => {
            // Check if the value is a value_copy that can be elided.
            if let WirInstr::ValueCopy { expr, .. } = value.as_ref()
                && is_fresh_via_defs(expr, defs)
            {
                // Safety check: only elide if:
                // 1. The destination local is never mutated in the remaining
                //    instructions (no StructSet, no mutable call args, etc.).
                // 2. The source local is not mutated after the copy point.
                //    Eliding the copy creates an alias; any subsequent mutation
                //    of the source would corrupt the destination's value.
                let dest_safe = remaining
                    .iter()
                    .all(|i| uses_of_var_are_reads_only(i, name));
                let source_safe = value_copy_source_local(expr).map_or(true, |src| {
                    remaining
                        .iter()
                        .all(|i| uses_of_var_are_reads_only(i, src))
                });
                if dest_safe && source_safe {
                    let old = std::mem::replace(value.as_mut(), WirInstr::Nop);
                    if let WirInstr::ValueCopy { expr, .. } = old {
                        *value = expr;
                    }
                    return;
                }
            }
            // Recurse into the value expression for nested blocks.
            elide_value_copies_in_instr_inner(value.as_mut(), defs);
        }
        WirInstr::Block { body, .. } | WirInstr::Loop { body, .. } => {
            elide_value_copies_cross_scope(body, defs);
        }
        WirInstr::If {
            then_body,
            else_body,
            ..
        } => {
            elide_value_copies_cross_scope(then_body, defs);
            if let Some(eb) = else_body {
                elide_value_copies_cross_scope(eb, defs);
            }
        }
        WirInstr::Seq(body) => {
            elide_value_copies_cross_scope(body, defs);
        }
        _ => {}
    }
}

/// Like `elide_value_copies_in_instr` but without the remaining-slice context
/// (for recursing into value expressions where we can't check use safety).
fn elide_value_copies_in_instr_inner(instr: &mut WirInstr, defs: &IndexMap<String, FreshDef>) {
    match instr {
        WirInstr::Block { body, .. } | WirInstr::Loop { body, .. } => {
            elide_value_copies_cross_scope(body, defs);
        }
        WirInstr::If {
            then_body,
            else_body,
            ..
        } => {
            elide_value_copies_cross_scope(then_body, defs);
            if let Some(eb) = else_body {
                elide_value_copies_cross_scope(eb, defs);
            }
        }
        WirInstr::Seq(body) => {
            elide_value_copies_cross_scope(body, defs);
        }
        _ => {}
    }
}

#[derive(Clone, PartialEq)]
enum FreshDef {
    Fresh,
    NotFresh,
}

/// Returns `true` if every use of `var_name` in `instr` is read-only:
/// field reads (`StructGet`), null/discriminant checks, break values, or
/// local copies. Mutation through the variable (`StructSet`, function calls
/// with the variable as argument, etc.) returns false.
fn uses_of_var_are_reads_only(instr: &WirInstr, var_name: &str) -> bool {
    match instr {
        // Field read: safe
        WirInstr::LocalSet { value, .. } | WirInstr::LocalTee { value, .. } => {
            match value.as_ref() {
                WirInstr::StructGet { expr, .. } if expr_roots_at_var(expr, var_name) => true,
                WirInstr::ValueCopy { expr, .. } => {
                    if let WirInstr::StructGet { expr: inner, .. } = expr.as_ref()
                        && expr_roots_at_var(inner, var_name)
                    {
                        return true;
                    }
                    !instr_contains_local_get(value, var_name)
                }
                // LocalGet(var) stored into another local: creates alias but OK if read-only
                WirInstr::LocalGet { name, .. } if name == var_name => true,
                // RefAsNonNull/RefCast/RefTest on var — type narrowing, safe
                WirInstr::RefAsNonNull(inner)
                | WirInstr::RefCast { expr: inner, .. }
                | WirInstr::RefTest { expr: inner, .. }
                    if matches!(inner.as_ref(), WirInstr::LocalGet { name, .. } if name == var_name) =>
                {
                    true
                }
                _ => !instr_contains_local_get(value, var_name),
            }
        }
        // Drop: safe
        WirInstr::Drop(inner) => !instr_contains_local_get(inner, var_name),
        // Recurse into blocks
        WirInstr::Block { body, .. } | WirInstr::Loop { body, .. } | WirInstr::Seq(body) => {
            body.iter().all(|i| uses_of_var_are_reads_only(i, var_name))
        }
        WirInstr::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            // Bodies must always be read-only. Condition expressions are
            // inherently read-only (they evaluate to a value for branching)
            // unless the variable is passed to a Call that could mutate it.
            then_body
                .iter()
                .all(|i| uses_of_var_are_reads_only(i, var_name))
                && else_body
                    .as_ref()
                    .is_none_or(|eb| eb.iter().all(|i| uses_of_var_are_reads_only(i, var_name)))
                && !condition_passes_var_to_call(condition, var_name)
        }
        // LocalGet: reading the variable is always safe.
        WirInstr::LocalGet { name, .. } if name == var_name => true,
        // Br carrying a value: check if the value mentions var
        WirInstr::Br { .. } => !instr_contains_local_get(instr, var_name),
        // Return: safe if var appears only in StructNew fields within the value
        WirInstr::Return { value: Some(v) } => {
            if value_uses_var_only_in_struct_new_fields(v, var_name) {
                return true;
            }
            !instr_contains_local_get(instr, var_name)
        }
        WirInstr::Return { value: None } => true,
        // StructSet on the variable — mutation!
        WirInstr::StructSet { expr, .. } => {
            !matches!(expr.as_ref(), WirInstr::LocalGet { name, .. } if name == var_name)
                && !instr_contains_local_get(instr, var_name)
        }
        // Any other instruction: var must not appear
        _ => !instr_contains_local_get(instr, var_name),
    }
}

/// Returns `true` if the condition expression passes `var_name` as an
/// argument to a `Call` or `CallRef`. Condition expressions are inherently
/// read-only (`StructGet`, `RefTest`, `RefIsNull`, comparisons, etc.) — the only
/// risk is when the variable reference is handed to a function that could
/// mutate the underlying object.
fn condition_passes_var_to_call(cond: &WirInstr, var_name: &str) -> bool {
    if let WirInstr::Call { args, .. } | WirInstr::CallRef { args, .. } = cond
        && args
            .iter()
            .any(|arg| instr_contains_local_get(arg, var_name))
    {
        return true;
    }
    let mut found = false;
    cond.for_each_child(&mut |child| {
        if !found {
            found = condition_passes_var_to_call(child, var_name);
        }
    });
    found
}

/// Check if a WIR expression is fresh by tracing `LocalGet` through definitions.
fn is_fresh_via_defs(instr: &WirInstr, defs: &IndexMap<String, FreshDef>) -> bool {
    match instr {
        WirInstr::LocalGet { name, .. } => defs.get(name.as_str()) == Some(&FreshDef::Fresh),
        WirInstr::RefAsNonNull(inner) => is_fresh_via_defs(inner, defs),
        WirInstr::StructGet { expr, .. } => is_fresh_via_defs(expr, defs),
        WirInstr::RefCast { expr, .. } => is_fresh_via_defs(expr, defs),
        _ => is_fresh_wir_value(instr),
    }
}

/// Elide `value_copy T(expr)` when the copy result is used exclusively for
/// struct field reads (`StructGet`).
///
/// This is safe because:
/// - Reading a primitive field from the original or a copy yields the same value.
/// - Reading a complex (GC) field is safe when the extracted value itself goes
///   through its own `value_copy` (which provides the necessary isolation).
/// - If `t` were used for any mutation (e.g. `StructSet`, `Call` taking `t` by
///   reference), the check would fail and the copy would be preserved.
///
/// The canonical case is struct destructuring in a for-of loop:
/// ```text
/// __pattern_temp_1 = value_copy Point(ref.as_non_null(__pattern_temp_0))
/// x = __pattern_temp_1.x    // StructGet → safe
/// y = __pattern_temp_1.y    // StructGet → safe
/// ```
fn elide_copy_used_only_for_field_reads(instrs: &mut [WirInstr]) {
    for i in 0..instrs.len() {
        match &instrs[i] {
            WirInstr::LocalSet { name, value }
                if matches!(value.as_ref(), WirInstr::ValueCopy { .. }) =>
            {
                let var_name = name.clone();
                let remaining = &instrs[i + 1..];
                // The destination must only be used for struct field reads.
                let all_reads_only = remaining
                    .iter()
                    .all(|instr| uses_of_var_are_field_reads_only(instr, &var_name));
                // The source must not be mutated after the copy; otherwise eliding
                // the copy creates an alias whose value would change under the caller.
                let source_safe = if let WirInstr::ValueCopy { expr, .. } = value.as_ref() {
                    value_copy_source_local(expr).map_or(true, |src| {
                        remaining
                            .iter()
                            .all(|instr| uses_of_var_are_reads_only(instr, src))
                    })
                } else {
                    true
                };
                if all_reads_only && source_safe {
                    if let WirInstr::LocalSet { value, .. } = &mut instrs[i] {
                        let old = std::mem::replace(value.as_mut(), WirInstr::Nop);
                        if let WirInstr::ValueCopy { expr, .. } = old {
                            *value.as_mut() = *expr;
                        }
                    }
                }
            }
            _ => {}
        }
        // Recurse into nested scopes to find value_copies inside blocks/ifs/loops.
        elide_copy_field_reads_recurse_into(&mut instrs[i]);
    }
}

/// Recurse into all nested instruction bodies to apply field-reads-only copy elision.
fn elide_copy_field_reads_recurse_into(instr: &mut WirInstr) {
    match instr {
        WirInstr::Block { body, .. } | WirInstr::Loop { body, .. } | WirInstr::Seq(body) => {
            elide_copy_used_only_for_field_reads(body);
        }
        WirInstr::If {
            then_body,
            else_body,
            ..
        } => {
            elide_copy_used_only_for_field_reads(then_body);
            if let Some(eb) = else_body {
                elide_copy_used_only_for_field_reads(eb);
            }
        }
        WirInstr::LocalSet { value, .. } | WirInstr::LocalTee { value, .. } => {
            elide_copy_field_reads_recurse_into(value);
        }
        WirInstr::ValueCopy { expr, .. } => {
            elide_copy_field_reads_recurse_into(expr);
        }
        _ => {}
    }
}

/// Returns `true` if every use of `var_name` in `instr` is a struct field read
/// stored directly into a local, or if `var_name` does not appear at all.
///
/// Safe patterns (where the field-read result is isolated into a local):
/// - `LocalSet { x, StructGet { expr: LocalGet(var) } }` — direct field read
/// - `LocalSet { x, StructGet { expr: StructGet { expr: LocalGet(var) } } }` — chained
/// - `LocalSet { x, StructGet { expr: RefCast { expr: LocalGet(var) } } }` — variant payload
/// - `LocalSet { x, ValueCopy { expr: StructGet { expr: ... LocalGet(var) } } }` — with copy
/// - `LocalSet { x, StructNew { fields: [..., LocalGet(var), ...] } }` — stored in new struct
/// - `RefTest(LocalGet(var))` embedded in a condition — discriminant check
///
/// We intentionally do NOT allow StructGet(var) embedded in arbitrary expressions
/// (e.g., `var.repr` as a function argument), because the extracted reference
/// could alias mutable internals of the struct.
///
/// Storing `var` as a field in a `StructNew` is safe because the new struct is a
/// fresh allocation that nobody else references yet. Any future extraction of the
/// field will go through its own `value_copy`, maintaining value semantics.
fn uses_of_var_are_field_reads_only(instr: &WirInstr, var_name: &str) -> bool {
    match instr {
        WirInstr::LocalSet { value, .. } | WirInstr::LocalTee { value, .. } => {
            match value.as_ref() {
                // `x = t.field` or `x = t.inner.field` — field read chain.
                WirInstr::StructGet { expr, .. } => {
                    if expr_roots_at_var(expr, var_name) {
                        return true;
                    }
                    !instr_contains_local_get(value, var_name)
                }
                // `x = value_copy T(t.field)` or chained — field read with copy.
                WirInstr::ValueCopy { expr, .. } => {
                    if let WirInstr::StructGet { expr: inner, .. } = expr.as_ref()
                        && expr_roots_at_var(inner, var_name)
                    {
                        return true;
                    }
                    !instr_contains_local_get(value, var_name)
                }
                // `x = struct.new T { ..., var, ... }` — var stored as field in fresh struct.
                WirInstr::StructNew { fields, .. }
                | WirInstr::ArrayNewFixed {
                    elements: fields, ..
                } => {
                    if var_used_only_as_direct_local_get_in_fields(fields, var_name) {
                        return true;
                    }
                    !instr_contains_local_get(value, var_name)
                }
                _ => !instr_contains_local_get(value, var_name),
            }
        }
        WirInstr::Block { body, .. } | WirInstr::Loop { body, .. } | WirInstr::Seq(body) => body
            .iter()
            .all(|i| uses_of_var_are_field_reads_only(i, var_name)),
        WirInstr::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            is_safe_condition_use(condition, var_name)
                && then_body
                    .iter()
                    .all(|i| uses_of_var_are_field_reads_only(i, var_name))
                && else_body.as_ref().is_none_or(|eb| {
                    eb.iter()
                        .all(|i| uses_of_var_are_field_reads_only(i, var_name))
                })
        }
        // Return: safe if var appears only in StructNew fields within the value
        WirInstr::Return { value: Some(v) } => {
            if value_uses_var_only_in_struct_new_fields(v, var_name) {
                return true;
            }
            !instr_contains_local_get(instr, var_name)
        }
        WirInstr::Return { value: None } => true,
        _ => !instr_contains_local_get(instr, var_name),
    }
}

/// Check if a condition expression uses `var_name` only in safe read-only ways.
///
/// Allows `RefTest(LocalGet(var))` and comparisons involving `RefTest`/`RefIsNull`
/// of the variable, which are purely discriminant checks.
fn is_safe_condition_use(instr: &WirInstr, var_name: &str) -> bool {
    match instr {
        // ref.test T(var) — discriminant check, read-only.
        WirInstr::RefTest { expr, .. } | WirInstr::RefIsNull(expr) => {
            if let WirInstr::LocalGet { name, .. } = expr.as_ref()
                && name == var_name
            {
                return true;
            }
            !instr_contains_local_get(instr, var_name)
        }
        // Comparison wrapping a ref.test/ref.is_null: `ref.test(var) != 0`
        WirInstr::I32Eq(a, b) | WirInstr::I32Ne(a, b) => {
            is_safe_condition_use(a, var_name) && is_safe_condition_use(b, var_name)
        }
        _ => !instr_contains_local_get(instr, var_name),
    }
}

/// Returns `true` if `var_name` appears in the return/break value expression only
/// as a direct `LocalGet(var_name)` inside `StructNew` or `ArrayNewFixed` fields.
///
/// Handles multi-value returns (Seq), nested `StructNew`, and Block expressions.
/// This is safe because each `StructNew` creates a fresh allocation — the variable
/// reference is consumed into a new struct, not aliased or mutated.
fn value_uses_var_only_in_struct_new_fields(instr: &WirInstr, var_name: &str) -> bool {
    match instr {
        // StructNew/ArrayNewFixed: var must appear only as direct LocalGet in fields
        WirInstr::StructNew { fields, .. }
        | WirInstr::ArrayNewFixed {
            elements: fields, ..
        } => {
            for field in fields {
                if is_direct_local_get_or_non_null(field, var_name) {
                    continue;
                }
                // Recurse into nested StructNew fields
                if instr_contains_local_get(field, var_name)
                    && !value_uses_var_only_in_struct_new_fields(field, var_name)
                {
                    return false;
                }
            }
            true
        }
        // Seq: multi-value return — check each element
        WirInstr::Seq(instrs) => instrs
            .iter()
            .all(|i| value_uses_var_only_in_struct_new_fields(i, var_name)),
        // RefAsNonNull wrapping — look through to the inner instruction
        WirInstr::RefAsNonNull(inner) => value_uses_var_only_in_struct_new_fields(inner, var_name),
        // Block: check body and break values
        WirInstr::Block { body, .. } => body
            .iter()
            .all(|i| value_uses_var_only_in_struct_new_fields(i, var_name)),
        // Doesn't contain var at all — OK
        _ if !instr_contains_local_get(instr, var_name) => true,
        // Contains var but not in a safe position
        _ => false,
    }
}

/// Returns `true` if `var_name` appears in `fields` only as direct `LocalGet(var_name)`
/// expressions (not nested inside other expressions). Other fields must not reference
/// `var_name` at all.
fn var_used_only_as_direct_local_get_in_fields(fields: &[WirInstr], var_name: &str) -> bool {
    let mut found = false;
    for field in fields {
        if is_direct_local_get_or_non_null(field, var_name) {
            found = true;
        } else if instr_contains_local_get(field, var_name) {
            return false;
        }
    }
    found
}

/// Check if an expression is `LocalGet(var)` or `RefAsNonNull(LocalGet(var))`.
fn is_direct_local_get_or_non_null(instr: &WirInstr, var_name: &str) -> bool {
    match instr {
        WirInstr::LocalGet { name, .. } => name == var_name,
        WirInstr::RefAsNonNull(inner) => {
            matches!(inner.as_ref(), WirInstr::LocalGet { name, .. } if name == var_name)
        }
        _ => false,
    }
}

/// Returns `true` if `var_name` appears as a `LocalGet` anywhere in `instr`.
fn instr_contains_local_get(instr: &WirInstr, var_name: &str) -> bool {
    if let WirInstr::LocalGet { name, .. } = instr {
        return name == var_name;
    }
    let mut found = false;
    instr.for_each_child(&mut |child| {
        if instr_contains_local_get(child, var_name) {
            found = true;
        }
    });
    found
}

/// Check if an expression's root (innermost non-StructGet, non-RefCast node)
/// is `LocalGet(var_name)`. This recognizes chains like:
/// - `LocalGet(var)`
/// - `StructGet(LocalGet(var))`
/// - `RefCast(LocalGet(var))`
/// - `StructGet(RefCast(StructGet(LocalGet(var))))`
fn expr_roots_at_var(expr: &WirInstr, var_name: &str) -> bool {
    match expr {
        WirInstr::LocalGet { name, .. } => name == var_name,
        WirInstr::StructGet { expr: inner, .. } | WirInstr::RefCast { expr: inner, .. } => {
            expr_roots_at_var(inner, var_name)
        }
        _ => false,
    }
}

/// Check if a WIR instruction provably produces a fresh value (no aliases).
fn is_fresh_wir_value(instr: &WirInstr) -> bool {
    match instr {
        // GC constructors create fresh values.
        WirInstr::StructNew { .. }
        | WirInstr::ArrayNew { .. }
        | WirInstr::ArrayNewDefault { .. }
        | WirInstr::ArrayNewData { .. }
        | WirInstr::ArrayNewFixed { .. } => true,

        // Function calls return fresh values (callee constructs them).
        WirInstr::Call { .. } | WirInstr::CallRef { .. } => true,

        // Unreachable never produces a value, so it's trivially "fresh".
        WirInstr::Unreachable => true,

        // RefAsNonNull wrapping a fresh value is still fresh.
        WirInstr::RefAsNonNull(inner) => is_fresh_wir_value(inner),

        // Block with a result: trace through to find the result value.
        WirInstr::Block {
            body,
            result: Some(_),
            ..
        } => block_result_is_fresh(body),

        // Seq: check the effective result instruction.
        WirInstr::Seq(body) => find_seq_result(body).is_some_and(is_fresh_wir_value),

        // If/else expression: fresh if every branch produces a fresh value.
        WirInstr::If {
            then_body,
            else_body,
            result: Some(_),
            ..
        } => {
            body_result_is_fresh(then_body)
                && else_body
                    .as_ref()
                    .is_some_and(|eb| body_result_is_fresh(eb))
        }

        _ => false,
    }
}

/// Determine if a block's result value is fresh.
///
/// The block's result is produced by either:
/// - A trailing `Seq([..., result_expr, Br(0)])` — the instruction before `Br`
/// - A trailing `Seq([..., LocalGet(x), Br(0)])` — trace back to find `x`'s value
/// - The last instruction in the body (fall-through)
fn block_result_is_fresh(body: &[WirInstr]) -> bool {
    let result_instr = match body.last() {
        Some(WirInstr::Seq(seq)) => find_seq_result(seq),
        Some(instr) => Some(instr),
        None => return false,
    };
    match result_instr {
        Some(WirInstr::LocalGet { name, .. }) => {
            // Trace back: find what this local was set to within the block.
            find_local_set_value(body, name).is_some_and(is_fresh_wir_value)
        }
        Some(instr) => is_fresh_wir_value(instr),
        None => false,
    }
}

/// Determine if an instruction body's result is fresh (for If branches).
///
/// The result of an If branch is the last instruction in the body.
/// Unlike blocks, If branches don't use Br to carry values.
fn body_result_is_fresh(body: &[WirInstr]) -> bool {
    match body.last() {
        Some(instr) => is_fresh_wir_value(instr),
        None => false,
    }
}

/// Find the effective result instruction of a `Seq`.
///
/// In a `Seq` ending with `Br`, the result is the instruction just before `Br`
/// (it leaves a value on the stack that `Br` carries to the enclosing block).
/// Otherwise, the last instruction is the result.
fn find_seq_result(body: &[WirInstr]) -> Option<&WirInstr> {
    if body.len() >= 2 && matches!(body.last(), Some(WirInstr::Br { .. })) {
        Some(&body[body.len() - 2])
    } else {
        body.last()
    }
}

/// Scan backward through a block body to find the value assigned to a local.
fn find_local_set_value<'a>(body: &'a [WirInstr], target: &str) -> Option<&'a WirInstr> {
    for instr in body.iter().rev() {
        if let WirInstr::LocalSet { name, value } = instr
            && name == target
        {
            return Some(value.as_ref());
        }
    }
    None
}

/// Multi-value tuple elision pass.
///
/// Matches the pattern generated by `translate_let_pattern` for multi-value
/// builtins (`i64.add128`, `i64.sub128`, `i64.mul_wide_u`, `i64.mul_wide_s`):
///
/// ```text
/// DeclareLocal { name: T, .. }                                              // optional
/// LocalSet { name: T, value: MultiValueStructNew { type_id, instr } }
/// LocalSet { name: a, value: StructGet { type_id, field: "0", expr: LocalGet(T) } }
/// LocalSet { name: b, value: StructGet { type_id, field: "1", expr: LocalGet(T) } }
/// ...
/// ```
///
/// Replaces with:
///
/// ```text
/// MultiValueLocalBind { instr, locals: [Some("a"), Some("b"), ...] }
/// ```
///
/// This eliminates a GC struct allocation per multi-value result.
fn elide_multi_value_structs(instrs: &mut Vec<WirInstr>, types: &[WirTypeDef]) {
    let mut result = Vec::with_capacity(instrs.len());
    let mut i = 0;

    while i < instrs.len() {
        // Step 1: Detect optional DeclareLocal + LocalSet(MultiValueStructNew)
        let (has_declare, set_idx) = match &instrs[i] {
            WirInstr::DeclareLocal { name: dn, .. } if i + 1 < instrs.len() => {
                if is_mv_local_set(&instrs[i + 1], dn) {
                    (true, i + 1)
                } else {
                    result.push(std::mem::replace(&mut instrs[i], WirInstr::Nop));
                    i += 1;
                    continue;
                }
            }
            _ => (false, i),
        };

        // Step 2: Verify LocalSet(MultiValueStructNew) and extract info
        let Some((temp_name, type_id_index)) = extract_mv_info(&instrs[set_idx]) else {
            result.push(std::mem::replace(&mut instrs[i], WirInstr::Nop));
            i += 1;
            continue;
        };

        // Step 3: Look up struct field count from the type definition
        let Some(WirTypeDef::Struct(s)) = types.get(type_id_index) else {
            result.push(std::mem::replace(&mut instrs[i], WirInstr::Nop));
            i += 1;
            continue;
        };
        let field_count = s.fields.len();

        // Step 4: Scan consecutive StructGet instructions reading from the temp
        let mut locals: Vec<Option<String>> = vec![None; field_count];
        let mut j = set_idx + 1;

        while j < instrs.len() {
            if let Some((idx, target)) =
                match_field_get(&instrs[j], &temp_name, field_count, &locals)
            {
                locals[idx] = Some(target);
                j += 1;
            } else {
                break;
            }
        }

        // Step 5: Require at least one field consumed
        if locals.iter().all(Option::is_none) {
            if has_declare {
                result.push(std::mem::replace(&mut instrs[i], WirInstr::Nop));
                result.push(std::mem::replace(&mut instrs[set_idx], WirInstr::Nop));
                i = set_idx + 1;
            } else {
                result.push(std::mem::replace(&mut instrs[i], WirInstr::Nop));
                i += 1;
            }
            continue;
        }

        // Step 6: Extract the inner instruction and emit MultiValueLocalBind
        let inner = take_mv_inner(&mut instrs[set_idx]);

        result.push(WirInstr::MultiValueLocalBind {
            instr: Box::new(inner),
            locals,
        });
        i = j;
    }

    *instrs = result;
}

/// Check if an instruction is `LocalSet { name, value: MultiValueStructNew { .. } }`.
fn is_mv_local_set(instr: &WirInstr, expected_name: &str) -> bool {
    matches!(
        instr,
        WirInstr::LocalSet { name, value }
            if name == expected_name
               && matches!(value.as_ref(), WirInstr::MultiValueStructNew { .. })
    )
}

/// Extract `(temp_name, type_id_index)` from a `LocalSet(MultiValueStructNew)`.
fn extract_mv_info(instr: &WirInstr) -> Option<(String, usize)> {
    let WirInstr::LocalSet { name, value } = instr else {
        return None;
    };
    let WirInstr::MultiValueStructNew { type_id, .. } = value.as_ref() else {
        return None;
    };
    Some((name.clone(), type_id.index() as usize))
}

/// Take ownership of the inner instruction from a `LocalSet(MultiValueStructNew)`.
///
/// Replaces the instruction in-place with `Nop`.
/// Returns `Box<WirInstr>` to pass directly into `MultiValueLocalBind::instr`.
fn take_mv_inner(instr: &mut WirInstr) -> WirInstr {
    let WirInstr::LocalSet { value, .. } = std::mem::replace(instr, WirInstr::Nop) else {
        unreachable!()
    };
    let WirInstr::MultiValueStructNew { instr: inner, .. } = *value else {
        unreachable!()
    };
    *inner
}

/// Try to match a `LocalSet { name, value: StructGet { field: "N", expr: LocalGet(temp) } }`.
///
/// Returns `Some((field_index, target_local_name))` on success.
fn match_field_get(
    instr: &WirInstr,
    temp_name: &str,
    field_count: usize,
    already_bound: &[Option<String>],
) -> Option<(usize, String)> {
    let WirInstr::LocalSet {
        name: target,
        value,
    } = instr
    else {
        return None;
    };
    let WirInstr::StructGet {
        field_name, expr, ..
    } = value.as_ref()
    else {
        return None;
    };
    let WirInstr::LocalGet { name: gn, .. } = expr.as_ref() else {
        return None;
    };
    if gn != temp_name {
        return None;
    }
    let idx: usize = field_name.parse().ok()?;
    if idx >= field_count || already_bound[idx].is_some() {
        return None;
    }
    Some((idx, target.clone()))
}

/// Relax `LocalGet.result_ty` from non-null to nullable for GC access operands.
///
/// GC access instructions (`array.get`, `array.set`, `struct.get`, `struct.set`,
/// `array.len`, `array.fill`, `array.copy`, `ref.cast`, `ref.test`) accept
/// `(ref null $type)`, so `ref.as_non_null` is unnecessary for their object operand.
/// Codegen emits `ref.as_non_null` only when `result_ty` is non-null, so relaxing
/// it here suppresses the redundant instruction.
fn relax_gc_operand_nullability(instrs: &mut [WirInstr]) {
    struct Relaxer;
    impl WirMutVisitor for Relaxer {
        fn visit_instr(&mut self, instr: &mut WirInstr) {
            self.walk_instr(instr);
            match instr {
                WirInstr::ArrayGet { array, .. }
                | WirInstr::ArrayGetS { array, .. }
                | WirInstr::ArrayGetU { array, .. }
                | WirInstr::ArraySet { array, .. } => relax_ref_local_get(array),
                WirInstr::ArrayLen(a) => relax_ref_local_get(a),
                WirInstr::ArrayFill { array, .. } => relax_ref_local_get(array),
                WirInstr::ArrayCopy { dest, src, .. } => {
                    relax_ref_local_get(dest);
                    relax_ref_local_get(src);
                }
                WirInstr::StructGet { expr, .. } | WirInstr::StructSet { expr, .. } => {
                    relax_ref_local_get(expr);
                }
                WirInstr::RefCast { expr, .. } | WirInstr::RefTest { expr, .. } => {
                    relax_ref_local_get(expr);
                }
                _ => {}
            }
        }
    }
    for instr in instrs.iter_mut() {
        Relaxer.visit_instr(instr);
    }
}

fn relax_ref_local_get(instr: &mut WirInstr) {
    if let WirInstr::LocalGet { result_ty, .. } = instr
        && result_ty.is_nonnull_ref()
    {
        *result_ty = result_ty.clone().as_nullable();
    }
}
