[package]
name = "wado-from-idl"
version = { workspace = true }
edition = "2024"
description = "Generate Wado standard library from IDL files (WIT, WebIDL)"
license.workspace = true

[[bin]]
name = "wado-from-idl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
indexmap.workspace = true
wit-parser = { workspace = true }
lexopt = { workspace = true }
heck = { workspace = true }

[lints]
workspace = true
