[package]
name = "wado-dev-tools"
version.workspace = true
edition = "2024"
description = "Developer tools for the Wado compiler project"
license.workspace = true

[[bin]]
name = "wado-dev-tools"
path = "src/main.rs"

[dependencies]
wado-compiler = { path = "../wado-compiler" }
dprint-plugin-markdown = { workspace = true }
glob = { workspace = true }
lexopt = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
wasmprinter = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[lints]
workspace = true
