[package]
name = "wado-from-wit"
version = "0.1.0"
edition = "2024"
description = "Generate Wado standard library from WIT files"
license.workspace = true

[[bin]]
name = "wado-from-wit"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
wit-parser = "0.244"
clap = { version = "4", features = ["derive"] }
heck = { workspace = true }
