[package]
name = "wado-playground"
version = { workspace = true }
edition = "2024"
license.workspace = true
rust-version.workspace = true
description = "wasm32 wrapper exposing the Wado compiler for an in-browser playground"

[lib]
crate-type = ["cdylib"]

[dependencies]
wado-compiler = { path = "../wado-compiler" }

[lints]
workspace = true
