[package]
name = "wado-compiler"
version = "0.1.0"
edition = "2024"
description = "Compiler for the Wado programming language"
license = { workspace = true }

[lib]
name = "wado_compiler"
path = "src/lib.rs"

[dependencies]
fluent-uri = { workspace = true }
heck = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-encoder = { workspace = true }
wasmparser = { workspace = true }
wasmprinter = { workspace = true }
wat = { workspace = true }

[dev-dependencies]
datatest-mini = { path = "../datatest-mini" }
anyhow = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
