[package]
name = "wado-compiler"
version = "0.1.0"
edition = "2024"
description = "Compiler for the Wado programming language targeting Wasm/WASI"
license = { workspace = true }

[lib]
name = "wado_compiler"
path = "src/lib.rs"

[dependencies]
wasm-encoder = { workspace = true }
wasmprinter = { workspace = true }
wat = { workspace = true }

[dev-dependencies]
wasmparser = { workspace = true }
