[workspace]

[package]
name = "cbor-bench"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "cbor_twitter_bench"
path = "serde_cbor_twitter.rs"

[[bin]]
name = "cbor_canada_bench"
path = "serde_cbor_canada.rs"

[[bin]]
name = "cbor_catalog_bench"
path = "serde_cbor_catalog.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_cbor = "0.11"
