// Generated by wado-from-idl from package-web/idl/dom.webidl.json. Do not edit.
// The `dom` module's imports, answered by the browser's own objects.

const $STRIDE = 137438953472;
// Deepest first: a class follows its ancestors in pre-order.
const $CLASSES = [
  ["Event", 7],
  ["Window", 6],
  ["Document", 5],
  ["HTMLInputElement", 4],
  ["HTMLElement", 3],
  ["Element", 2],
  ["Node", 1],
  ["EventTarget", 0],
];

const $objects = [];
const $handles = new Map();

function $handle(object) {
  let handle = $handles.get(object);
  if (handle === undefined) {
    const entry = $CLASSES.find(
      ([name]) => globalThis[name] !== undefined && object instanceof globalThis[name],
    );
    if (entry === undefined) {
      throw new TypeError(`${object} is an instance of no interface this package declares`);
    }
    handle = entry[1] * $STRIDE + $objects.push(object) - 1;
    $handles.set(object, handle);
  }
  return handle;
}

const $object = (handle) => $objects[handle % $STRIDE];
const $some = (f) => (value) => (value === undefined ? undefined : f(value));
const $nullable = (f) => (value) => (value === null ? undefined : f(value));
const $someObject = $some($object);
const $nullableHandle = $nullable($handle);
const $someNumber = $some(Number);
const $nullableBigInt = $nullable(BigInt);

// The component's `wado:callback/callback` export, which calls a closure back.
// The component hands it over once instantiated.
let $callbackExport;

export function $connect(callback) {
  $callbackExport = callback;
}

// One function per closure key, so `removeEventListener` is handed the very
// function `addEventListener` was.
const $callbacks = new Map();

function $callback(key, call) {
  let f = $callbacks.get(key);
  if (f === undefined) {
    f = (...args) => call(key, ...args);
    $callbacks.set(key, f);
  }
  return f;
}

export const eventTarget = {
  new() {
    return $handle(new globalThis.EventTarget());
  },
  addEventListener(self, type, callback, options) {
    $object(self).addEventListener(type, $callback(callback, (key, a0) => $callbackExport.callHandle(key, $handle(a0))), options);
  },
  removeEventListener(self, type, callback, options) {
    $object(self).removeEventListener(type, $callback(callback, (key, a0) => $callbackExport.callHandle(key, $handle(a0))), options);
  },
  dispatchEvent(self, event) {
    return $object(self).dispatchEvent($object(event));
  },
};

export const event = {
  new(type) {
    return $handle(new globalThis.Event(type));
  },
  type(self) {
    return $object(self).type;
  },
  target(self) {
    return $nullableHandle($object(self).target);
  },
  srcElement(self) {
    return $nullableHandle($object(self).srcElement);
  },
  currentTarget(self) {
    return $nullableHandle($object(self).currentTarget);
  },
  eventPhase(self) {
    return $object(self).eventPhase;
  },
  stopPropagation(self) {
    $object(self).stopPropagation();
  },
  cancelBubble(self) {
    return $object(self).cancelBubble;
  },
  setCancelBubble(self, value) {
    $object(self).cancelBubble = value;
  },
  stopImmediatePropagation(self) {
    $object(self).stopImmediatePropagation();
  },
  bubbles(self) {
    return $object(self).bubbles;
  },
  cancelable(self) {
    return $object(self).cancelable;
  },
  returnValue(self) {
    return $object(self).returnValue;
  },
  setReturnValue(self, value) {
    $object(self).returnValue = value;
  },
  preventDefault(self) {
    $object(self).preventDefault();
  },
  defaultPrevented(self) {
    return $object(self).defaultPrevented;
  },
  composed(self) {
    return $object(self).composed;
  },
  isTrusted(self) {
    return $object(self).isTrusted;
  },
  timeStamp(self) {
    return $object(self).timeStamp;
  },
  initEvent(self, type, bubbles, cancelable) {
    $object(self).initEvent(type, bubbles, cancelable);
  },
};

export const node = {
  nodeType(self) {
    return $object(self).nodeType;
  },
  nodeName(self) {
    return $object(self).nodeName;
  },
  baseUri(self) {
    return $object(self).baseURI;
  },
  isConnected(self) {
    return $object(self).isConnected;
  },
  ownerDocument(self) {
    return $nullableHandle($object(self).ownerDocument);
  },
  getRootNode(self) {
    return $handle($object(self).getRootNode());
  },
  parentNode(self) {
    return $nullableHandle($object(self).parentNode);
  },
  parentElement(self) {
    return $nullableHandle($object(self).parentElement);
  },
  hasChildNodes(self) {
    return $object(self).hasChildNodes();
  },
  firstChild(self) {
    return $nullableHandle($object(self).firstChild);
  },
  lastChild(self) {
    return $nullableHandle($object(self).lastChild);
  },
  previousSibling(self) {
    return $nullableHandle($object(self).previousSibling);
  },
  nextSibling(self) {
    return $nullableHandle($object(self).nextSibling);
  },
  nodeValue(self) {
    return $object(self).nodeValue;
  },
  setNodeValue(self, value) {
    $object(self).nodeValue = value;
  },
  textContent(self) {
    return $object(self).textContent;
  },
  setTextContent(self, value) {
    $object(self).textContent = value;
  },
  normalize(self) {
    $object(self).normalize();
  },
  cloneNode(self, subtree) {
    return $handle($object(self).cloneNode(subtree));
  },
  isEqualNode(self, otherNode) {
    return $object(self).isEqualNode($someObject(otherNode));
  },
  isSameNode(self, otherNode) {
    return $object(self).isSameNode($someObject(otherNode));
  },
  compareDocumentPosition(self, other) {
    return $object(self).compareDocumentPosition($object(other));
  },
  contains(self, other) {
    return $object(self).contains($someObject(other));
  },
  lookupPrefix(self, namespace) {
    return $object(self).lookupPrefix(namespace);
  },
  lookupNamespaceUri(self, prefix) {
    return $object(self).lookupNamespaceURI(prefix);
  },
  isDefaultNamespace(self, namespace) {
    return $object(self).isDefaultNamespace(namespace);
  },
  insertBefore(self, node, child) {
    return $handle($object(self).insertBefore($object(node), $someObject(child)));
  },
  appendChild(self, node) {
    return $handle($object(self).appendChild($object(node)));
  },
  replaceChild(self, node, child) {
    return $handle($object(self).replaceChild($object(node), $object(child)));
  },
  removeChild(self, child) {
    return $handle($object(self).removeChild($object(child)));
  },
};

export const element = {
  getSpatialNavigationContainer(self) {
    return $handle($object(self).getSpatialNavigationContainer());
  },
  checkVisibility(self) {
    return $object(self).checkVisibility();
  },
  scrollTop(self) {
    return $object(self).scrollTop;
  },
  setScrollTop(self, value) {
    $object(self).scrollTop = value;
  },
  scrollLeft(self) {
    return $object(self).scrollLeft;
  },
  setScrollLeft(self, value) {
    $object(self).scrollLeft = value;
  },
  scrollWidth(self) {
    return $object(self).scrollWidth;
  },
  scrollHeight(self) {
    return $object(self).scrollHeight;
  },
  clientTop(self) {
    return $object(self).clientTop;
  },
  clientLeft(self) {
    return $object(self).clientLeft;
  },
  clientWidth(self) {
    return $object(self).clientWidth;
  },
  clientHeight(self) {
    return $object(self).clientHeight;
  },
  currentCssZoom(self) {
    return $object(self).currentCSSZoom;
  },
  namespaceUri(self) {
    return $object(self).namespaceURI;
  },
  prefix(self) {
    return $object(self).prefix;
  },
  localName(self) {
    return $object(self).localName;
  },
  tagName(self) {
    return $object(self).tagName;
  },
  id(self) {
    return $object(self).id;
  },
  setId(self, value) {
    $object(self).id = value;
  },
  className(self) {
    return $object(self).className;
  },
  setClassName(self, value) {
    $object(self).className = value;
  },
  slot(self) {
    return $object(self).slot;
  },
  setSlot(self, value) {
    $object(self).slot = value;
  },
  hasAttributes(self) {
    return $object(self).hasAttributes();
  },
  getAttribute(self, qualifiedName) {
    return $object(self).getAttribute(qualifiedName);
  },
  getAttributeNs(self, namespace, localName) {
    return $object(self).getAttributeNS(namespace, localName);
  },
  setAttribute(self, qualifiedName, value) {
    $object(self).setAttribute(qualifiedName, value);
  },
  setAttributeNs(self, namespace, qualifiedName, value) {
    $object(self).setAttributeNS(namespace, qualifiedName, value);
  },
  removeAttribute(self, qualifiedName) {
    $object(self).removeAttribute(qualifiedName);
  },
  removeAttributeNs(self, namespace, localName) {
    $object(self).removeAttributeNS(namespace, localName);
  },
  toggleAttribute(self, qualifiedName, force) {
    return $object(self).toggleAttribute(qualifiedName, force);
  },
  hasAttribute(self, qualifiedName) {
    return $object(self).hasAttribute(qualifiedName);
  },
  hasAttributeNs(self, namespace, localName) {
    return $object(self).hasAttributeNS(namespace, localName);
  },
  closest(self, selectors) {
    return $nullableHandle($object(self).closest(selectors));
  },
  matches(self, selectors) {
    return $object(self).matches(selectors);
  },
  webkitMatchesSelector(self, selectors) {
    return $object(self).webkitMatchesSelector(selectors);
  },
  insertAdjacentElement(self, where, element) {
    return $nullableHandle($object(self).insertAdjacentElement(where, $object(element)));
  },
  insertAdjacentText(self, where, data) {
    $object(self).insertAdjacentText(where, data);
  },
  elementTiming(self) {
    return $object(self).elementTiming;
  },
  setElementTiming(self, value) {
    $object(self).elementTiming = value;
  },
  setHtml(self, html) {
    $object(self).setHTML(html);
  },
  setHtmlUnsafe(self, html) {
    $object(self).setHTMLUnsafe(html);
  },
  getHtml(self) {
    return $object(self).getHTML();
  },
  setInnerHtml(self, value) {
    $object(self).innerHTML = value;
  },
  setOuterHtml(self, value) {
    $object(self).outerHTML = value;
  },
  insertAdjacentHtml(self, position, string) {
    $object(self).insertAdjacentHTML(position, string);
  },
  setPointerCapture(self, pointerId) {
    $object(self).setPointerCapture(pointerId);
  },
  releasePointerCapture(self, pointerId) {
    $object(self).releasePointerCapture(pointerId);
  },
  hasPointerCapture(self, pointerId) {
    return $object(self).hasPointerCapture(pointerId);
  },
  firstElementChild(self) {
    return $nullableHandle($object(self).firstElementChild);
  },
  lastElementChild(self) {
    return $nullableHandle($object(self).lastElementChild);
  },
  childElementCount(self) {
    return $object(self).childElementCount;
  },
  moveBefore(self, node, child) {
    $object(self).moveBefore($object(node), $someObject(child));
  },
  querySelector(self, selectors) {
    return $nullableHandle($object(self).querySelector(selectors));
  },
  previousElementSibling(self) {
    return $nullableHandle($object(self).previousElementSibling);
  },
  nextElementSibling(self) {
    return $nullableHandle($object(self).nextElementSibling);
  },
  remove(self) {
    $object(self).remove();
  },
  role(self) {
    return $object(self).role;
  },
  setRole(self, value) {
    $object(self).role = value;
  },
  ariaActiveDescendantElement(self) {
    return $nullableHandle($object(self).ariaActiveDescendantElement);
  },
  setAriaActiveDescendantElement(self, value) {
    $object(self).ariaActiveDescendantElement = $someObject(value);
  },
  ariaAtomic(self) {
    return $object(self).ariaAtomic;
  },
  setAriaAtomic(self, value) {
    $object(self).ariaAtomic = value;
  },
  ariaAutoComplete(self) {
    return $object(self).ariaAutoComplete;
  },
  setAriaAutoComplete(self, value) {
    $object(self).ariaAutoComplete = value;
  },
  ariaBrailleLabel(self) {
    return $object(self).ariaBrailleLabel;
  },
  setAriaBrailleLabel(self, value) {
    $object(self).ariaBrailleLabel = value;
  },
  ariaBrailleRoleDescription(self) {
    return $object(self).ariaBrailleRoleDescription;
  },
  setAriaBrailleRoleDescription(self, value) {
    $object(self).ariaBrailleRoleDescription = value;
  },
  ariaBusy(self) {
    return $object(self).ariaBusy;
  },
  setAriaBusy(self, value) {
    $object(self).ariaBusy = value;
  },
  ariaChecked(self) {
    return $object(self).ariaChecked;
  },
  setAriaChecked(self, value) {
    $object(self).ariaChecked = value;
  },
  ariaColCount(self) {
    return $object(self).ariaColCount;
  },
  setAriaColCount(self, value) {
    $object(self).ariaColCount = value;
  },
  ariaColIndex(self) {
    return $object(self).ariaColIndex;
  },
  setAriaColIndex(self, value) {
    $object(self).ariaColIndex = value;
  },
  ariaColIndexText(self) {
    return $object(self).ariaColIndexText;
  },
  setAriaColIndexText(self, value) {
    $object(self).ariaColIndexText = value;
  },
  ariaColSpan(self) {
    return $object(self).ariaColSpan;
  },
  setAriaColSpan(self, value) {
    $object(self).ariaColSpan = value;
  },
  ariaCurrent(self) {
    return $object(self).ariaCurrent;
  },
  setAriaCurrent(self, value) {
    $object(self).ariaCurrent = value;
  },
  ariaDescription(self) {
    return $object(self).ariaDescription;
  },
  setAriaDescription(self, value) {
    $object(self).ariaDescription = value;
  },
  ariaDisabled(self) {
    return $object(self).ariaDisabled;
  },
  setAriaDisabled(self, value) {
    $object(self).ariaDisabled = value;
  },
  ariaExpanded(self) {
    return $object(self).ariaExpanded;
  },
  setAriaExpanded(self, value) {
    $object(self).ariaExpanded = value;
  },
  ariaHasPopup(self) {
    return $object(self).ariaHasPopup;
  },
  setAriaHasPopup(self, value) {
    $object(self).ariaHasPopup = value;
  },
  ariaHidden(self) {
    return $object(self).ariaHidden;
  },
  setAriaHidden(self, value) {
    $object(self).ariaHidden = value;
  },
  ariaInvalid(self) {
    return $object(self).ariaInvalid;
  },
  setAriaInvalid(self, value) {
    $object(self).ariaInvalid = value;
  },
  ariaKeyShortcuts(self) {
    return $object(self).ariaKeyShortcuts;
  },
  setAriaKeyShortcuts(self, value) {
    $object(self).ariaKeyShortcuts = value;
  },
  ariaLabel(self) {
    return $object(self).ariaLabel;
  },
  setAriaLabel(self, value) {
    $object(self).ariaLabel = value;
  },
  ariaLevel(self) {
    return $object(self).ariaLevel;
  },
  setAriaLevel(self, value) {
    $object(self).ariaLevel = value;
  },
  ariaLive(self) {
    return $object(self).ariaLive;
  },
  setAriaLive(self, value) {
    $object(self).ariaLive = value;
  },
  ariaModal(self) {
    return $object(self).ariaModal;
  },
  setAriaModal(self, value) {
    $object(self).ariaModal = value;
  },
  ariaMultiLine(self) {
    return $object(self).ariaMultiLine;
  },
  setAriaMultiLine(self, value) {
    $object(self).ariaMultiLine = value;
  },
  ariaMultiSelectable(self) {
    return $object(self).ariaMultiSelectable;
  },
  setAriaMultiSelectable(self, value) {
    $object(self).ariaMultiSelectable = value;
  },
  ariaOrientation(self) {
    return $object(self).ariaOrientation;
  },
  setAriaOrientation(self, value) {
    $object(self).ariaOrientation = value;
  },
  ariaPlaceholder(self) {
    return $object(self).ariaPlaceholder;
  },
  setAriaPlaceholder(self, value) {
    $object(self).ariaPlaceholder = value;
  },
  ariaPosInSet(self) {
    return $object(self).ariaPosInSet;
  },
  setAriaPosInSet(self, value) {
    $object(self).ariaPosInSet = value;
  },
  ariaPressed(self) {
    return $object(self).ariaPressed;
  },
  setAriaPressed(self, value) {
    $object(self).ariaPressed = value;
  },
  ariaReadOnly(self) {
    return $object(self).ariaReadOnly;
  },
  setAriaReadOnly(self, value) {
    $object(self).ariaReadOnly = value;
  },
  ariaRelevant(self) {
    return $object(self).ariaRelevant;
  },
  setAriaRelevant(self, value) {
    $object(self).ariaRelevant = value;
  },
  ariaRequired(self) {
    return $object(self).ariaRequired;
  },
  setAriaRequired(self, value) {
    $object(self).ariaRequired = value;
  },
  ariaRoleDescription(self) {
    return $object(self).ariaRoleDescription;
  },
  setAriaRoleDescription(self, value) {
    $object(self).ariaRoleDescription = value;
  },
  ariaRowCount(self) {
    return $object(self).ariaRowCount;
  },
  setAriaRowCount(self, value) {
    $object(self).ariaRowCount = value;
  },
  ariaRowIndex(self) {
    return $object(self).ariaRowIndex;
  },
  setAriaRowIndex(self, value) {
    $object(self).ariaRowIndex = value;
  },
  ariaRowIndexText(self) {
    return $object(self).ariaRowIndexText;
  },
  setAriaRowIndexText(self, value) {
    $object(self).ariaRowIndexText = value;
  },
  ariaRowSpan(self) {
    return $object(self).ariaRowSpan;
  },
  setAriaRowSpan(self, value) {
    $object(self).ariaRowSpan = value;
  },
  ariaSelected(self) {
    return $object(self).ariaSelected;
  },
  setAriaSelected(self, value) {
    $object(self).ariaSelected = value;
  },
  ariaSetSize(self) {
    return $object(self).ariaSetSize;
  },
  setAriaSetSize(self, value) {
    $object(self).ariaSetSize = value;
  },
  ariaSort(self) {
    return $object(self).ariaSort;
  },
  setAriaSort(self, value) {
    $object(self).ariaSort = value;
  },
  ariaValueMax(self) {
    return $object(self).ariaValueMax;
  },
  setAriaValueMax(self, value) {
    $object(self).ariaValueMax = value;
  },
  ariaValueMin(self) {
    return $object(self).ariaValueMin;
  },
  setAriaValueMin(self, value) {
    $object(self).ariaValueMin = value;
  },
  ariaValueNow(self) {
    return $object(self).ariaValueNow;
  },
  setAriaValueNow(self, value) {
    $object(self).ariaValueNow = value;
  },
  ariaValueText(self) {
    return $object(self).ariaValueText;
  },
  setAriaValueText(self, value) {
    $object(self).ariaValueText = value;
  },
  ariaNotify(self, announcement) {
    $object(self).ariaNotify(announcement);
  },
};

export const htmlElement = {
  containerTiming(self) {
    return $object(self).containerTiming;
  },
  setContainerTiming(self, value) {
    $object(self).containerTiming = value;
  },
  containerTimingIgnore(self) {
    return $object(self).containerTimingIgnore;
  },
  setContainerTimingIgnore(self, value) {
    $object(self).containerTimingIgnore = value;
  },
  scrollParent(self) {
    return $nullableHandle($object(self).scrollParent);
  },
  offsetParent(self) {
    return $nullableHandle($object(self).offsetParent);
  },
  offsetTop(self) {
    return $object(self).offsetTop;
  },
  offsetLeft(self) {
    return $object(self).offsetLeft;
  },
  offsetWidth(self) {
    return $object(self).offsetWidth;
  },
  offsetHeight(self) {
    return $object(self).offsetHeight;
  },
  title(self) {
    return $object(self).title;
  },
  setTitle(self, value) {
    $object(self).title = value;
  },
  lang(self) {
    return $object(self).lang;
  },
  setLang(self, value) {
    $object(self).lang = value;
  },
  translate(self) {
    return $object(self).translate;
  },
  setTranslate(self, value) {
    $object(self).translate = value;
  },
  dir(self) {
    return $object(self).dir;
  },
  setDir(self, value) {
    $object(self).dir = value;
  },
  inert(self) {
    return $object(self).inert;
  },
  setInert(self, value) {
    $object(self).inert = value;
  },
  click(self) {
    $object(self).click();
  },
  accessKey(self) {
    return $object(self).accessKey;
  },
  setAccessKey(self, value) {
    $object(self).accessKey = value;
  },
  accessKeyLabel(self) {
    return $object(self).accessKeyLabel;
  },
  draggable(self) {
    return $object(self).draggable;
  },
  setDraggable(self, value) {
    $object(self).draggable = value;
  },
  spellcheck(self) {
    return $object(self).spellcheck;
  },
  setSpellcheck(self, value) {
    $object(self).spellcheck = value;
  },
  writingSuggestions(self) {
    return $object(self).writingSuggestions;
  },
  setWritingSuggestions(self, value) {
    $object(self).writingSuggestions = value;
  },
  autocapitalize(self) {
    return $object(self).autocapitalize;
  },
  setAutocapitalize(self, value) {
    $object(self).autocapitalize = value;
  },
  autocorrect(self) {
    return $object(self).autocorrect;
  },
  setAutocorrect(self, value) {
    $object(self).autocorrect = value;
  },
  innerText(self) {
    return $object(self).innerText;
  },
  setInnerText(self, value) {
    $object(self).innerText = value;
  },
  outerText(self) {
    return $object(self).outerText;
  },
  setOuterText(self, value) {
    $object(self).outerText = value;
  },
  showPopover(self) {
    $object(self).showPopover();
  },
  hidePopover(self) {
    $object(self).hidePopover();
  },
  togglePopover(self, options) {
    return $object(self).togglePopover(options);
  },
  popover(self) {
    return $object(self).popover;
  },
  setPopover(self, value) {
    $object(self).popover = value;
  },
  headingOffset(self) {
    return $object(self).headingOffset;
  },
  setHeadingOffset(self, value) {
    $object(self).headingOffset = value;
  },
  headingReset(self) {
    return $object(self).headingReset;
  },
  setHeadingReset(self, value) {
    $object(self).headingReset = value;
  },
  contentEditable(self) {
    return $object(self).contentEditable;
  },
  setContentEditable(self, value) {
    $object(self).contentEditable = value;
  },
  enterKeyHint(self) {
    return $object(self).enterKeyHint;
  },
  setEnterKeyHint(self, value) {
    $object(self).enterKeyHint = value;
  },
  isContentEditable(self) {
    return $object(self).isContentEditable;
  },
  inputMode(self) {
    return $object(self).inputMode;
  },
  setInputMode(self, value) {
    $object(self).inputMode = value;
  },
  virtualKeyboardPolicy(self) {
    return $object(self).virtualKeyboardPolicy;
  },
  setVirtualKeyboardPolicy(self, value) {
    $object(self).virtualKeyboardPolicy = value;
  },
  nonce(self) {
    return $object(self).nonce;
  },
  setNonce(self, value) {
    $object(self).nonce = value;
  },
  autofocus(self) {
    return $object(self).autofocus;
  },
  setAutofocus(self, value) {
    $object(self).autofocus = value;
  },
  tabIndex(self) {
    return $object(self).tabIndex;
  },
  setTabIndex(self, value) {
    $object(self).tabIndex = value;
  },
  focus(self) {
    $object(self).focus();
  },
  blur(self) {
    $object(self).blur();
  },
};

export const htmlInputElement = {
  webkitdirectory(self) {
    return $object(self).webkitdirectory;
  },
  setWebkitdirectory(self, value) {
    $object(self).webkitdirectory = value;
  },
  accept(self) {
    return $object(self).accept;
  },
  setAccept(self, value) {
    $object(self).accept = value;
  },
  alpha(self) {
    return $object(self).alpha;
  },
  setAlpha(self, value) {
    $object(self).alpha = value;
  },
  alt(self) {
    return $object(self).alt;
  },
  setAlt(self, value) {
    $object(self).alt = value;
  },
  autocomplete(self) {
    return $object(self).autocomplete;
  },
  setAutocomplete(self, value) {
    $object(self).autocomplete = value;
  },
  defaultChecked(self) {
    return $object(self).defaultChecked;
  },
  setDefaultChecked(self, value) {
    $object(self).defaultChecked = value;
  },
  checked(self) {
    return $object(self).checked;
  },
  setChecked(self, value) {
    $object(self).checked = value;
  },
  colorSpace(self) {
    return $object(self).colorSpace;
  },
  setColorSpace(self, value) {
    $object(self).colorSpace = value;
  },
  dirName(self) {
    return $object(self).dirName;
  },
  setDirName(self, value) {
    $object(self).dirName = value;
  },
  disabled(self) {
    return $object(self).disabled;
  },
  setDisabled(self, value) {
    $object(self).disabled = value;
  },
  formAction(self) {
    return $object(self).formAction;
  },
  setFormAction(self, value) {
    $object(self).formAction = value;
  },
  formEnctype(self) {
    return $object(self).formEnctype;
  },
  setFormEnctype(self, value) {
    $object(self).formEnctype = value;
  },
  formMethod(self) {
    return $object(self).formMethod;
  },
  setFormMethod(self, value) {
    $object(self).formMethod = value;
  },
  formNoValidate(self) {
    return $object(self).formNoValidate;
  },
  setFormNoValidate(self, value) {
    $object(self).formNoValidate = value;
  },
  formTarget(self) {
    return $object(self).formTarget;
  },
  setFormTarget(self, value) {
    $object(self).formTarget = value;
  },
  height(self) {
    return $object(self).height;
  },
  setHeight(self, value) {
    $object(self).height = value;
  },
  indeterminate(self) {
    return $object(self).indeterminate;
  },
  setIndeterminate(self, value) {
    $object(self).indeterminate = value;
  },
  max(self) {
    return $object(self).max;
  },
  setMax(self, value) {
    $object(self).max = value;
  },
  maxLength(self) {
    return $object(self).maxLength;
  },
  setMaxLength(self, value) {
    $object(self).maxLength = value;
  },
  min(self) {
    return $object(self).min;
  },
  setMin(self, value) {
    $object(self).min = value;
  },
  minLength(self) {
    return $object(self).minLength;
  },
  setMinLength(self, value) {
    $object(self).minLength = value;
  },
  multiple(self) {
    return $object(self).multiple;
  },
  setMultiple(self, value) {
    $object(self).multiple = value;
  },
  name(self) {
    return $object(self).name;
  },
  setName(self, value) {
    $object(self).name = value;
  },
  pattern(self) {
    return $object(self).pattern;
  },
  setPattern(self, value) {
    $object(self).pattern = value;
  },
  placeholder(self) {
    return $object(self).placeholder;
  },
  setPlaceholder(self, value) {
    $object(self).placeholder = value;
  },
  readOnly(self) {
    return $object(self).readOnly;
  },
  setReadOnly(self, value) {
    $object(self).readOnly = value;
  },
  required(self) {
    return $object(self).required;
  },
  setRequired(self, value) {
    $object(self).required = value;
  },
  size(self) {
    return $object(self).size;
  },
  setSize(self, value) {
    $object(self).size = value;
  },
  src(self) {
    return $object(self).src;
  },
  setSrc(self, value) {
    $object(self).src = value;
  },
  step(self) {
    return $object(self).step;
  },
  setStep(self, value) {
    $object(self).step = value;
  },
  type(self) {
    return $object(self).type;
  },
  setType(self, value) {
    $object(self).type = value;
  },
  defaultValue(self) {
    return $object(self).defaultValue;
  },
  setDefaultValue(self, value) {
    $object(self).defaultValue = value;
  },
  value(self) {
    return $object(self).value;
  },
  setValue(self, value) {
    $object(self).value = value;
  },
  valueAsNumber(self) {
    return $object(self).valueAsNumber;
  },
  setValueAsNumber(self, value) {
    $object(self).valueAsNumber = value;
  },
  width(self) {
    return $object(self).width;
  },
  setWidth(self, value) {
    $object(self).width = value;
  },
  stepUp(self, n) {
    $object(self).stepUp(n);
  },
  stepDown(self, n) {
    $object(self).stepDown(n);
  },
  willValidate(self) {
    return $object(self).willValidate;
  },
  validationMessage(self) {
    return $object(self).validationMessage;
  },
  checkValidity(self) {
    return $object(self).checkValidity();
  },
  reportValidity(self) {
    return $object(self).reportValidity();
  },
  setCustomValidity(self, error) {
    $object(self).setCustomValidity(error);
  },
  select(self) {
    $object(self).select();
  },
  selectionStart(self) {
    return $object(self).selectionStart;
  },
  setSelectionStart(self, value) {
    $object(self).selectionStart = value;
  },
  selectionEnd(self) {
    return $object(self).selectionEnd;
  },
  setSelectionEnd(self, value) {
    $object(self).selectionEnd = value;
  },
  selectionDirection(self) {
    return $object(self).selectionDirection;
  },
  setSelectionDirection(self, value) {
    $object(self).selectionDirection = value;
  },
  setSelectionRange(self, start, end, direction) {
    $object(self).setSelectionRange(start, end, direction);
  },
  showPicker(self) {
    $object(self).showPicker();
  },
  align(self) {
    return $object(self).align;
  },
  setAlign(self, value) {
    $object(self).align = value;
  },
  useMap(self) {
    return $object(self).useMap;
  },
  setUseMap(self, value) {
    $object(self).useMap = value;
  },
  capture(self) {
    return $object(self).capture;
  },
  setCapture(self, value) {
    $object(self).capture = value;
  },
  popoverTargetElement(self) {
    return $nullableHandle($object(self).popoverTargetElement);
  },
  setPopoverTargetElement(self, value) {
    $object(self).popoverTargetElement = $someObject(value);
  },
  popoverTargetAction(self) {
    return $object(self).popoverTargetAction;
  },
  setPopoverTargetAction(self, value) {
    $object(self).popoverTargetAction = value;
  },
};

export const document = {
  elementFromPoint(self, x, y) {
    return $nullableHandle($object(self).elementFromPoint(x, y));
  },
  scrollingElement(self) {
    return $nullableHandle($object(self).scrollingElement);
  },
  new() {
    return $handle(new globalThis.Document());
  },
  url(self) {
    return $object(self).URL;
  },
  documentUri(self) {
    return $object(self).documentURI;
  },
  compatMode(self) {
    return $object(self).compatMode;
  },
  characterSet(self) {
    return $object(self).characterSet;
  },
  charset(self) {
    return $object(self).charset;
  },
  inputEncoding(self) {
    return $object(self).inputEncoding;
  },
  contentType(self) {
    return $object(self).contentType;
  },
  documentElement(self) {
    return $nullableHandle($object(self).documentElement);
  },
  createElement(self, localName, options) {
    return $handle($object(self).createElement(localName, options));
  },
  createElementNs(self, namespace, qualifiedName, options) {
    return $handle($object(self).createElementNS(namespace, qualifiedName, options));
  },
  importNode(self, node, options) {
    return $handle($object(self).importNode($object(node), options));
  },
  adoptNode(self, node) {
    return $handle($object(self).adoptNode($object(node)));
  },
  createEvent(self, interface_) {
    return $handle($object(self).createEvent(interface_));
  },
  fullscreenEnabled(self) {
    return $object(self).fullscreenEnabled;
  },
  fullscreen(self) {
    return $object(self).fullscreen;
  },
  parseHtmlUnsafe(html) {
    return $handle(globalThis.Document.parseHTMLUnsafe(html));
  },
  parseHtml(html) {
    return $handle(globalThis.Document.parseHTML(html));
  },
  domain(self) {
    return $object(self).domain;
  },
  setDomain(self, value) {
    $object(self).domain = value;
  },
  referrer(self) {
    return $object(self).referrer;
  },
  cookie(self) {
    return $object(self).cookie;
  },
  setCookie(self, value) {
    $object(self).cookie = value;
  },
  lastModified(self) {
    return $object(self).lastModified;
  },
  title(self) {
    return $object(self).title;
  },
  setTitle(self, value) {
    $object(self).title = value;
  },
  dir(self) {
    return $object(self).dir;
  },
  setDir(self, value) {
    $object(self).dir = value;
  },
  body(self) {
    return $nullableHandle($object(self).body);
  },
  setBody(self, value) {
    $object(self).body = $someObject(value);
  },
  open(self, unused1, unused2) {
    return $handle($object(self).open(unused1, unused2));
  },
  close(self) {
    $object(self).close();
  },
  hasFocus(self) {
    return $object(self).hasFocus();
  },
  designMode(self) {
    return $object(self).designMode;
  },
  setDesignMode(self, value) {
    $object(self).designMode = value;
  },
  execCommand(self, commandId, showUi, value) {
    return $object(self).execCommand(commandId, showUi, value);
  },
  queryCommandEnabled(self, commandId) {
    return $object(self).queryCommandEnabled(commandId);
  },
  queryCommandIndeterm(self, commandId) {
    return $object(self).queryCommandIndeterm(commandId);
  },
  queryCommandState(self, commandId) {
    return $object(self).queryCommandState(commandId);
  },
  queryCommandSupported(self, commandId) {
    return $object(self).queryCommandSupported(commandId);
  },
  queryCommandValue(self, commandId) {
    return $object(self).queryCommandValue(commandId);
  },
  hidden(self) {
    return $object(self).hidden;
  },
  fgColor(self) {
    return $object(self).fgColor;
  },
  setFgColor(self, value) {
    $object(self).fgColor = value;
  },
  linkColor(self) {
    return $object(self).linkColor;
  },
  setLinkColor(self, value) {
    $object(self).linkColor = value;
  },
  vlinkColor(self) {
    return $object(self).vlinkColor;
  },
  setVlinkColor(self, value) {
    $object(self).vlinkColor = value;
  },
  alinkColor(self) {
    return $object(self).alinkColor;
  },
  setAlinkColor(self, value) {
    $object(self).alinkColor = value;
  },
  bgColor(self) {
    return $object(self).bgColor;
  },
  setBgColor(self, value) {
    $object(self).bgColor = value;
  },
  clear(self) {
    $object(self).clear();
  },
  captureEvents(self) {
    $object(self).captureEvents();
  },
  releaseEvents(self) {
    $object(self).releaseEvents();
  },
  wasDiscarded(self) {
    return $object(self).wasDiscarded;
  },
  pictureInPictureEnabled(self) {
    return $object(self).pictureInPictureEnabled;
  },
  exitPointerLock(self) {
    $object(self).exitPointerLock();
  },
  prerendering(self) {
    return $object(self).prerendering;
  },
  getElementById(self, elementId) {
    return $nullableHandle($object(self).getElementById(elementId));
  },
  fullscreenElement(self) {
    return $nullableHandle($object(self).fullscreenElement);
  },
  activeElement(self) {
    return $nullableHandle($object(self).activeElement);
  },
  pictureInPictureElement(self) {
    return $nullableHandle($object(self).pictureInPictureElement);
  },
  pointerLockElement(self) {
    return $nullableHandle($object(self).pointerLockElement);
  },
  firstElementChild(self) {
    return $nullableHandle($object(self).firstElementChild);
  },
  lastElementChild(self) {
    return $nullableHandle($object(self).lastElementChild);
  },
  childElementCount(self) {
    return $object(self).childElementCount;
  },
  moveBefore(self, node, child) {
    $object(self).moveBefore($object(node), $someObject(child));
  },
  querySelector(self, selectors) {
    return $nullableHandle($object(self).querySelector(selectors));
  },
  createNsResolver(self, nodeResolver) {
    return $handle($object(self).createNSResolver($object(nodeResolver)));
  },
  ariaNotify(self, announcement) {
    $object(self).ariaNotify(announcement);
  },
};

export const window = {
  credentialless(self) {
    return $object(self).credentialless;
  },
  orientation(self) {
    return $object(self).orientation;
  },
  requestResize(self) {
    $object(self).requestResize();
  },
  moveTo(self, x, y) {
    $object(self).moveTo(x, y);
  },
  moveBy(self, x, y) {
    $object(self).moveBy(x, y);
  },
  resizeTo(self, width, height) {
    $object(self).resizeTo(width, height);
  },
  resizeBy(self, x, y) {
    $object(self).resizeBy(x, y);
  },
  innerWidth(self) {
    return $object(self).innerWidth;
  },
  innerHeight(self) {
    return $object(self).innerHeight;
  },
  scrollX(self) {
    return $object(self).scrollX;
  },
  pageXOffset(self) {
    return $object(self).pageXOffset;
  },
  scrollY(self) {
    return $object(self).scrollY;
  },
  pageYOffset(self) {
    return $object(self).pageYOffset;
  },
  screenX(self) {
    return $object(self).screenX;
  },
  screenLeft(self) {
    return $object(self).screenLeft;
  },
  screenY(self) {
    return $object(self).screenY;
  },
  screenTop(self) {
    return $object(self).screenTop;
  },
  outerWidth(self) {
    return $object(self).outerWidth;
  },
  outerHeight(self) {
    return $object(self).outerHeight;
  },
  devicePixelRatio(self) {
    return $object(self).devicePixelRatio;
  },
  event(self) {
    return $nullableHandle($object(self).event);
  },
  document(self) {
    return $handle($object(self).document);
  },
  name(self) {
    return $object(self).name;
  },
  setName(self, value) {
    $object(self).name = value;
  },
  status(self) {
    return $object(self).status;
  },
  setStatus(self, value) {
    $object(self).status = value;
  },
  close(self) {
    $object(self).close();
  },
  closed(self) {
    return $object(self).closed;
  },
  stop(self) {
    $object(self).stop();
  },
  focus(self) {
    $object(self).focus();
  },
  blur(self) {
    $object(self).blur();
  },
  length(self) {
    return $object(self).length;
  },
  frameElement(self) {
    return $nullableHandle($object(self).frameElement);
  },
  originAgentCluster(self) {
    return $object(self).originAgentCluster;
  },
  confirm(self, message) {
    return $object(self).confirm(message);
  },
  prompt(self, message, default_) {
    return $object(self).prompt(message, default_);
  },
  print(self) {
    $object(self).print();
  },
  captureEvents(self) {
    $object(self).captureEvents();
  },
  releaseEvents(self) {
    $object(self).releaseEvents();
  },
  cancelIdleCallback(self, handle) {
    $object(self).cancelIdleCallback(handle);
  },
  origin(self) {
    return $object(self).origin;
  },
  isSecureContext(self) {
    return $object(self).isSecureContext;
  },
  crossOriginIsolated(self) {
    return $object(self).crossOriginIsolated;
  },
  btoa(self, data) {
    return $object(self).btoa(data);
  },
  atob(self, data) {
    return $object(self).atob(data);
  },
  clearTimeout(self, id) {
    $object(self).clearTimeout(id);
  },
  clearInterval(self, id) {
    $object(self).clearInterval(id);
  },
  queueMicrotask(self, callback) {
    $object(self).queueMicrotask($callback(callback, (key) => $callbackExport.call(key)));
  },
  requestAnimationFrame(self, callback) {
    return $object(self).requestAnimationFrame($callback(callback, (key, a0) => $callbackExport.callF64(key, a0)));
  },
  cancelAnimationFrame(self, handle) {
    $object(self).cancelAnimationFrame(handle);
  },
};

export const global = {
  window() {
    return $handle(globalThis);
  },
  document() {
    return $handle(globalThis.document);
  },
};
