[package]
name = "cm-catalog"
description = "A Wasm CM catalog package for those who implement Wasm CM ABI"
repository-directory = "package-cm-catalog"
lib = "src/lib.wado"
# version / repository / namespace / license / authors inherited from [workspace.package]
