[package]
namespace = "wado-lang"
name = "cm-catalog"
version = "0.1.0"

description = "A Wasm CM catalog package for those who implement Wasm CM ABI"
repository = "https://github.com/wado-lang/wado"
repository-directory = "package-cm-catalog"
license = "MIT"
authors = ["FUJI Goro <g.psy.va@gmail.com>"]

lib = "src/lib.wado"
