[package]
namespace = "wado-lang"
name = "cm-catalog"
version = "0.1.0"

description = "A Wasm CM catalog package for those who implement Wasm CM ABI"
url = "https://github.com/wado-lang/wado/tree/main/package-cm-catalog"
license = "MIT"

lib = "src/lib.wado"
