use std::fmt::{self, Write as _};
use std::str::FromStr;

use serde::Deserialize;

/// A parsed `wado.lock` file.
///
/// As of WEP M9, `wado.lock` is dependency-pin-only: it contains
/// `[[package]]` and `[[build-dependency]]` entries but no Kiln
/// generator-cache state. Per-invocation cache state lives next to the
/// generated outputs as `<output_dir>/<primary>.kiln.json`. Older
/// lockfiles that contain `[[generator-cache]]` sections still parse
/// cleanly — the unknown table is ignored — but newly written lockfiles
/// never emit it.
#[derive(Debug, Clone)]
pub struct LockFile {
    /// Lock file format version.
    pub version: u32,
    /// Hash of `[dependencies]` + `[dev-dependencies]` for staleness detection.
    pub deps_hash: String,
    /// Resolved packages.
    pub packages: Vec<LockedPackage>,
    /// Resolved build dependencies (Kiln generator modules).
    pub build_dependencies: Vec<LockedPackage>,
}

/// A single resolved package in the lock file.
#[derive(Debug, Clone)]
pub struct LockedPackage {
    /// Resolved package id (e.g., `"registry+https://wa.dev/docs:regex"`).
    pub id: String,
    /// Exact resolved version.
    pub version: String,
    /// Exact commit SHA (git dependencies only).
    pub resolved_ref: Option<String>,
    /// Content hash (registry dependencies only).
    pub integrity: Option<String>,
    /// Whether this is a dev-only dependency.
    pub dev: bool,
    /// Entry point for `wasi:cli/command`.
    pub command: Option<String>,
    /// Entry point for `wasi:http/service`.
    pub service: Option<String>,
    /// Library entry point.
    pub lib: Option<String>,
    /// Dependencies as `"id@version"` references.
    pub deps: Vec<String>,
}

impl FromStr for LockFile {
    type Err = LockFileError;

    fn from_str(toml_str: &str) -> Result<Self, Self::Err> {
        let raw: RawLockFile = toml::from_str::<RawLockFile>(toml_str)
            .map_err(|e| LockFileError::Toml(e.to_string()))?;

        let version = raw.version.ok_or_else(|| LockFileError::MissingField {
            package_id: "(header)".to_string(),
            field: "version".to_string(),
        })?;

        if version != 1 {
            return Err(LockFileError::InvalidVersion {
                expected: 1,
                found: version,
            });
        }

        let deps_hash = raw.deps_hash.ok_or_else(|| LockFileError::MissingField {
            package_id: "(header)".to_string(),
            field: "deps-hash".to_string(),
        })?;

        let packages = raw
            .package
            .unwrap_or_default()
            .into_iter()
            .map(convert_locked_package)
            .collect::<Result<Vec<_>, _>>()?;

        let build_dependencies = raw
            .build_dependency
            .unwrap_or_default()
            .into_iter()
            .map(convert_locked_package)
            .collect::<Result<Vec<_>, _>>()?;

        // `[[generator-cache]]` sections from older lockfiles are tolerated
        // but ignored — the new design (WEP M9) records that state in
        // `<output_dir>/<primary>.kiln.json`.

        Ok(LockFile {
            version,
            deps_hash,
            packages,
            build_dependencies,
        })
    }
}

impl LockFile {
    /// Serialize to deterministic TOML string.
    ///
    /// Packages are sorted by `id` then `version` for determinism. Build
    /// dependencies appear as `[[build-dependency]]` sections sorted the same
    /// way. As of WEP M9 the lockfile carries no Kiln generator-cache state.
    #[must_use]
    pub fn to_toml(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is auto-generated by wado. Do not edit manually.\n");
        let _ = writeln!(out, "version = {}", self.version);
        let _ = writeln!(out, "deps-hash = {:?}", self.deps_hash);

        let mut sorted: Vec<&LockedPackage> = self.packages.iter().collect();
        sorted.sort_by(|a, b| a.id.cmp(&b.id).then_with(|| a.version.cmp(&b.version)));
        for pkg in sorted {
            write_locked_package(&mut out, pkg, "[[package]]");
        }

        let mut sorted_build: Vec<&LockedPackage> = self.build_dependencies.iter().collect();
        sorted_build.sort_by(|a, b| a.id.cmp(&b.id).then_with(|| a.version.cmp(&b.version)));
        for pkg in sorted_build {
            write_locked_package(&mut out, pkg, "[[build-dependency]]");
        }

        out
    }
}

fn write_locked_package(out: &mut String, pkg: &LockedPackage, header: &str) {
    out.push('\n');
    out.push_str(header);
    out.push('\n');
    let _ = writeln!(out, "id = {:?}", pkg.id);
    let _ = writeln!(out, "version = {:?}", pkg.version);
    if let Some(resolved_ref) = &pkg.resolved_ref {
        let _ = writeln!(out, "resolved-ref = {resolved_ref:?}");
    }
    if let Some(integrity) = &pkg.integrity {
        let _ = writeln!(out, "integrity = {integrity:?}");
    }
    if pkg.dev {
        out.push_str("dev = true\n");
    }
    if let Some(command) = &pkg.command {
        let _ = writeln!(out, "command = {command:?}");
    }
    if let Some(service) = &pkg.service {
        let _ = writeln!(out, "service = {service:?}");
    }
    if let Some(lib) = &pkg.lib {
        let _ = writeln!(out, "lib = {lib:?}");
    }
    if pkg.deps.is_empty() {
        out.push_str("deps = []\n");
    } else {
        out.push_str("deps = [");
        for (i, dep) in pkg.deps.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let _ = write!(out, "{dep:?}");
        }
        out.push_str("]\n");
    }
}

/// Errors from lock file parsing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockFileError {
    /// TOML syntax error.
    Toml(String),
    /// Unsupported lock file version.
    InvalidVersion { expected: u32, found: u32 },
    /// Missing required field.
    MissingField { package_id: String, field: String },
}

impl fmt::Display for LockFileError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LockFileError::Toml(msg) => write!(f, "lock file TOML error: {msg}"),
            LockFileError::InvalidVersion { expected, found } => {
                write!(
                    f,
                    "unsupported lock file version {found} (expected {expected})"
                )
            }
            LockFileError::MissingField { package_id, field } => {
                write!(f, "missing field `{field}` in lock file ({package_id})")
            }
        }
    }
}

impl std::error::Error for LockFileError {}

// --- Raw serde types ---

#[derive(Deserialize)]
struct RawLockFile {
    version: Option<u32>,
    #[serde(rename = "deps-hash")]
    deps_hash: Option<String>,
    package: Option<Vec<RawLockedPackage>>,
    #[serde(rename = "build-dependency")]
    build_dependency: Option<Vec<RawLockedPackage>>,
    // `[[generator-cache]]` from older lockfiles is silently ignored
    // since WEP M9. We accept the table without parsing its rows so old
    // checkouts still load cleanly.
    #[serde(rename = "generator-cache", default)]
    _generator_cache: Option<serde::de::IgnoredAny>,
}

#[derive(Deserialize)]
struct RawLockedPackage {
    id: Option<String>,
    version: Option<String>,
    #[serde(rename = "resolved-ref")]
    resolved_ref: Option<String>,
    integrity: Option<String>,
    dev: Option<bool>,
    command: Option<String>,
    service: Option<String>,
    lib: Option<String>,
    deps: Option<Vec<String>>,
}

fn convert_locked_package(raw: RawLockedPackage) -> Result<LockedPackage, LockFileError> {
    let id = raw.id.ok_or_else(|| LockFileError::MissingField {
        package_id: "(unknown)".to_string(),
        field: "id".to_string(),
    })?;
    let version = raw.version.ok_or_else(|| LockFileError::MissingField {
        package_id: id.clone(),
        field: "version".to_string(),
    })?;
    Ok(LockedPackage {
        id,
        version,
        resolved_ref: raw.resolved_ref,
        integrity: raw.integrity,
        dev: raw.dev.unwrap_or(false),
        command: raw.command,
        service: raw.service,
        lib: raw.lib,
        deps: raw.deps.unwrap_or_default(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const EXAMPLE_LOCK: &str = r#"
# This file is auto-generated by wado. Do not edit manually.
version = 1
deps-hash = "sha256:9f8e7d6c5b4a"

[[package]]
id = "registry+https://wa.dev/docs:regex"
version = "0.1.2"
integrity = "sha256:a1b2c3d4e5f6"
lib = "src/lib.wado"
deps = ["registry+https://wa.dev/docs:regex-utils@0.3.0"]

[[package]]
id = "registry+https://wa.dev/docs:regex-utils"
version = "0.3.0"
integrity = "sha256:f6e5d4c3b2a1"
lib = "src/lib.wado"
deps = []

[[package]]
id = "git+https://github.com/user/router.git/user:router"
version = "1.0.2"
resolved-ref = "abc1234def5678901234567890abcdef12345678"
lib = "src/lib.wado"
deps = ["registry+https://wa.dev/tools:utils@0.5.1"]
"#;

    #[test]
    fn parse_lock_file() {
        let lock: LockFile = EXAMPLE_LOCK.parse().unwrap();
        assert_eq!(lock.version, 1);
        assert_eq!(lock.deps_hash, "sha256:9f8e7d6c5b4a");
        assert_eq!(lock.packages.len(), 3);

        let regex = &lock.packages[0];
        assert_eq!(regex.id, "registry+https://wa.dev/docs:regex");
        assert_eq!(regex.version, "0.1.2");
        assert_eq!(regex.integrity.as_deref(), Some("sha256:a1b2c3d4e5f6"));
        assert!(!regex.dev);
        assert_eq!(regex.deps.len(), 1);

        let router = &lock.packages[2];
        assert!(router.resolved_ref.is_some());
        assert!(router.integrity.is_none());
    }

    #[test]
    fn roundtrip() {
        let lock: LockFile = EXAMPLE_LOCK.parse().unwrap();
        let serialized = lock.to_toml();
        let reparsed: LockFile = serialized.parse().unwrap();
        assert_eq!(reparsed.version, lock.version);
        assert_eq!(reparsed.deps_hash, lock.deps_hash);
        assert_eq!(reparsed.packages.len(), lock.packages.len());
    }

    #[test]
    fn invalid_version() {
        let toml = r#"
version = 99
deps-hash = "sha256:abc"
"#;
        let err = toml.parse::<LockFile>().unwrap_err();
        assert!(matches!(
            err,
            LockFileError::InvalidVersion {
                expected: 1,
                found: 99
            }
        ));
    }

    #[test]
    fn dev_dep_flag() {
        let toml = r#"
version = 1
deps-hash = "sha256:abc"

[[package]]
id = "git+https://gitlab.com/user/bench.git/bench-tool"
version = "0.1.0"
resolved-ref = "def5678901234567890abcdef12345678abc1234d"
dev = true
command = "src/main.wado"
deps = []
"#;
        let lock: LockFile = toml.parse().unwrap();
        assert!(lock.packages[0].dev);
        assert_eq!(lock.packages[0].command.as_deref(), Some("src/main.wado"));
    }

    #[test]
    fn deterministic_output() {
        let lock = LockFile {
            version: 1,
            deps_hash: "sha256:test".to_string(),
            packages: vec![
                LockedPackage {
                    id: "registry+https://wa.dev/z:last".to_string(),
                    version: "1.0.0".to_string(),
                    resolved_ref: None,
                    integrity: Some("sha256:zzz".to_string()),
                    dev: false,
                    command: None,
                    service: None,
                    lib: Some("src/lib.wado".to_string()),
                    deps: vec![],
                },
                LockedPackage {
                    id: "registry+https://wa.dev/a:first".to_string(),
                    version: "0.1.0".to_string(),
                    resolved_ref: None,
                    integrity: Some("sha256:aaa".to_string()),
                    dev: false,
                    command: None,
                    service: None,
                    lib: Some("src/lib.wado".to_string()),
                    deps: vec![],
                },
            ],
            build_dependencies: vec![],
        };
        let output = lock.to_toml();
        let pos_a = output.find("a:first").unwrap();
        let pos_z = output.find("z:last").unwrap();
        assert!(pos_a < pos_z, "packages should be sorted by id");
    }

    const EXAMPLE_KILN_LOCK: &str = r#"
version = 1
deps-hash = "sha256:9f8e7d6c5b4a"

[[package]]
id = "registry+https://wa.dev/docs:regex"
version = "0.1.2"
integrity = "sha256:aaa"
lib = "src/lib.wado"
deps = []

[[build-dependency]]
id = "registry+https://wa.dev/tools:protoc-gen"
version = "2.3.0"
integrity = "sha256:bbb"
lib = "src/lib.wado"
deps = []

[[build-dependency]]
id = "registry+https://wa.dev/tools:antlr-gen"
version = "1.0.0"
integrity = "sha256:ccc"
lib = "src/lib.wado"
deps = []

[[generator-cache]]
invocation = "proto-greeter"
generator = "tools:protoc-gen@2.3.0"
primary = { path = "schemas/greeter.proto", hash = "sha256:schema1" }
options-hash = "sha256:opt1"
inputs = [
    { path = "schemas/common.proto", hash = "sha256:schema2" },
]
reads = [
    { path = "schemas/imported.proto", hash = "sha256:read1" },
    { path = "schemas/shared.proto", hash = "sha256:read2" },
]
outputs = [
    { path = "build/kiln/proto-greeter/greeter.wado", hash = "sha256:out1", entry = true },
    { path = "build/kiln/proto-greeter/types.wado", hash = "sha256:out2", entry = false },
]

[[generator-cache]]
invocation = "antlr-lang"
generator = "tools:antlr-gen@1.0.0"
primary = { path = "grammars/lang.g4", hash = "sha256:schema3" }
options-hash = "sha256:opt2"
inputs = []
outputs = [
    { path = "build/kiln/antlr-lang/parser.wado", hash = "sha256:out3", entry = true },
]
"#;

    #[test]
    fn parse_kiln_sections() {
        // Lockfile retains [[build-dependency]] only. Old [[generator-cache]]
        // sections are accepted for backward compatibility but yield no
        // observable state on `LockFile` (WEP M9).
        let lock: LockFile = EXAMPLE_KILN_LOCK.parse().unwrap();
        assert_eq!(lock.build_dependencies.len(), 2);

        let protoc = lock
            .build_dependencies
            .iter()
            .find(|p| p.id.contains("protoc-gen"))
            .unwrap();
        assert_eq!(protoc.version, "2.3.0");
    }

    #[test]
    fn roundtrip_drops_legacy_generator_cache() {
        let lock: LockFile = EXAMPLE_KILN_LOCK.parse().unwrap();
        let serialized = lock.to_toml();
        // The new serializer never emits [[generator-cache]] rows.
        assert!(
            !serialized.contains("[[generator-cache]]"),
            "to_toml() must not emit legacy [[generator-cache]] sections; got:\n{serialized}"
        );
        let reparsed: LockFile = serialized.parse().unwrap();
        assert_eq!(reparsed.build_dependencies.len(), 2);
    }

    #[test]
    fn deterministic_build_dependency_ordering() {
        let lock = LockFile {
            version: 1,
            deps_hash: "sha256:test".to_string(),
            packages: vec![],
            build_dependencies: vec![
                LockedPackage {
                    id: "registry+https://wa.dev/tools:z-gen".to_string(),
                    version: "1.0.0".to_string(),
                    resolved_ref: None,
                    integrity: Some("sha256:zzz".to_string()),
                    dev: false,
                    command: None,
                    service: None,
                    lib: Some("src/lib.wado".to_string()),
                    deps: vec![],
                },
                LockedPackage {
                    id: "registry+https://wa.dev/tools:a-gen".to_string(),
                    version: "0.1.0".to_string(),
                    resolved_ref: None,
                    integrity: Some("sha256:aaa".to_string()),
                    dev: false,
                    command: None,
                    service: None,
                    lib: Some("src/lib.wado".to_string()),
                    deps: vec![],
                },
            ],
        };
        let output = lock.to_toml();
        let a_bd = output.find("tools:a-gen").unwrap();
        let z_bd = output.find("tools:z-gen").unwrap();
        assert!(a_bd < z_bd, "build-dependencies should be sorted by id");
    }
}
