; Syntax-highlight query for SQLite.g4 (Gale highlights.scm subset).
; Captures use the tree-sitter standard vocabulary; each becomes a CSS class.
; Named tokens (KEYWORD/LITERAL/COMMENT) are matched by lexer-rule name;
; punctuation and operators appear as inline literals, matched by text.

; Literals and comments
(STRING_LITERAL) @string
(BLOB_LITERAL) @string
(NUMERIC_LITERAL) @number
(SINGLE_LINE_COMMENT) @comment
(MULTILINE_COMMENT) @comment
(BIND_PARAMETER) @variable.parameter

; Punctuation
"(" @punctuation.bracket
")" @punctuation.bracket
";" @punctuation.delimiter
"." @punctuation.delimiter
"," @punctuation.delimiter

; Operators
"=" @operator
"||" @operator
"*" @operator
"/" @operator
"%" @operator
"+" @operator
"-" @operator
"<<" @operator
">>" @operator
"&" @operator
"|" @operator
"<" @operator
"<=" @operator
">" @operator
">=" @operator
"==" @operator
"!=" @operator
"<>" @operator
"~" @operator

; Keywords
(K_ABORT) @keyword
(K_ACTION) @keyword
(K_ADD) @keyword
(K_AFTER) @keyword
(K_ALL) @keyword
(K_ALTER) @keyword
(K_ANALYZE) @keyword
(K_AND) @keyword
(K_AS) @keyword
(K_ASC) @keyword
(K_ATTACH) @keyword
(K_AUTOINCREMENT) @keyword
(K_BEFORE) @keyword
(K_BEGIN) @keyword
(K_BETWEEN) @keyword
(K_BY) @keyword
(K_CASCADE) @keyword
(K_CASE) @keyword
(K_CAST) @keyword
(K_CHECK) @keyword
(K_COLLATE) @keyword
(K_COLUMN) @keyword
(K_COMMIT) @keyword
(K_CONFLICT) @keyword
(K_CONSTRAINT) @keyword
(K_CREATE) @keyword
(K_CROSS) @keyword
(K_CURRENT_DATE) @keyword
(K_CURRENT_TIME) @keyword
(K_CURRENT_TIMESTAMP) @keyword
(K_DATABASE) @keyword
(K_DEFAULT) @keyword
(K_DEFERRABLE) @keyword
(K_DEFERRED) @keyword
(K_DELETE) @keyword
(K_DESC) @keyword
(K_DETACH) @keyword
(K_DISTINCT) @keyword
(K_DROP) @keyword
(K_EACH) @keyword
(K_ELSE) @keyword
(K_END) @keyword
(K_ESCAPE) @keyword
(K_EXCEPT) @keyword
(K_EXCLUSIVE) @keyword
(K_EXISTS) @keyword
(K_EXPLAIN) @keyword
(K_FAIL) @keyword
(K_FOR) @keyword
(K_FOREIGN) @keyword
(K_FROM) @keyword
(K_FULL) @keyword
(K_GLOB) @keyword
(K_GROUP) @keyword
(K_HAVING) @keyword
(K_IF) @keyword
(K_IGNORE) @keyword
(K_IMMEDIATE) @keyword
(K_IN) @keyword
(K_INDEX) @keyword
(K_INDEXED) @keyword
(K_INITIALLY) @keyword
(K_INNER) @keyword
(K_INSERT) @keyword
(K_INSTEAD) @keyword
(K_INTERSECT) @keyword
(K_INTO) @keyword
(K_IS) @keyword
(K_ISNULL) @keyword
(K_JOIN) @keyword
(K_KEY) @keyword
(K_LEFT) @keyword
(K_LIKE) @keyword
(K_LIMIT) @keyword
(K_MATCH) @keyword
(K_NATURAL) @keyword
(K_NO) @keyword
(K_NOT) @keyword
(K_NOTNULL) @keyword
(K_NULL) @keyword
(K_OF) @keyword
(K_OFFSET) @keyword
(K_ON) @keyword
(K_OR) @keyword
(K_ORDER) @keyword
(K_OUTER) @keyword
(K_PLAN) @keyword
(K_PRAGMA) @keyword
(K_PRIMARY) @keyword
(K_QUERY) @keyword
(K_RAISE) @keyword
(K_RECURSIVE) @keyword
(K_REFERENCES) @keyword
(K_REGEXP) @keyword
(K_REINDEX) @keyword
(K_RELEASE) @keyword
(K_RENAME) @keyword
(K_REPLACE) @keyword
(K_RESTRICT) @keyword
(K_RIGHT) @keyword
(K_ROLLBACK) @keyword
(K_ROW) @keyword
(K_SAVEPOINT) @keyword
(K_SELECT) @keyword
(K_SET) @keyword
(K_TABLE) @keyword
(K_TEMP) @keyword
(K_TEMPORARY) @keyword
(K_THEN) @keyword
(K_TO) @keyword
(K_TRANSACTION) @keyword
(K_TRIGGER) @keyword
(K_UNION) @keyword
(K_UNIQUE) @keyword
(K_UPDATE) @keyword
(K_USING) @keyword
(K_VACUUM) @keyword
(K_VALUES) @keyword
(K_VIEW) @keyword
(K_VIRTUAL) @keyword
(K_WHEN) @keyword
(K_WHERE) @keyword
(K_WITH) @keyword
(K_WITHOUT) @keyword
