//! The value trait resolution answers questions about. An id is a plain index,
//! so a test writes the program it needs rather than compiling source.

use crate::hashmap::IndexMap;

/// A type declaration — a struct, variant, enum, flags, newtype, resource, or
/// builtin.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct TypeDeclId(pub u32);

/// A trait declaration. Two same-named traits from different modules are two
/// ids, which is what keeps them distinct everywhere the order runs.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct TraitDeclId(pub u32);

/// An `impl` block.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct ImplId(pub u32);

/// A type as selection reads it.
///
/// Two impls whose targets are equal here are two impls of one `(Trait, Type)`
/// pair: a parameter is its position, so `impl<T> Tag for Box_<T>` and
/// `impl<U> Tag for Box_<U>` are the same target, while
/// `impl Tag for Box_<i32>` is a different one.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum SolverType {
    /// A declared type at its type arguments: `Point`, `Box_<i32>`.
    Decl(TypeDeclId, Vec<SolverType>),
    /// One of the impl's own type parameters, by position.
    Param(u32),
    /// One of the impl's own variadic type packs, by position — the `[..T]` an
    /// impl target may be.
    Pack(u32),
    Ref {
        is_mut: bool,
        inner: Box<SolverType>,
    },
    Tuple(Vec<SolverType>),
}

/// An associated type of a trait: `Mul::Output`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct AssocId(pub u32);

/// What a bound says an associated type must be: the `Output = T` in
/// `impl<T: Mul<Output = T>> Product for T`. The impl answering `T: Mul` must
/// bind `Output` to `ty`, spelled with the pinning impl's own parameters.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct Pin {
    pub trait_: TraitDeclId,
    pub assoc: AssocId,
    pub ty: SolverType,
}

impl SolverType {
    /// Whether a [`Param`](Self::Param) or [`Pack`](Self::Pack) in `self`
    /// satisfies `pred`.
    #[must_use]
    pub fn mentions(&self, pred: &dyn Fn(&Self) -> bool) -> bool {
        match self {
            Self::Param(_) | Self::Pack(_) => pred(self),
            Self::Decl(_, inner) | Self::Tuple(inner) => inner.iter().any(|t| t.mentions(pred)),
            Self::Ref { inner, .. } => inner.mentions(pred),
        }
    }

    /// `self` with each parameter and pack replaced by `arg` at its position;
    /// `None` where `arg` has none for one.
    #[must_use]
    pub fn map_params(&self, arg: &dyn Fn(u32) -> Option<Self>) -> Option<Self> {
        let each = |inner: &[Self]| -> Option<Vec<Self>> {
            inner.iter().map(|t| t.map_params(arg)).collect()
        };
        Some(match self {
            Self::Param(index) | Self::Pack(index) => arg(*index)?,
            Self::Decl(head, inner) => Self::Decl(*head, each(inner)?),
            Self::Tuple(inner) => Self::Tuple(each(inner)?),
            Self::Ref { is_mut, inner } => Self::Ref {
                is_mut: *is_mut,
                inner: Box::new(inner.map_params(arg)?),
            },
        })
    }
}

/// One of an impl's type parameters.
#[derive(Clone, PartialEq, Eq, Hash, Debug, Default)]
pub struct ParamDef {
    pub bounds: Vec<TraitDeclId>,
    pub pins: Vec<Pin>,
}

impl ParamDef {
    #[must_use]
    pub fn bounded(bounds: Vec<TraitDeclId>) -> Self {
        Self {
            bounds,
            pins: Vec::new(),
        }
    }
}

/// An `impl` block, reduced to what the rules read.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct ImplDef {
    /// The trait it implements; `None` for an inherent impl.
    pub trait_: Option<TraitDeclId>,
    /// The trait's own type arguments — `[i32]` for `impl Conv<i32> for X`.
    pub trait_args: Vec<SolverType>,
    pub target: SolverType,
    /// The impl's type parameters, in declaration order. [`SolverType::Param`]
    /// and [`SolverType::Pack`] index into this.
    pub params: Vec<ParamDef>,
    pub origin: ImplOrigin,
}

/// Where an impl came from, which decides whether an answer through it owes a
/// body.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum ImplOrigin {
    /// Written in source, or supplied by the compiler for a primitive. Provides
    /// its own body.
    Written,
    /// Generated by [`derive`](super::derive) for a declaration whose members
    /// satisfy the trait. Answering through it owes the derived body.
    Derived,
    /// `impl Tr for T;` — a demand for the derived body and a conformance check
    /// on it (WEP 2026-06-25). Answering through it owes the body; it provides
    /// none, so it is not one of the impls a pair may have only one of.
    Marker,
}

/// A module, as the asking side of a question.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct ModuleId(pub u32);

/// The default a trait's type parameter declares — the `Self` in
/// `trait Mul<Rhs = Self>`.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum ArgDefault {
    /// `= Self`: the implementing type.
    SelfType,
    Type(SolverType),
    /// A default the lowering cannot spell. Nothing restates it, so an impl
    /// writing that argument answers no bare bound.
    Opaque,
}

/// How a reference answers a bound its pointee holds.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum RefRule {
    /// `&T` holds the bound when `T` does, by auto-deref at the call.
    #[default]
    Inherits,
    /// `&T` holds it of itself — `Eq`, which compares references by identity.
    Always,
    /// `&T` never inherits it: `Ord`, or a trait with a receiverless method
    /// naming `Self`, which forwarding cannot supply.
    Never,
}

/// A trait declaration, reduced to what the rules read.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub struct TraitDef {
    /// The traits an implementor must also implement, so a bound naming this
    /// one answers for them too.
    pub supertraits: Vec<TraitDeclId>,
    /// Holds of every type before any body exists — `Inspect`. The unbounded
    /// blanket that would say so is rejected, so the trait says it itself.
    pub holds_for_all: bool,
    pub on_ref: RefRule,
    /// Per type parameter, its declared default, if any. A bound spells no
    /// arguments (WEP 2026-07-31), so it asks for the trait at its defaults,
    /// and an impl whose written arguments say otherwise does not answer it.
    pub arg_defaults: Vec<Option<ArgDefault>>,
}

/// A type declaration, reduced to what `holds` reads of it at a query. Its
/// members arrive at `derive` as a [`Declaration`] and are not kept.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub struct TypeDef {
    /// For a newtype, the base it inherits impls from, spelled with the
    /// newtype's own parameters by position.
    pub newtype_base: Option<SolverType>,
}

/// What a declaration looks like to `derive`: the members a structural trait
/// is derived over. A plain `enum` or `flags` has none and derives
/// unconditionally; a newtype is not a declaration here, since it inherits.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Declaration {
    pub id: TypeDeclId,
    /// How many type parameters the declaration takes; a member may mention
    /// them as [`SolverType::Param`] by position.
    pub params: u32,
    /// Every field of a struct, or every payload of a variant.
    pub members: Vec<SolverType>,
    pub module: ModuleId,
}

/// A body the answer depends on: "this type satisfies `Eq`" is also "emit `Eq`
/// for this type". An answer that arrives without its requests loses the body.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct DerivationRequest {
    pub ty: SolverType,
    pub trait_: TraitDeclId,
}

/// A declaration's own reflection kind, stated of the declaration and answering
/// for every instance of it. Its answer owes the body, as a derived impl's does.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub struct Fact {
    /// Where the fact holds. `None` — everywhere. `Some(modules)` — only when
    /// asked from one of them, which is how a `Reflect*` bound's visibility gate
    /// arrives: naming a type is not enumerating it.
    pub visible_from: Option<Vec<ModuleId>>,
}

/// What the solver is asked about (`docs/wep-2026-09-01-trait-resolution.md`,
/// "The solver's input").
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub struct Program {
    /// Insertion order is the order every answer is reported in, so a caller
    /// that builds it deterministically gets deterministic diagnostics.
    pub impls: IndexMap<ImplId, ImplDef>,
    pub traits: IndexMap<TraitDeclId, TraitDef>,
    pub types: IndexMap<TypeDeclId, TypeDef>,
    /// The non-recursive ways a bound holds, keyed by the declaration and the
    /// trait they answer for.
    pub facts: IndexMap<(TypeDeclId, TraitDeclId), Fact>,
    /// Each impl's `type X = …;` bindings, spelled with the impl's own
    /// parameters. What a [`Pin`] is checked against.
    pub assoc_bindings: IndexMap<(ImplId, AssocId), SolverType>,
}

/// The bounds in force where a question was asked.
///
/// A generic body's `T: Tr` holds because its own signature says so, not because
/// any impl exists, so no question is a function of the program alone. Indexed
/// by the position [`SolverType::Param`] carries.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub struct Env {
    pub param_bounds: Vec<Vec<TraitDeclId>>,
}

impl Program {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Add one impl at the next id.
    pub fn push_impl(&mut self, def: ImplDef) -> ImplId {
        let id = ImplId(
            u32::try_from(self.impls.len()).expect("a program declares fewer than 2^32 impls"),
        );
        let declared = |p: &SolverType| match p {
            SolverType::Param(index) | SolverType::Pack(index) => {
                (*index as usize) < def.params.len()
            }
            SolverType::Decl(..) | SolverType::Tuple(_) | SolverType::Ref { .. } => true,
        };
        let undeclared = |ty: &SolverType| ty.mentions(&|p| !declared(p));
        assert!(
            !undeclared(&def.target)
                && !def.trait_args.iter().any(undeclared)
                && !def
                    .params
                    .iter()
                    .flat_map(|p| &p.pins)
                    .any(|pin| undeclared(&pin.ty)),
            "{id:?} mentions a parameter it does not declare: {def:?}"
        );
        assert!(self.impls.insert(id, def).is_none());
        id
    }

    /// The traits a bound on `trait_` answers for: itself and its supertraits,
    /// transitively. A cycle among supertraits is rejected where the traits are
    /// declared; the walk refuses to hang on one regardless.
    pub(super) fn bound_reaches(&self, bound: TraitDeclId, wanted: TraitDeclId) -> bool {
        let mut stack = vec![bound];
        let mut seen: Vec<TraitDeclId> = Vec::new();
        while let Some(next) = stack.pop() {
            if next == wanted {
                return true;
            }
            if seen.contains(&next) {
                continue;
            }
            seen.push(next);
            if let Some(def) = self.traits.get(&next) {
                stack.extend(def.supertraits.iter().copied());
            }
        }
        false
    }
}
