//! Integration tests for `Engine`'s consume-only Kiln support.
//!
//! Pins the consume-only contract from WEP 2026-04-12 §"Consume-only
//! mode". The consume-only host cannot run the generator,
//! so it cannot re-derive any of the recorded hashes; strict cache
//! validation there only makes the redirect silently die and breaks
//! every query. Consume-only therefore **trusts the on-disk artifact**:
//!
//! - **Artifact present** — `<output_dir>/<primary>.kiln.json` records
//!   an entry output that still exists on disk. The redirect from
//!   `use { ... } from "./schema.g4"` to that generated `.wado` fires
//!   and `Engine::diagnostics` emits no warning, regardless of whether
//!   the schema, options, generator identity, or the generated bytes
//!   themselves have drifted since generation.
//! - **No usable artifact** — no metadata, no entry output recorded,
//!   or the recorded entry output is missing / escapes the workspace.
//!   `Engine::diagnostics` surfaces a `KilnStaleCache` warning, the
//!   redirect does *not* fire, and the LSP writes nothing back to
//!   `<output_dir>` (a follow-up `wado compile` natively refreshes it).
//!
//! `wado check` (native, runtime-backed) remains the gate that catches
//! drift between a committed generated `.wado` and what the generator
//! would produce now; consume-only intentionally does not duplicate it.
//!
//! The fixture is built programmatically inside a `tempdir()` so the
//! test owns every byte that contributes to a cache hash. Committed
//! fixtures would force us to re-encode hashes whenever the schema
//! body changes.

use std::path::Path;

use wado_compiler::kiln::metadata::{
    FileHash, METADATA_VERSION, Metadata, OutputEntry, metadata_filename,
};
use wado_compiler::kiln::{content_hash, hex_digest};
use wado_lsp::{Engine, FilesystemCompilerHost, Severity};

const SCHEMA_BODY: &str = "// dummy calc grammar — body content is irrelevant\n";
const GENERATED_BODY: &str = "#![generated(by = \"fake:gen@0.1\", sources = [\"grammars/calc.g4\"])]\n\
     pub fn parse() -> i32 { return 42; }\n";

/// The `use … with { generator }` clause, as written wherever it lives.
const CLAUSE: &str = "use { parse } from \"./grammars/calc.g4\" with {\n    \
     generator: {\n        \
     module: \"fake:gen@0.1\",\n        \
     output_dir: \"./tests/generated\",\n    \
     },\n\
     };\n";

fn entry_source() -> String {
    format!("{CLAUSE}fn run() {{\n    let _x = parse();\n}}\n")
}

/// The entry when the clause lives one module deeper: it imports the
/// re-export instead of declaring the clause itself.
fn importer_entry_source() -> String {
    "use { parse } from \"./lib.wado\";\nfn run() {\n    let _x = parse();\n}\n".to_string()
}

/// The imported module that declares the clause and re-exports its symbol.
fn clause_module_source() -> String {
    format!("pub {CLAUSE}")
}

fn hex_sha256(bytes: &[u8]) -> String {
    hex_digest(&content_hash(bytes))
}

struct Fixture {
    root: tempfile::TempDir,
    entry_uri: String,
    entry_text: String,
}

/// Knobs the builder consults to materialize the workspace state. Each
/// scenario flips exactly the bytes (or metadata fields) it needs to
/// exercise; defaults give a clean cache hit.
struct FixtureSpec<'a> {
    /// Bytes the user is currently looking at. The metadata pins
    /// `SCHEMA_BODY`'s hash, so passing anything else simulates drift.
    schema_on_disk: &'a str,
    /// Bytes of the generated `.wado` on disk. The metadata always
    /// pins `GENERATED_BODY`'s hash; passing anything else simulates a
    /// hand-edit (hit-but-modified).
    generated_on_disk: &'a str,
    /// Override the `generator` identity written into metadata.
    /// Defaults to `"fake:gen@0.1"` so it matches what
    /// `generator_identity` derives for the inline `module:`.
    metadata_generator: Option<&'a str>,
    /// Put the clause in `lib.wado`, which the entry imports, instead of
    /// in the entry itself. Kiln's unit is the module, not the entry:
    /// a clause anywhere in the graph must redirect.
    clause_in_imported_module: bool,
}

impl Default for FixtureSpec<'_> {
    fn default() -> Self {
        Self {
            schema_on_disk: SCHEMA_BODY,
            generated_on_disk: GENERATED_BODY,
            metadata_generator: None,
            clause_in_imported_module: false,
        }
    }
}

fn build_fixture(spec: FixtureSpec<'_>) -> Fixture {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();

    std::fs::write(
        root.join("wado.toml"),
        "[package]\nname = \"kiln-lsp-test\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();

    let schema_dir = root.join("grammars");
    std::fs::create_dir_all(&schema_dir).unwrap();
    std::fs::write(schema_dir.join("calc.g4"), spec.schema_on_disk).unwrap();

    let gen_dir = root.join("tests/generated");
    std::fs::create_dir_all(&gen_dir).unwrap();
    std::fs::write(gen_dir.join("calc.wado"), spec.generated_on_disk).unwrap();

    let metadata = Metadata {
        version: METADATA_VERSION,
        invocation: "kiln-test".to_string(),
        generator: spec
            .metadata_generator
            .unwrap_or("fake:gen@0.1")
            .to_string(),
        generator_source_hash: String::new(),
        primary: FileHash {
            path: "grammars/calc.g4".to_string(),
            hash: hex_sha256(SCHEMA_BODY.as_bytes()),
        },
        inputs: Vec::new(),
        // No `OptionsDescriptor` reaches the LSP, so `options_canonical`
        // is empty and its hash is the SHA-256 of an empty input.
        options_hash: hex_sha256(&[]),
        outputs: vec![OutputEntry {
            path: "tests/generated/calc.wado".to_string(),
            hash: hex_sha256(GENERATED_BODY.as_bytes()),
            entry: true,
        }],
    };

    std::fs::write(
        gen_dir.join(metadata_filename("grammars/calc.g4")),
        serde_json::to_string_pretty(&metadata).unwrap(),
    )
    .unwrap();

    let entry_text = if spec.clause_in_imported_module {
        std::fs::write(root.join("lib.wado"), clause_module_source()).unwrap();
        importer_entry_source()
    } else {
        entry_source()
    };
    let entry_path = root.join("main.wado");
    std::fs::write(&entry_path, &entry_text).unwrap();

    Fixture {
        root: tmp,
        entry_uri: format!("file://{}", entry_path.display()),
        entry_text,
    }
}

fn engine_with(fixture: &Fixture) -> (Engine, FilesystemCompilerHost) {
    let host = FilesystemCompilerHost::new(fixture.root.path().to_path_buf());
    let mut engine = Engine::new();
    engine.open_document(&fixture.entry_uri, fixture.entry_text.clone());
    (engine, host)
}

fn has_warning(diags: &[wado_lsp::Diagnostic], code: &str) -> bool {
    diags
        .iter()
        .any(|d| d.severity == Severity::Warning && d.code == code)
}

fn errors(diags: &[wado_lsp::Diagnostic]) -> Vec<&wado_lsp::Diagnostic> {
    diags
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect()
}

/// Assert the redirect fired (so `use { parse }` resolves) with no
/// stale-cache warning. The healthy case for every "artifact present"
/// scenario, whatever drifted around it.
fn assert_redirected_clean(diags: &[wado_lsp::Diagnostic]) {
    assert!(
        !has_warning(diags, "KILN_STALE_CACHE"),
        "consume-only must trust the on-disk artifact, not warn stale, got {diags:#?}",
    );
    assert!(
        errors(diags).is_empty(),
        "the redirect should fire so `parse` resolves, got {:#?}",
        errors(diags),
    );
}

#[test]
fn artifact_present_redirects_without_warning() {
    futures::executor::block_on(async {
        let fixture = build_fixture(FixtureSpec::default());
        let (engine, host) = engine_with(&fixture);

        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert_redirected_clean(&diags);
    });
}

#[test]
fn clause_in_an_imported_module_redirects() {
    futures::executor::block_on(async {
        // Kiln's unit is the module, not the entry: a `with` clause in an
        // imported module produces a generated module for *that* module's
        // imports (WEP 2026-04-12 §"The loader redirect").
        let fixture = build_fixture(FixtureSpec {
            clause_in_imported_module: true,
            ..FixtureSpec::default()
        });
        let (engine, host) = engine_with(&fixture);

        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert_redirected_clean(&diags);
    });
}

#[test]
fn schema_drift_still_redirects() {
    futures::executor::block_on(async {
        // The schema on disk no longer matches the recorded hash. A
        // runtime-backed host would regenerate; consume-only cannot, so
        // it trusts the existing output and redirects anyway.
        let fixture = build_fixture(FixtureSpec {
            schema_on_disk: "// edited grammar — hash will not match\n",
            ..FixtureSpec::default()
        });
        let (engine, host) = engine_with(&fixture);

        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert_redirected_clean(&diags);
    });
}

#[test]
fn consume_only_never_writes_back() {
    futures::executor::block_on(async {
        let fixture = build_fixture(FixtureSpec {
            schema_on_disk: "// edited grammar\n",
            ..FixtureSpec::default()
        });
        let metadata_path = fixture
            .root
            .path()
            .join("tests/generated")
            .join(metadata_filename("grammars/calc.g4"));
        let before = std::fs::read(&metadata_path).unwrap();

        let (engine, host) = engine_with(&fixture);
        let _ = engine.diagnostics(&fixture.entry_uri, &host).await;

        let after = std::fs::read(&metadata_path).unwrap();
        assert_eq!(before, after, "consume-only LSP must not rewrite the cache");
        assert!(
            metadata_check_no_orphan_writes(fixture.root.path()),
            "consume-only LSP must not create stray files under the workspace",
        );
    });
}

#[test]
fn generator_identity_mismatch_still_redirects() {
    futures::executor::block_on(async {
        // The inline `module:` now resolves to a different
        // `generator_identity` than the metadata pinned. A native host
        // would regenerate with the new generator; consume-only trusts
        // whatever output is on disk and redirects.
        let fixture = build_fixture(FixtureSpec {
            metadata_generator: Some("fake:gen@9.9"),
            ..FixtureSpec::default()
        });
        let (engine, host) = engine_with(&fixture);

        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert_redirected_clean(&diags);
    });
}

#[test]
fn output_edited_still_redirects_without_warning() {
    futures::executor::block_on(async {
        // The generated `.wado` was hand-edited after generation.
        // Consume-only honors the edit and redirects; freshness drift
        // is `wado check`'s job, not the editor's.
        let fixture = build_fixture(FixtureSpec {
            generated_on_disk: "#![generated(by = \"fake:gen@0.1\", sources = [\"grammars/calc.g4\"])]\n\
                 pub fn parse() -> i32 { return 99; }\n",
            ..FixtureSpec::default()
        });
        let (engine, host) = engine_with(&fixture);

        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert!(
            !has_warning(&diags, "KILN_GENERATED_MODIFIED"),
            "consume-only no longer hashes outputs, so no modified warning, got {diags:#?}",
        );
        assert_redirected_clean(&diags);
    });
}

#[test]
fn no_metadata_is_stale() {
    futures::executor::block_on(async {
        // Without `<primary>.kiln.json` there is no record of which
        // output is the entry, so consume-only cannot redirect and must
        // point the user at `wado compile`.
        let fixture = build_fixture(FixtureSpec::default());
        std::fs::remove_file(
            fixture
                .root
                .path()
                .join("tests/generated")
                .join(metadata_filename("grammars/calc.g4")),
        )
        .unwrap();

        let (engine, host) = engine_with(&fixture);
        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert!(
            has_warning(&diags, "KILN_STALE_CACHE"),
            "missing metadata must surface as a stale-cache miss, got {diags:#?}",
        );
    });
}

#[test]
fn metadata_with_traversal_paths_is_cache_miss() {
    futures::executor::block_on(async {
        // Build a clean workspace, then rewrite the metadata to point
        // its output at a `..`-prefixed path (a tampered cache file).
        // The LSP must refuse the join — treating it as a cache miss
        // — rather than reading or hashing anything outside
        // `manifest_root`. We also plant a sentinel file outside the
        // workspace to confirm the traversal really would have hit it.
        let fixture = build_fixture(FixtureSpec::default());
        let outside_dir = tempfile::tempdir().unwrap();
        let outside_path = outside_dir.path().join("victim.wado");
        std::fs::write(&outside_path, "pub fn pwned() {}\n").unwrap();

        let metadata_path = fixture
            .root
            .path()
            .join("tests/generated")
            .join(metadata_filename("grammars/calc.g4"));
        let mut metadata: Metadata =
            serde_json::from_str(&std::fs::read_to_string(&metadata_path).unwrap()).unwrap();
        metadata.outputs[0].path = format!(
            "../../{}",
            outside_path
                .strip_prefix(outside_dir.path().parent().unwrap())
                .unwrap()
                .display()
        );
        std::fs::write(
            &metadata_path,
            serde_json::to_string_pretty(&metadata).unwrap(),
        )
        .unwrap();

        let (engine, host) = engine_with(&fixture);
        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert!(
            has_warning(&diags, "KILN_STALE_CACHE"),
            "traversal path must be refused as cache miss, got {diags:#?}",
        );
    });
}

#[test]
fn missing_output_is_cache_miss() {
    futures::executor::block_on(async {
        // Cache says the output exists, but the file is gone.
        // CLI parity: `wado_cli::kiln_driver::cache_matches` treats
        // an unreadable output as a miss; the LSP must do the same
        // rather than redirect into thin air.
        let fixture = build_fixture(FixtureSpec::default());
        std::fs::remove_file(fixture.root.path().join("tests/generated/calc.wado")).unwrap();

        let (engine, host) = engine_with(&fixture);
        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert!(
            has_warning(&diags, "KILN_STALE_CACHE"),
            "missing output must be refused as cache miss, got {diags:#?}",
        );
    });
}

#[test]
fn missing_sibling_output_is_cache_miss() {
    futures::executor::block_on(async {
        // The entry output exists, but metadata also records a non-entry
        // sibling that is absent on disk. The entry module imports its
        // generated siblings by relative path, so a missing sibling would
        // fail the import with an opaque error; refuse the whole redirect and
        // surface the actionable stale-cache hint instead.
        let fixture = build_fixture(FixtureSpec::default());
        let metadata_path = fixture
            .root
            .path()
            .join("tests/generated")
            .join(metadata_filename("grammars/calc.g4"));
        let mut metadata: Metadata =
            serde_json::from_str(&std::fs::read_to_string(&metadata_path).unwrap()).unwrap();
        metadata.outputs.push(OutputEntry {
            path: "tests/generated/helper.wado".to_string(),
            hash: hex_sha256(b"sibling that was never written"),
            entry: false,
        });
        std::fs::write(
            &metadata_path,
            serde_json::to_string_pretty(&metadata).unwrap(),
        )
        .unwrap();

        let (engine, host) = engine_with(&fixture);
        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert!(
            has_warning(&diags, "KILN_STALE_CACHE"),
            "a missing sibling output must be refused as cache miss, got {diags:#?}",
        );
    });
}

#[test]
fn a_directory_in_the_metadata_slot_is_a_cache_miss() {
    futures::executor::block_on(async {
        // Nothing loadable is at the path, so the redirect is refused rather
        // than firing against whatever the directory listing looks like.
        let fixture = build_fixture(FixtureSpec::default());
        let metadata_path = fixture
            .root
            .path()
            .join("tests/generated")
            .join(metadata_filename("grammars/calc.g4"));
        std::fs::remove_file(&metadata_path).unwrap();
        std::fs::create_dir(&metadata_path).unwrap();

        let (engine, host) = engine_with(&fixture);
        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert!(
            has_warning(&diags, "KILN_STALE_CACHE"),
            "an unloadable metadata path must be refused as a cache miss, got {diags:#?}",
        );
    });
}

/// "Not generated yet" and "there but unreadable" have different fixes, so the
/// warning tells them apart. Only the first is reachable without a permission
/// error, which this suite cannot stage as root.
#[test]
fn absent_metadata_reports_no_cache() {
    futures::executor::block_on(async {
        let fixture = build_fixture(FixtureSpec::default());
        std::fs::remove_file(
            fixture
                .root
                .path()
                .join("tests/generated")
                .join(metadata_filename("grammars/calc.g4")),
        )
        .unwrap();

        let (engine, host) = engine_with(&fixture);
        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        let stale = diags
            .iter()
            .find(|d| d.code == "KILN_STALE_CACHE")
            .unwrap_or_else(|| panic!("expected a stale-cache warning, got {diags:#?}"));
        assert!(
            stale.message.contains("no cache at"),
            "an absent cache is the ordinary not-generated-yet case, got {:?}",
            stale.message,
        );
    });
}

#[cfg(unix)]
#[test]
fn symlink_escape_is_cache_miss() {
    futures::executor::block_on(async {
        // Replace the generated output with a symlink that points at
        // a sentinel file outside the workspace. `safe_join`
        // canonicalizes both the joined path and `manifest_root`,
        // so the resolved target must lie under the workspace —
        // anything else is refused as a cache miss.
        let fixture = build_fixture(FixtureSpec::default());
        let outside_dir = tempfile::tempdir().unwrap();
        let outside_file = outside_dir.path().join("victim.wado");
        std::fs::write(&outside_file, "pub fn pwned() -> i32 { return 0; }\n").unwrap();

        let inside = fixture.root.path().join("tests/generated/calc.wado");
        std::fs::remove_file(&inside).unwrap();
        std::os::unix::fs::symlink(&outside_file, &inside).unwrap();

        let (engine, host) = engine_with(&fixture);
        let diags = engine.diagnostics(&fixture.entry_uri, &host).await;

        assert!(
            has_warning(&diags, "KILN_STALE_CACHE"),
            "symlink escape must be refused as cache miss, got {diags:#?}",
        );
    });
}

/// Sanity-check: after a consume-only diagnostic pass the workspace
/// must contain only the files we wrote in `build_fixture`. Catches
/// accidental regressions where the LSP path picks up a CLI-only write
/// helper.
fn metadata_check_no_orphan_writes(root: &Path) -> bool {
    let mut entries: Vec<String> = walk_files(root)
        .into_iter()
        .map(|p| {
            p.strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();
    entries.sort();

    let expected: Vec<String> = vec![
        "grammars/calc.g4".to_string(),
        "main.wado".to_string(),
        "tests/generated/calc.g4.kiln.json".to_string(),
        "tests/generated/calc.wado".to_string(),
        "wado.toml".to_string(),
    ];
    entries == expected
}

fn walk_files(root: &Path) -> Vec<std::path::PathBuf> {
    let mut out = Vec::new();
    walk(root, &mut out);
    out
}

fn walk(dir: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in rd.flatten() {
        let p = entry.path();
        if p.is_dir() {
            walk(&p, out);
        } else {
            out.push(p);
        }
    }
}
