//! Inspect and display synthesis — marker replacement and function body generation.
//!
//! Replaces `builtin::inspect(expr, &mut f)` and `builtin::display(expr, &mut f)`
//! marker calls with concrete formatting code, and generates bodies for
//! `__inspect$TypeName` functions registered by template expansion or markers.
//!
//! - `builtin::inspect` → always generates inspect (debug) output
//! - `builtin::display` → tries Display impl first, falls back to inspect
//!
//! Pipeline position: pre-monomorphize synthesis phase.
//! Inspect/Display trait impls are generated by `synthesis/traits.rs`.
//! This module handles marker replacement and inspect function body generation.
//!
//! See `docs/wep-2026-02-21-inspect-debug-output.md` for design details.

use std::cell::RefCell;
use std::rc::Rc;

use indexmap::{IndexMap, IndexSet};

use crate::name::{LocalMethodName, MethodName, ModuleSource};
use crate::tir::{
    FunctionRef, InlineHint, PrimitiveType, ResolvedType, SubstitutionContext, TirBinaryOp,
    TirBlock, TirExpr, TirExprKind, TirFlags, TirFunction, TirModule, TirParam, TirStmt,
    TirStmtKind, TirTemplatePart, TirUnaryOp, TirVariantDecl, TypeId, TypeTable,
};
use crate::token::Span;

use super::common::synth_span;

/// Replace `builtin::inspect` and `builtin::display` markers in a single module.
pub fn replace_markers_in_module(
    module: &TirModule,
    tt: &Rc<RefCell<TypeTable>>,
    all_modules: &[&TirModule],
    reg: &mut InspectRegistry,
    fmt_type: TypeId,
    module_source: &ModuleSource,
) {
    for func_rc in &module.functions {
        let mut func = func_rc.borrow_mut();
        if let Some(ref mut body) = func.body {
            let closure_sources = collect_closure_sources(body);
            replace_markers_in_block(
                body,
                tt,
                all_modules,
                &closure_sources,
                reg,
                fmt_type,
                module_source,
            );
        }
    }
}

/// Generate bodies for all pending inspect functions in the registry.
///
/// Called after template expansion and marker replacement have registered
/// all needed types.
pub fn generate_pending_inspect_fns(
    reg: &mut InspectRegistry,
    tt: &Rc<RefCell<TypeTable>>,
    all_modules: &[&TirModule],
    fmt_type: TypeId,
    module_source: &ModuleSource,
) {
    while let Some(type_id) = reg.pending.pop() {
        generate_inspect_fn_body(reg, type_id, tt, all_modules, fmt_type, module_source);
    }
}

/// Registry of generated inspect functions, keyed by `TypeId`.
pub struct InspectRegistry {
    functions: IndexMap<TypeId, Rc<RefCell<TirFunction>>>,
    pending: Vec<TypeId>,
}

impl Default for InspectRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl InspectRegistry {
    pub fn new() -> Self {
        Self {
            functions: IndexMap::new(),
            pending: Vec::new(),
        }
    }

    pub fn into_functions(self) -> Vec<Rc<RefCell<TirFunction>>> {
        self.functions.into_values().collect()
    }
}

/// Ensure an inspect function exists for the given type. Returns a reference
/// to the (possibly placeholder) function.
fn ensure_inspect_fn(
    reg: &mut InspectRegistry,
    type_id: TypeId,
    tt: &Rc<RefCell<TypeTable>>,
    fmt_type: TypeId,
) -> Rc<RefCell<TirFunction>> {
    if let Some(func) = reg.functions.get(&type_id) {
        return Rc::clone(func);
    }
    let name = format!("__inspect${}", tt.borrow().type_name(type_id));
    let span = synth_span();
    let func = TirFunction {
        name,
        is_pub: false,
        is_export: false,
        is_async: false,
        type_params: vec![],
        impl_type_params: vec![],
        monomorph_info: None,
        method_info: None,
        params: vec![
            TirParam {
                name: "__val".into(),
                type_id,
                local_index: 0,
                is_mut: false,
                span,
            },
            TirParam {
                name: "__fmt".into(),
                type_id: fmt_type,
                local_index: 1,
                is_mut: false,
                span,
            },
        ],
        return_type: TypeTable::UNIT,
        effects: vec![],
        body: None, // filled in Phase 2
        span,
        local_count: 2,
        local_types: vec![type_id, fmt_type],
        address_taken_locals: IndexSet::new(),
        is_cm_adapter: false,
        inline_hint: InlineHint::Auto,
        comp_features: 0,
        export_name: None,
    };
    let rc = Rc::new(RefCell::new(func));
    reg.functions.insert(type_id, Rc::clone(&rc));
    reg.pending.push(type_id);
    rc
}

/// Public entry point for calling inspect functions from other synthesis phases.
pub fn call_inspect_fn_pub(
    reg: &mut InspectRegistry,
    type_id: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> TirStmt {
    call_inspect_fn(reg, type_id, val, fmt, tt, fmt_type, module_source, span)
}

/// Create a call statement to an inspect function for the given type.
fn call_inspect_fn(
    reg: &mut InspectRegistry,
    type_id: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> TirStmt {
    let func_rc = ensure_inspect_fn(reg, type_id, tt, fmt_type);
    let call = TirExpr::new(
        TirExprKind::Call {
            func: FunctionRef::from_resolved(&func_rc.borrow(), module_source.clone()),
            type_args: vec![],
            args: vec![val, fmt],
            param_is_mut: vec![false, false],
        },
        TypeTable::UNIT,
        span,
    );
    TirStmt::new(TirStmtKind::Expr(call), span)
}

/// Generate the body for an inspect function (Phase 2).
fn generate_inspect_fn_body(
    reg: &mut InspectRegistry,
    type_id: TypeId,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    fmt_type: TypeId,
    module_source: &ModuleSource,
) {
    let span = synth_span();
    let val = TirExpr::new(
        TirExprKind::Local {
            index: 0,
            name: "__val".into(),
        },
        type_id,
        span,
    );
    let fmt = TirExpr::new(
        TirExprKind::Local {
            index: 1,
            name: "__fmt".into(),
        },
        fmt_type,
        span,
    );
    let mut alloc = LocalAlloc {
        next_index: 2,
        new_types: Vec::new(),
    };

    let stmts = synth_body(
        reg,
        type_id,
        val,
        fmt,
        tt,
        mods,
        &mut alloc,
        fmt_type,
        module_source,
        span,
    );

    let func_rc = reg.functions.get(&type_id).unwrap().clone();
    let mut func = func_rc.borrow_mut();
    func.body = Some(TirBlock::new(stmts, span));
    func.local_count = alloc.next_index;
    let mut types = vec![type_id, fmt_type];
    types.extend(alloc.new_types);
    func.local_types = types;
}

/// Tracks local variable allocation during function body generation.
struct LocalAlloc {
    next_index: u32,
    new_types: Vec<TypeId>,
}

impl LocalAlloc {
    fn alloc(&mut self, type_id: TypeId) -> u32 {
        let idx = self.next_index;
        self.next_index += 1;
        self.new_types.push(type_id);
        idx
    }
}

/// Collect closure source texts from Let statements in a function body.
/// Maps `local_index` → `source_text` for closures that have pre-desugar source.
pub fn collect_closure_sources(block: &TirBlock) -> IndexMap<u32, String> {
    let mut map = IndexMap::new();
    collect_closure_sources_block(block, &mut map);
    map
}

fn collect_closure_sources_block(block: &TirBlock, map: &mut IndexMap<u32, String>) {
    for stmt in &block.stmts {
        collect_closure_sources_stmt(stmt, map);
    }
}

fn collect_closure_sources_stmt(stmt: &TirStmt, map: &mut IndexMap<u32, String>) {
    match &stmt.kind {
        TirStmtKind::Let {
            local_index, value, ..
        } => {
            if let Some(text) = extract_closure_source(value) {
                map.insert(*local_index, text);
            }
            collect_closure_sources_expr(value, map);
        }
        TirStmtKind::Expr(e) => collect_closure_sources_expr(e, map),
        TirStmtKind::If {
            then_block,
            else_block,
            ..
        } => {
            collect_closure_sources_block(then_block, map);
            if let Some(b) = else_block {
                collect_closure_sources_block(b, map);
            }
        }
        TirStmtKind::Loop { body } => collect_closure_sources_block(body, map),
        TirStmtKind::IfPattern {
            then_block,
            else_block,
            ..
        } => {
            collect_closure_sources_block(then_block, map);
            if let Some(b) = else_block {
                collect_closure_sources_block(b, map);
            }
        }
        TirStmtKind::LabeledBlock { block, .. } => {
            collect_closure_sources_block(block, map);
        }
        TirStmtKind::LetPattern { value, .. } | TirStmtKind::TaskReturn { value, .. } => {
            collect_closure_sources_expr(value, map);
        }
        _ => {}
    }
}

fn collect_closure_sources_expr(expr: &TirExpr, map: &mut IndexMap<u32, String>) {
    match &expr.kind {
        TirExprKind::Block(block) | TirExprKind::LabeledBlock { block, .. } => {
            collect_closure_sources_block(block, map);
        }
        TirExprKind::If {
            then_branch,
            else_branch,
            ..
        } => {
            collect_closure_sources_block(then_branch, map);
            if let Some(b) = else_branch {
                collect_closure_sources_block(b, map);
            }
        }
        TirExprKind::Closure { body, .. } => {
            collect_closure_sources_expr(body, map);
        }
        _ => {}
    }
}

/// Extract closure source text from an expression.
/// Handles both direct closures and mutable closures wrapped in a Block.
fn extract_closure_source(expr: &TirExpr) -> Option<String> {
    match &expr.kind {
        TirExprKind::Closure {
            source_text: Some(text),
            ..
        } => Some(text.clone()),
        // Mutable closures are wrapped: Block { let __ref_x = &mut x; Closure { ... } }
        TirExprKind::Block(block) => block.stmts.last().and_then(|stmt| {
            if let TirStmtKind::Expr(inner) = &stmt.kind {
                extract_closure_source(inner)
            } else {
                None
            }
        }),
        _ => None,
    }
}

// ─── Phase 1: Replace markers with calls ───

fn replace_markers_in_block(
    block: &mut TirBlock,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    cs: &IndexMap<u32, String>,
    reg: &mut InspectRegistry,
    fmt_type: TypeId,
    module_source: &ModuleSource,
) {
    let mut i = 0;
    while i < block.stmts.len() {
        let marker_kind = if let TirStmtKind::Expr(ref expr) = block.stmts[i].kind {
            marker_kind(expr)
        } else {
            MarkerKind::None
        };

        if matches!(marker_kind, MarkerKind::Inspect | MarkerKind::Display) {
            let stmt = block.stmts.remove(i);
            if let TirStmtKind::Expr(expr) = stmt.kind
                && let TirExprKind::StaticCall { args, .. } = expr.kind
            {
                let mut args = args;
                let fmt_ref = args.pop().unwrap();
                let value_expr = args.pop().unwrap();
                let type_id = value_expr.type_id;
                let span = expr.span;

                let resolved = tt.borrow().get(type_id).clone();

                let new_stmt = if matches!(marker_kind, MarkerKind::Display)
                    && has_display_impl(type_id, tt, mods)
                {
                    // builtin::display with a concrete Display impl — call it directly
                    let mut stmts = display_fmt(type_id, value_expr, fmt_ref, tt, span);
                    let first = stmts.remove(0);
                    // Insert any extra stmts (display_fmt typically returns exactly 1)
                    for (j, s) in stmts.into_iter().enumerate() {
                        block.stmts.insert(i + j, s);
                    }
                    first
                } else if matches!(resolved, ResolvedType::Function { .. }) {
                    // Closure: check Formatter.alternate at runtime to decide
                    // between source text (if available) and signature display.
                    let source = match &value_expr.kind {
                        TirExprKind::Closure {
                            source_text: Some(text),
                            ..
                        } => Some(text.clone()),
                        TirExprKind::Local { index, .. } => cs.get(index).cloned(),
                        _ => None,
                    };
                    if let Some(text) = source {
                        // Generate: if fmt.alternate { write source } else { inspect }
                        let alternate_cond = TirExpr::new(
                            TirExprKind::FieldAccess {
                                expr: Box::new(fmt_ref.clone()),
                                field_index: 3, // alternate field
                                field_name: "alternate".to_string(),
                            },
                            TypeTable::BOOL,
                            span,
                        );
                        let then_stmt = ws(&text, fmt_ref.clone(), tt, span);
                        let else_stmt = call_inspect_fn(
                            reg,
                            type_id,
                            value_expr,
                            fmt_ref,
                            tt,
                            fmt_type,
                            module_source,
                            span,
                        );
                        TirStmt::new(
                            TirStmtKind::If {
                                condition: alternate_cond,
                                then_block: TirBlock::new(vec![then_stmt], span),
                                else_block: Some(TirBlock::new(vec![else_stmt], span)),
                            },
                            span,
                        )
                    } else {
                        call_inspect_fn(
                            reg,
                            type_id,
                            value_expr,
                            fmt_ref,
                            tt,
                            fmt_type,
                            module_source,
                            span,
                        )
                    }
                } else {
                    call_inspect_fn(
                        reg,
                        type_id,
                        value_expr,
                        fmt_ref,
                        tt,
                        fmt_type,
                        module_source,
                        span,
                    )
                };
                block.stmts.insert(i, new_stmt);
            }
        } else {
            walk_stmt(
                &mut block.stmts[i],
                tt,
                mods,
                cs,
                reg,
                fmt_type,
                module_source,
            );
        }
        i += 1;
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum MarkerKind {
    None,
    Inspect,
    Display,
}

fn marker_kind(expr: &TirExpr) -> MarkerKind {
    if let TirExprKind::StaticCall { func, .. } = &expr.kind {
        let name = func.name.clone();
        if name == "builtin::inspect" {
            MarkerKind::Inspect
        } else if name == "builtin::display" {
            MarkerKind::Display
        } else {
            MarkerKind::None
        }
    } else {
        MarkerKind::None
    }
}

/// Check if a concrete type has a `Display::fmt` implementation available
/// in any of the loaded TIR modules.
///
/// Uses `try_borrow()` to avoid panicking when a function is already mutably
/// borrowed (the current function being processed in the outer loop).
fn has_display_impl(type_id: TypeId, tt: &Rc<RefCell<TypeTable>>, mods: &[&TirModule]) -> bool {
    let base = tt.borrow().get_ultimate_base_type(type_id);
    let type_name = tt.borrow().mangle_type_name(base);
    let expected_name = MethodName::format_local(&type_name, Some("Display"), "fmt");
    for m in mods {
        for f in &m.functions {
            if let Ok(func) = f.try_borrow()
                && func.name == expected_name
            {
                return true;
            }
        }
    }
    false
}

fn walk_stmt(
    stmt: &mut TirStmt,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    cs: &IndexMap<u32, String>,
    reg: &mut InspectRegistry,
    fmt_type: TypeId,
    ms: &ModuleSource,
) {
    match &mut stmt.kind {
        TirStmtKind::Expr(e) => walk_expr(e, tt, mods, cs, reg, fmt_type, ms),
        TirStmtKind::Let { value, .. } => walk_expr(value, tt, mods, cs, reg, fmt_type, ms),
        TirStmtKind::Return { value: Some(e) } | TirStmtKind::Break { value: Some(e), .. } => {
            walk_expr(e, tt, mods, cs, reg, fmt_type, ms);
        }
        TirStmtKind::If {
            condition,
            then_block,
            else_block,
        } => {
            walk_expr(condition, tt, mods, cs, reg, fmt_type, ms);
            replace_markers_in_block(then_block, tt, mods, cs, reg, fmt_type, ms);
            if let Some(eb) = else_block {
                replace_markers_in_block(eb, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirStmtKind::Loop { body } => {
            replace_markers_in_block(body, tt, mods, cs, reg, fmt_type, ms);
        }
        TirStmtKind::IfPattern {
            scrutinee,
            then_block,
            else_block,
            ..
        } => {
            walk_expr(scrutinee, tt, mods, cs, reg, fmt_type, ms);
            replace_markers_in_block(then_block, tt, mods, cs, reg, fmt_type, ms);
            if let Some(eb) = else_block {
                replace_markers_in_block(eb, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirStmtKind::LetPattern { value, .. } => {
            walk_expr(value, tt, mods, cs, reg, fmt_type, ms);
        }
        _ => {}
    }
}

fn walk_expr(
    expr: &mut TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    cs: &IndexMap<u32, String>,
    reg: &mut InspectRegistry,
    fmt_type: TypeId,
    ms: &ModuleSource,
) {
    match &mut expr.kind {
        TirExprKind::Block(b) | TirExprKind::LabeledBlock { block: b, .. } => {
            replace_markers_in_block(b, tt, mods, cs, reg, fmt_type, ms);
        }
        TirExprKind::If {
            condition,
            then_branch,
            else_branch,
        } => {
            walk_expr(condition, tt, mods, cs, reg, fmt_type, ms);
            replace_markers_in_block(then_branch, tt, mods, cs, reg, fmt_type, ms);
            if let Some(eb) = else_branch {
                replace_markers_in_block(eb, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirExprKind::Match { expr: s, arms } => {
            walk_expr(s, tt, mods, cs, reg, fmt_type, ms);
            for arm in arms {
                walk_expr(&mut arm.body, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirExprKind::Call { args, .. } | TirExprKind::StaticCall { args, .. } => {
            for a in args {
                walk_expr(a, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirExprKind::MethodCall { receiver, args, .. } => {
            walk_expr(receiver, tt, mods, cs, reg, fmt_type, ms);
            for a in args {
                walk_expr(a, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirExprKind::Binary { left, right, .. } => {
            walk_expr(left, tt, mods, cs, reg, fmt_type, ms);
            walk_expr(right, tt, mods, cs, reg, fmt_type, ms);
        }
        TirExprKind::Unary { expr: inner, .. }
        | TirExprKind::Cast { expr: inner, .. }
        | TirExprKind::FieldAccess { expr: inner, .. }
        | TirExprKind::VariantTag { expr: inner }
        | TirExprKind::VariantTest { expr: inner, .. }
        | TirExprKind::VariantPayload { expr: inner, .. } => {
            walk_expr(inner, tt, mods, cs, reg, fmt_type, ms);
        }
        TirExprKind::Assign { target, value } => {
            walk_expr(target, tt, mods, cs, reg, fmt_type, ms);
            walk_expr(value, tt, mods, cs, reg, fmt_type, ms);
        }
        TirExprKind::Index {
            expr: e,
            index: idx,
        } => {
            walk_expr(e, tt, mods, cs, reg, fmt_type, ms);
            walk_expr(idx, tt, mods, cs, reg, fmt_type, ms);
        }
        TirExprKind::StructLiteral { fields, .. } => {
            for f in fields {
                walk_expr(&mut f.value, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirExprKind::TupleLiteral { elements } => {
            for e in elements {
                walk_expr(e, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirExprKind::Closure { body, .. } => {
            walk_expr(body, tt, mods, cs, reg, fmt_type, ms);
        }
        TirExprKind::IndirectCall { callee, args } => {
            walk_expr(callee, tt, mods, cs, reg, fmt_type, ms);
            for a in args {
                walk_expr(a, tt, mods, cs, reg, fmt_type, ms);
            }
        }
        TirExprKind::TemplateString { parts } => {
            for part in parts {
                if let TirTemplatePart::Interpolation { expr: inner, .. } = part {
                    walk_expr(inner, tt, mods, cs, reg, fmt_type, ms);
                }
            }
        }
        _ => {}
    }
}

// ─── Phase 2: Generate inspect function bodies ───

/// Dispatch to the appropriate synth_* based on type.
fn synth_body(
    reg: &mut InspectRegistry,
    type_id: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    alloc: &mut LocalAlloc,
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let resolved = tt.borrow().get(type_id).clone();

    match resolved {
        ResolvedType::Primitive(PrimitiveType::Char) => {
            let mut s = Vec::new();
            s.push(wc('\'', fmt.clone(), span));
            s.extend(display_fmt(type_id, val, fmt.clone(), tt, span));
            s.push(wc('\'', fmt, span));
            s
        }
        ResolvedType::Primitive(_) => display_fmt(type_id, val, fmt, tt, span),
        ResolvedType::Unit => {
            vec![ws("()", fmt, tt, span)]
        }
        ResolvedType::Struct {
            ref name,
            module_source: ref ms,
            ref base_name,
            is_monomorphized,
        } => {
            let n = name.clone();
            let ms = ms.clone();
            if n == "String" && ms == ModuleSource::string() {
                synth_string(val, fmt, tt, span)
            } else if is_monomorphized {
                // Monomorphized struct (e.g., "Box<i32>").
                // Use base_name for display, monomorphized name for field lookup.
                let display_name = base_name.as_deref().unwrap_or(&n);
                synth_monomorphized_struct(
                    reg,
                    display_name,
                    &n,
                    val,
                    fmt,
                    tt,
                    mods,
                    fmt_type,
                    module_source,
                    span,
                )
            } else {
                synth_struct(reg, &n, val, fmt, tt, mods, fmt_type, module_source, span)
            }
        }
        ResolvedType::Enum { ref name, .. } => {
            let n = name.clone();
            synth_enum(&n, type_id, val, fmt, tt, mods, span)
        }
        ResolvedType::Tuple(ref elems) => {
            let e = elems.clone();
            synth_tuple(reg, &e, val, fmt, tt, fmt_type, module_source, span)
        }
        // Option<T>: synthesize inspect using variant operations (SubtypeHierarchy)
        ResolvedType::GenericInstance {
            ref name,
            ref type_args,
            ..
        } if name == "Option" && type_args.len() == 1 => {
            let inner = type_args[0];
            synth_option_variant(
                reg,
                inner,
                val,
                fmt,
                tt,
                mods,
                fmt_type,
                module_source,
                span,
            )
        }
        ResolvedType::GenericInstance {
            ref name,
            ref type_args,
            ..
        } if name == "Array" && type_args.len() == 1 => {
            let elem = type_args[0];
            synth_array(
                reg,
                elem,
                val,
                fmt,
                tt,
                alloc,
                fmt_type,
                module_source,
                span,
            )
        }
        ResolvedType::GenericInstance {
            ref name,
            ref type_args,
            ..
        } => {
            let n = name.clone();
            let ta = type_args.clone();
            synth_generic_struct(
                reg,
                &n,
                &ta,
                val,
                fmt,
                tt,
                mods,
                fmt_type,
                module_source,
                span,
            )
        }
        ResolvedType::Ref(inner) => synth_ref(
            reg,
            false,
            inner,
            val,
            fmt,
            tt,
            fmt_type,
            module_source,
            span,
        ),
        ResolvedType::MutRef(inner) => synth_ref(
            reg,
            true,
            inner,
            val,
            fmt,
            tt,
            fmt_type,
            module_source,
            span,
        ),
        ResolvedType::Newtype {
            ref name,
            base_type,
            ..
        } => {
            let n = name.clone();
            synth_newtype(
                reg,
                &n,
                base_type,
                val,
                fmt,
                tt,
                mods,
                alloc,
                fmt_type,
                module_source,
                span,
            )
        }
        ResolvedType::Variant { ref name, .. } => {
            let n = name.clone();
            synth_variant(reg, &n, val, fmt, tt, mods, fmt_type, module_source, span)
        }
        ResolvedType::Resource { ref name, .. } => {
            let n = name.clone();
            synth_resource(&n, val, fmt, tt, span)
        }
        ResolvedType::Function {
            ref params,
            return_type,
            ..
        } => {
            // Inside a generated function, always show signature only (no source text)
            let p = params.clone();
            synth_fn_type(&p, return_type, fmt, tt, span)
        }
        _ => {
            let tn = tt.borrow().type_name(type_id);
            vec![ws(&format!("<{tn}>"), fmt, tt, span)]
        }
    }
}

// ─── Synthesis helpers ───

/// Resolve string `TypeId`.
fn str_type(tt: &Rc<RefCell<TypeTable>>) -> TypeId {
    tt.borrow_mut()
        .make_struct("String".to_string(), ModuleSource::string())
}

/// Build a `f.write_str("text")` statement.
fn ws(text: &str, fmt: TirExpr, tt: &Rc<RefCell<TypeTable>>, span: Span) -> TirStmt {
    let s = str_type(tt);
    let call = TirExpr::new(
        TirExprKind::MethodCall {
            receiver: Box::new(fmt),
            func: FunctionRef {
                module_source: ModuleSource::format(),
                name: "Formatter::write_str".to_string(),
                monomorph_info: None,
                method_info: Some(LocalMethodName::new(
                    "Formatter".into(),
                    None,
                    "write_str".into(),
                )),
                is_cm_adapter: false,
            },
            type_args: vec![],
            args: vec![TirExpr::new(
                TirExprKind::StringLiteral(text.to_string()),
                s,
                span,
            )],
            param_is_mut: vec![false],
        },
        TypeTable::UNIT,
        span,
    );
    TirStmt::new(TirStmtKind::Expr(call), span)
}

/// Build a `f.write_char(c)` statement.
fn wc(c: char, fmt: TirExpr, span: Span) -> TirStmt {
    let call = TirExpr::new(
        TirExprKind::MethodCall {
            receiver: Box::new(fmt),
            func: FunctionRef {
                module_source: ModuleSource::format(),
                name: "Formatter::write_char".to_string(),
                monomorph_info: None,
                method_info: Some(LocalMethodName::new(
                    "Formatter".into(),
                    None,
                    "write_char".into(),
                )),
                is_cm_adapter: false,
            },
            type_args: vec![],
            args: vec![TirExpr::new(
                TirExprKind::CharLiteral(c),
                TypeTable::CHAR,
                span,
            )],
            param_is_mut: vec![false],
        },
        TypeTable::UNIT,
        span,
    );
    TirStmt::new(TirStmtKind::Expr(call), span)
}

/// Build a `Display::fmt` call: `(&expr).fmt(fmt_ref)`.
fn display_fmt(
    type_id: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    span: Span,
) -> Vec<TirStmt> {
    let base = tt.borrow().get_ultimate_base_type(type_id);
    let type_name = tt.borrow().mangle_type_name(base);
    let impl_mod = display_impl_module(base, tt);

    let ref_type = tt.borrow_mut().make_ref(type_id);
    let receiver = TirExpr::new(
        TirExprKind::Unary {
            op: TirUnaryOp::Ref,
            expr: Box::new(val),
        },
        ref_type,
        span,
    );

    let mangled = MethodName::format_local(&type_name, Some("Display"), "fmt");
    let call = TirExpr::new(
        TirExprKind::MethodCall {
            receiver: Box::new(receiver),
            func: FunctionRef {
                module_source: impl_mod,
                name: mangled,
                monomorph_info: None,
                method_info: Some(LocalMethodName::new(
                    type_name,
                    Some("Display".into()),
                    "fmt".into(),
                )),
                is_cm_adapter: false,
            },
            type_args: vec![],
            args: vec![fmt],
            param_is_mut: vec![false],
        },
        TypeTable::UNIT,
        span,
    );
    vec![TirStmt::new(TirStmtKind::Expr(call), span)]
}

/// Call `LowerHex::fmt(&val, &mut f)` — used for resource handle hex output.
fn lower_hex_fmt(
    type_id: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    span: Span,
) -> Vec<TirStmt> {
    let type_name = tt.borrow().mangle_type_name(type_id);

    let ref_type = tt.borrow_mut().make_ref(type_id);
    let receiver = TirExpr::new(
        TirExprKind::Unary {
            op: TirUnaryOp::Ref,
            expr: Box::new(val),
        },
        ref_type,
        span,
    );

    let mangled = MethodName::format_local(&type_name, Some("LowerHex"), "fmt");
    let call = TirExpr::new(
        TirExprKind::MethodCall {
            receiver: Box::new(receiver),
            func: FunctionRef {
                module_source: ModuleSource::primitives(),
                name: mangled,
                monomorph_info: None,
                method_info: Some(LocalMethodName::new(
                    type_name,
                    Some("LowerHex".into()),
                    "fmt".into(),
                )),
                is_cm_adapter: false,
            },
            type_args: vec![],
            args: vec![fmt],
            param_is_mut: vec![false],
        },
        TypeTable::UNIT,
        span,
    );
    vec![TirStmt::new(TirStmtKind::Expr(call), span)]
}

fn display_impl_module(type_id: TypeId, tt: &Rc<RefCell<TypeTable>>) -> ModuleSource {
    match tt.borrow().get(type_id).clone() {
        ResolvedType::Primitive(_) => ModuleSource::primitives(),
        ResolvedType::Struct { name, .. } if name == "String" => ModuleSource::format(),
        ResolvedType::Struct { module_source, .. } | ResolvedType::Enum { module_source, .. } => {
            module_source
        }
        _ => ModuleSource::primitives(),
    }
}

// ─── Type-specific body generators ───

fn synth_string(
    val: TirExpr,
    fmt: TirExpr,
    _tt: &Rc<RefCell<TypeTable>>,
    span: Span,
) -> Vec<TirStmt> {
    let mut s = Vec::new();
    s.push(wc('"', fmt.clone(), span));
    let call = TirExpr::new(
        TirExprKind::Call {
            func: FunctionRef {
                module_source: ModuleSource::internal(),
                name: "write_escaped_string".to_string(),
                monomorph_info: None,
                method_info: None,
                is_cm_adapter: false,
            },
            type_args: vec![],
            args: vec![val, fmt.clone()],
            param_is_mut: vec![false, false],
        },
        TypeTable::UNIT,
        span,
    );
    s.push(TirStmt::new(TirStmtKind::Expr(call), span));
    s.push(wc('"', fmt, span));
    s
}

fn synth_struct(
    reg: &mut InspectRegistry,
    name: &str,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let fields = find_struct_fields(name, mods);
    let mut s = Vec::new();

    match fields {
        Some((fields, has_hidden)) if !fields.is_empty() => {
            s.push(ws(&format!("{name} {{ "), fmt.clone(), tt, span));
            for (i, (fn_, ft, fi)) in fields.iter().enumerate() {
                if i > 0 {
                    s.push(ws(", ", fmt.clone(), tt, span));
                }
                s.push(ws(&format!("{fn_}: "), fmt.clone(), tt, span));
                let fa = TirExpr::new(
                    TirExprKind::FieldAccess {
                        expr: Box::new(val.clone()),
                        field_index: *fi,
                        field_name: fn_.clone(),
                    },
                    *ft,
                    span,
                );
                s.push(call_inspect_fn(
                    reg,
                    *ft,
                    fa,
                    fmt.clone(),
                    tt,
                    fmt_type,
                    module_source,
                    span,
                ));
            }
            if has_hidden {
                s.push(ws(", ..", fmt.clone(), tt, span));
            }
            s.push(ws(" }", fmt, tt, span));
        }
        Some((_, true)) => s.push(ws(&format!("{name} {{ .. }}"), fmt, tt, span)),
        Some(_) => s.push(ws(&format!("{name} {{}}"), fmt, tt, span)),
        None => s.push(ws(&format!("{name} {{ ... }}"), fmt, tt, span)),
    }
    s
}

/// Inspect a monomorphized struct (e.g., `Box<i32>`).
/// Uses `display_name` (the base name "Box") for the output prefix and
/// `lookup_name` (the monomorphized name "Box<i32>") for field lookup.
fn synth_monomorphized_struct(
    reg: &mut InspectRegistry,
    display_name: &str,
    lookup_name: &str,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let fields = find_struct_fields(lookup_name, mods);
    let mut s = Vec::new();

    match fields {
        Some((fields, has_hidden)) if !fields.is_empty() => {
            s.push(ws(&format!("{display_name} {{ "), fmt.clone(), tt, span));
            for (i, (fn_, ft, fi)) in fields.iter().enumerate() {
                if i > 0 {
                    s.push(ws(", ", fmt.clone(), tt, span));
                }
                s.push(ws(&format!("{fn_}: "), fmt.clone(), tt, span));
                let fa = TirExpr::new(
                    TirExprKind::FieldAccess {
                        expr: Box::new(val.clone()),
                        field_index: *fi,
                        field_name: fn_.clone(),
                    },
                    *ft,
                    span,
                );
                s.push(call_inspect_fn(
                    reg,
                    *ft,
                    fa,
                    fmt.clone(),
                    tt,
                    fmt_type,
                    module_source,
                    span,
                ));
            }
            if has_hidden {
                s.push(ws(", ..", fmt.clone(), tt, span));
            }
            s.push(ws(" }", fmt, tt, span));
        }
        Some((_, true)) => {
            s.push(ws(&format!("{display_name} {{ .. }}"), fmt, tt, span));
        }
        Some(_) => s.push(ws(&format!("{display_name} {{}}"), fmt, tt, span)),
        None => s.push(ws(&format!("{display_name} {{ ... }}"), fmt, tt, span)),
    }
    s
}

/// Returns `(visible_fields, has_hidden)` for the named struct.
fn find_struct_fields(
    name: &str,
    mods: &[&TirModule],
) -> Option<(Vec<(String, TypeId, u32)>, bool)> {
    for m in mods {
        if let Some(s) = m.find_struct(name) {
            let mut visible = Vec::new();
            let mut has_hidden = false;
            for f in &s.fields {
                if f.is_hidden {
                    has_hidden = true;
                } else {
                    visible.push((f.name.clone(), f.type_id, f.index));
                }
            }
            return Some((visible, has_hidden));
        }
    }
    None
}

fn synth_generic_struct(
    reg: &mut InspectRegistry,
    name: &str,
    type_args: &[TypeId],
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let fields = find_struct_fields(name, mods);
    let mut s = Vec::new();

    match fields {
        Some((fields, has_hidden)) if !fields.is_empty() => {
            s.push(ws(&format!("{name} {{ "), fmt.clone(), tt, span));
            let subst = SubstitutionContext::new().with_impl_args(type_args);
            for (i, (fn_, ft, fi)) in fields.iter().enumerate() {
                if i > 0 {
                    s.push(ws(", ", fmt.clone(), tt, span));
                }
                s.push(ws(&format!("{fn_}: "), fmt.clone(), tt, span));
                let concrete_type = subst.substitute(*ft, &mut tt.borrow_mut());
                let fa = TirExpr::new(
                    TirExprKind::FieldAccess {
                        expr: Box::new(val.clone()),
                        field_index: *fi,
                        field_name: fn_.clone(),
                    },
                    concrete_type,
                    span,
                );
                s.push(call_inspect_fn(
                    reg,
                    concrete_type,
                    fa,
                    fmt.clone(),
                    tt,
                    fmt_type,
                    module_source,
                    span,
                ));
            }
            if has_hidden {
                s.push(ws(", ..", fmt.clone(), tt, span));
            }
            s.push(ws(" }", fmt, tt, span));
        }
        Some((_, true)) => s.push(ws(&format!("{name} {{ .. }}"), fmt, tt, span)),
        Some(_) => s.push(ws(&format!("{name} {{}}"), fmt, tt, span)),
        None => s.push(ws(&format!("{name} {{ ... }}"), fmt, tt, span)),
    }
    s
}

fn synth_enum(
    name: &str,
    type_id: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    span: Span,
) -> Vec<TirStmt> {
    let cases = find_enum_cases(name, mods);
    match cases {
        Some(cases) if !cases.is_empty() => {
            let mut chain: Option<TirExpr> = None;
            for (cn, ci) in cases.iter().rev() {
                let text = format!("{name}::{cn}");
                let then_block = TirBlock::new(vec![ws(&text, fmt.clone(), tt, span)], span);
                let cond = TirExpr::new(
                    TirExprKind::Binary {
                        left: Box::new(val.clone()),
                        op: TirBinaryOp::Eq,
                        right: Box::new(TirExpr::new(
                            TirExprKind::IntLiteral {
                                value: u64::from(*ci),
                                repr: ci.to_string(),
                            },
                            type_id,
                            span,
                        )),
                    },
                    TypeTable::BOOL,
                    span,
                );
                let if_expr = TirExpr::new(
                    TirExprKind::If {
                        condition: Box::new(cond),
                        then_branch: then_block,
                        else_branch: chain.map(|e| {
                            TirBlock::new(vec![TirStmt::new(TirStmtKind::Expr(e), span)], span)
                        }),
                    },
                    TypeTable::UNIT,
                    span,
                );
                chain = Some(if_expr);
            }
            chain.map_or_else(Vec::new, |e| vec![TirStmt::new(TirStmtKind::Expr(e), span)])
        }
        _ => vec![ws(name, fmt, tt, span)],
    }
}

fn find_enum_cases(name: &str, mods: &[&TirModule]) -> Option<Vec<(String, u32)>> {
    for m in mods {
        if let Some(e) = m.find_enum(name) {
            return Some(e.cases.iter().map(|c| (c.name.clone(), c.index)).collect());
        }
    }
    None
}

fn synth_tuple(
    reg: &mut InspectRegistry,
    elems: &[TypeId],
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let mut s = vec![wc('[', fmt.clone(), span)];
    for (i, et) in elems.iter().enumerate() {
        if i > 0 {
            s.push(ws(", ", fmt.clone(), tt, span));
        }
        let ea = TirExpr::new(
            TirExprKind::FieldAccess {
                expr: Box::new(val.clone()),
                field_index: i as u32,
                field_name: i.to_string(),
            },
            *et,
            span,
        );
        s.push(call_inspect_fn(
            reg,
            *et,
            ea,
            fmt.clone(),
            tt,
            fmt_type,
            module_source,
            span,
        ));
    }
    s.push(wc(']', fmt, span));
    s
}

fn synth_array(
    reg: &mut InspectRegistry,
    elem: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    alloc: &mut LocalAlloc,
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let mut s = vec![wc('[', fmt.clone(), span)];

    // Inline Array::len() as field access `val.used` instead of generating a method call.
    // This avoids needing to resolve Array<T>::len, which may add unnecessary dependencies.
    let len_call = TirExpr::new(
        TirExprKind::FieldAccess {
            expr: Box::new(val.clone()),
            field_name: "used".to_string(),
            field_index: 1,
        },
        TypeTable::I32,
        span,
    );

    let len_idx = alloc.alloc(TypeTable::I32);
    let i_idx = alloc.alloc(TypeTable::I32);

    s.push(TirStmt::new(
        TirStmtKind::Let {
            name: "__inspect_len".into(),
            local_index: len_idx,
            is_mut: false,
            is_reactive: false,
            type_id: TypeTable::I32,
            value: len_call,
            skip_value_copy: false,
        },
        span,
    ));

    s.push(TirStmt::new(
        TirStmtKind::Let {
            name: "__inspect_i".into(),
            local_index: i_idx,
            is_mut: true,
            is_reactive: false,
            type_id: TypeTable::I32,
            value: TirExpr::new(
                TirExprKind::IntLiteral {
                    value: 0,
                    repr: "0".into(),
                },
                TypeTable::I32,
                span,
            ),
            skip_value_copy: false,
        },
        span,
    ));

    let i_local = || {
        TirExpr::new(
            TirExprKind::Local {
                index: i_idx,
                name: "__inspect_i".into(),
            },
            TypeTable::I32,
            span,
        )
    };
    let len_local = || {
        TirExpr::new(
            TirExprKind::Local {
                index: len_idx,
                name: "__inspect_len".into(),
            },
            TypeTable::I32,
            span,
        )
    };

    let cond = TirExpr::new(
        TirExprKind::Binary {
            left: Box::new(i_local()),
            op: TirBinaryOp::Lt,
            right: Box::new(len_local()),
        },
        TypeTable::BOOL,
        span,
    );

    let mut body = Vec::new();

    let comma_cond = TirExpr::new(
        TirExprKind::Binary {
            left: Box::new(i_local()),
            op: TirBinaryOp::Gt,
            right: Box::new(TirExpr::new(
                TirExprKind::IntLiteral {
                    value: 0,
                    repr: "0".into(),
                },
                TypeTable::I32,
                span,
            )),
        },
        TypeTable::BOOL,
        span,
    );
    body.push(TirStmt::new(
        TirStmtKind::Expr(TirExpr::new(
            TirExprKind::If {
                condition: Box::new(comma_cond),
                then_branch: TirBlock::new(vec![ws(", ", fmt.clone(), tt, span)], span),
                else_branch: None,
            },
            TypeTable::UNIT,
            span,
        )),
        span,
    ));

    let idx_access = TirExpr::new(
        TirExprKind::Index {
            expr: Box::new(val),
            index: Box::new(i_local()),
        },
        elem,
        span,
    );
    body.push(call_inspect_fn(
        reg,
        elem,
        idx_access,
        fmt.clone(),
        tt,
        fmt_type,
        module_source,
        span,
    ));

    body.push(TirStmt::new(
        TirStmtKind::Expr(TirExpr::new(
            TirExprKind::Assign {
                target: Box::new(i_local()),
                value: Box::new(TirExpr::new(
                    TirExprKind::Binary {
                        left: Box::new(i_local()),
                        op: TirBinaryOp::Add,
                        right: Box::new(TirExpr::new(
                            TirExprKind::IntLiteral {
                                value: 1,
                                repr: "1".into(),
                            },
                            TypeTable::I32,
                            span,
                        )),
                    },
                    TypeTable::I32,
                    span,
                )),
            },
            TypeTable::UNIT,
            span,
        )),
        span,
    ));

    let break_if_done = TirStmt::new(
        TirStmtKind::If {
            condition: TirExpr::new(
                TirExprKind::Unary {
                    op: TirUnaryOp::Not,
                    expr: Box::new(cond),
                },
                TypeTable::BOOL,
                span,
            ),
            then_block: TirBlock::new(
                vec![TirStmt::new(
                    TirStmtKind::Break {
                        label: None,
                        value: None,
                    },
                    span,
                )],
                span,
            ),
            else_block: None,
        },
        span,
    );
    body.insert(0, break_if_done);
    s.push(TirStmt::new(
        TirStmtKind::Loop {
            body: TirBlock::new(body, span),
        },
        span,
    ));
    s.push(wc(']', fmt, span));
    s
}

fn synth_ref(
    reg: &mut InspectRegistry,
    is_mut: bool,
    inner: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let mut s = Vec::new();
    if is_mut {
        s.push(ws("&mut ", fmt.clone(), tt, span));
    } else {
        s.push(wc('&', fmt.clone(), span));
    }
    let deref = TirExpr::new(
        TirExprKind::Unary {
            op: TirUnaryOp::Deref,
            expr: Box::new(val),
        },
        inner,
        span,
    );
    s.push(call_inspect_fn(
        reg,
        inner,
        deref,
        fmt,
        tt,
        fmt_type,
        module_source,
        span,
    ));
    s
}

fn synth_newtype(
    reg: &mut InspectRegistry,
    name: &str,
    base: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    alloc: &mut LocalAlloc,
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    if let Some(fd) = find_flags(name, mods) {
        return synth_flags(&fd, val, fmt, tt, alloc, span);
    }

    let cast = TirExpr::new(
        TirExprKind::Cast {
            expr: Box::new(val),
            target_type: base,
        },
        base,
        span,
    );
    let mut s = Vec::new();
    s.push(call_inspect_fn(
        reg,
        base,
        cast,
        fmt.clone(),
        tt,
        fmt_type,
        module_source,
        span,
    ));
    s.push(ws(&format!(" as {name}"), fmt, tt, span));
    s
}

fn find_flags(name: &str, mods: &[&TirModule]) -> Option<TirFlags> {
    for m in mods {
        for f in &m.flags {
            if f.name == name {
                return Some(f.clone());
            }
        }
    }
    None
}

fn synth_variant(
    reg: &mut InspectRegistry,
    name: &str,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    mods: &[&TirModule],
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    let vd = find_variant(name, mods);
    match vd {
        Some(decl) => {
            let cases = decl.cases.clone();
            let mut chain: Option<TirExpr> = None;

            for case in cases.iter().rev() {
                let is_unit = case.payload == TypeTable::UNIT;
                let mut then_stmts = Vec::new();

                if is_unit {
                    then_stmts.push(ws(&format!("{name}::{}", case.name), fmt.clone(), tt, span));
                } else {
                    then_stmts.push(ws(
                        &format!("{name}::{}(", case.name),
                        fmt.clone(),
                        tt,
                        span,
                    ));
                    let payload = TirExpr::new(
                        TirExprKind::VariantPayload {
                            expr: Box::new(val.clone()),
                            case_index: case.index,
                            payload_type: case.payload,
                        },
                        case.payload,
                        span,
                    );
                    then_stmts.push(call_inspect_fn(
                        reg,
                        case.payload,
                        payload,
                        fmt.clone(),
                        tt,
                        fmt_type,
                        module_source,
                        span,
                    ));
                    then_stmts.push(wc(')', fmt.clone(), span));
                }

                let cond = TirExpr::new(
                    TirExprKind::VariantTest {
                        expr: Box::new(val.clone()),
                        case_index: case.index,
                        case_name: case.name.clone(),
                    },
                    TypeTable::BOOL,
                    span,
                );
                let if_expr = TirExpr::new(
                    TirExprKind::If {
                        condition: Box::new(cond),
                        then_branch: TirBlock::new(then_stmts, span),
                        else_branch: chain.map(|e| {
                            TirBlock::new(vec![TirStmt::new(TirStmtKind::Expr(e), span)], span)
                        }),
                    },
                    TypeTable::UNIT,
                    span,
                );
                chain = Some(if_expr);
            }
            chain.map_or_else(Vec::new, |e| vec![TirStmt::new(TirStmtKind::Expr(e), span)])
        }
        None => vec![ws(&format!("{name}::???"), fmt, tt, span)],
    }
}

/// Synthesize inspect for `Option<T>` using `SubtypeHierarchy` (variant operations).
///
/// Generates:
///   if VariantTest(val, 0 /* Some */) {
///       write "Some("
///       inspect(VariantPayload(val, 0), ...)
///       write ")"
///   } else {
///       write "null"
///   }
#[allow(clippy::too_many_arguments)]
fn synth_option_variant(
    reg: &mut InspectRegistry,
    inner: TypeId,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    _mods: &[&TirModule],
    fmt_type: TypeId,
    module_source: &ModuleSource,
    span: Span,
) -> Vec<TirStmt> {
    // "Some" case: VariantTest for case_index 0
    let mut some_stmts = Vec::new();
    some_stmts.push(ws("Some(", fmt.clone(), tt, span));

    let payload = TirExpr::new(
        TirExprKind::VariantPayload {
            expr: Box::new(val.clone()),
            case_index: 0,
            payload_type: inner,
        },
        inner,
        span,
    );
    some_stmts.push(call_inspect_fn(
        reg,
        inner,
        payload,
        fmt.clone(),
        tt,
        fmt_type,
        module_source,
        span,
    ));
    some_stmts.push(wc(')', fmt.clone(), span));

    // "None" case: write "null"
    let none_stmts = vec![ws("null", fmt.clone(), tt, span)];

    let cond = TirExpr::new(
        TirExprKind::VariantTest {
            expr: Box::new(val),
            case_index: 0,
            case_name: "Some".to_string(),
        },
        TypeTable::BOOL,
        span,
    );
    let if_expr = TirExpr::new(
        TirExprKind::If {
            condition: Box::new(cond),
            then_branch: TirBlock::new(some_stmts, span),
            else_branch: Some(TirBlock::new(none_stmts, span)),
        },
        TypeTable::UNIT,
        span,
    );
    vec![TirStmt::new(TirStmtKind::Expr(if_expr), span)]
}

fn find_variant(name: &str, mods: &[&TirModule]) -> Option<TirVariantDecl> {
    for m in mods {
        for v in &m.variants {
            if v.name == name {
                return Some(v.clone());
            }
        }
    }
    None
}

fn synth_resource(
    name: &str,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    span: Span,
) -> Vec<TirStmt> {
    let mut s = Vec::new();
    s.push(ws(&format!("{name}#0x"), fmt.clone(), tt, span));
    let cast = TirExpr::new(
        TirExprKind::Cast {
            expr: Box::new(val),
            target_type: TypeTable::I32,
        },
        TypeTable::I32,
        span,
    );
    s.extend(lower_hex_fmt(TypeTable::I32, cast, fmt, tt, span));
    s
}

fn synth_flags(
    fd: &TirFlags,
    val: TirExpr,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    alloc: &mut LocalAlloc,
    span: Span,
) -> Vec<TirStmt> {
    let name = &fd.name;

    let u32_val = TirExpr::new(
        TirExprKind::Cast {
            expr: Box::new(val),
            target_type: TypeTable::U32,
        },
        TypeTable::U32,
        span,
    );

    let is_none = TirExpr::new(
        TirExprKind::Binary {
            left: Box::new(u32_val.clone()),
            op: TirBinaryOp::Eq,
            right: Box::new(TirExpr::new(
                TirExprKind::IntLiteral {
                    value: 0,
                    repr: "0".into(),
                },
                TypeTable::U32,
                span,
            )),
        },
        TypeTable::BOOL,
        span,
    );

    let none_text = format!("{name}::none()");
    let then_block = TirBlock::new(vec![ws(&none_text, fmt.clone(), tt, span)], span);

    let first_idx = alloc.alloc(TypeTable::BOOL);
    let mut else_stmts = Vec::new();
    else_stmts.push(TirStmt::new(
        TirStmtKind::Let {
            name: "__inspect_first".into(),
            local_index: first_idx,
            is_mut: true,
            is_reactive: false,
            type_id: TypeTable::BOOL,
            value: TirExpr::new(TirExprKind::BoolLiteral(true), TypeTable::BOOL, span),
            skip_value_copy: false,
        },
        span,
    ));

    let first_local = || {
        TirExpr::new(
            TirExprKind::Local {
                index: first_idx,
                name: "__inspect_first".into(),
            },
            TypeTable::BOOL,
            span,
        )
    };

    for member in &fd.members {
        let bit_check = TirExpr::new(
            TirExprKind::Binary {
                left: Box::new(TirExpr::new(
                    TirExprKind::Binary {
                        left: Box::new(u32_val.clone()),
                        op: TirBinaryOp::BitAnd,
                        right: Box::new(TirExpr::new(
                            TirExprKind::IntLiteral {
                                value: u64::from(member.bitmask),
                                repr: member.bitmask.to_string(),
                            },
                            TypeTable::U32,
                            span,
                        )),
                    },
                    TypeTable::U32,
                    span,
                )),
                op: TirBinaryOp::NotEq,
                right: Box::new(TirExpr::new(
                    TirExprKind::IntLiteral {
                        value: 0,
                        repr: "0".into(),
                    },
                    TypeTable::U32,
                    span,
                )),
            },
            TypeTable::BOOL,
            span,
        );

        let mut member_stmts = Vec::new();
        let sep_cond = TirExpr::new(
            TirExprKind::Unary {
                op: TirUnaryOp::Not,
                expr: Box::new(first_local()),
            },
            TypeTable::BOOL,
            span,
        );
        member_stmts.push(TirStmt::new(
            TirStmtKind::Expr(TirExpr::new(
                TirExprKind::If {
                    condition: Box::new(sep_cond),
                    then_branch: TirBlock::new(vec![ws(" | ", fmt.clone(), tt, span)], span),
                    else_branch: None,
                },
                TypeTable::UNIT,
                span,
            )),
            span,
        ));
        member_stmts.push(ws(
            &format!("{name}::{}", member.name),
            fmt.clone(),
            tt,
            span,
        ));
        member_stmts.push(TirStmt::new(
            TirStmtKind::Expr(TirExpr::new(
                TirExprKind::Assign {
                    target: Box::new(first_local()),
                    value: Box::new(TirExpr::new(
                        TirExprKind::BoolLiteral(false),
                        TypeTable::BOOL,
                        span,
                    )),
                },
                TypeTable::UNIT,
                span,
            )),
            span,
        ));

        else_stmts.push(TirStmt::new(
            TirStmtKind::Expr(TirExpr::new(
                TirExprKind::If {
                    condition: Box::new(bit_check),
                    then_branch: TirBlock::new(member_stmts, span),
                    else_branch: None,
                },
                TypeTable::UNIT,
                span,
            )),
            span,
        ));
    }

    let if_expr = TirExpr::new(
        TirExprKind::If {
            condition: Box::new(is_none),
            then_branch: then_block,
            else_branch: Some(TirBlock::new(else_stmts, span)),
        },
        TypeTable::UNIT,
        span,
    );
    vec![TirStmt::new(TirStmtKind::Expr(if_expr), span)]
}

fn synth_fn_type(
    params: &[TypeId],
    ret: TypeId,
    fmt: TirExpr,
    tt: &Rc<RefCell<TypeTable>>,
    span: Span,
) -> Vec<TirStmt> {
    let t = tt.borrow();
    let mut sig = String::from("|");
    for (i, p) in params.iter().enumerate() {
        if i > 0 {
            sig.push_str(", ");
        }
        sig.push_str(&t.type_name(*p));
    }
    sig.push('|');
    if ret != TypeTable::UNIT {
        sig.push_str(" -> ");
        sig.push_str(&t.type_name(ret));
    }
    drop(t);
    vec![ws(&sig, fmt, tt, span)]
}
