[build-dependencies]
gale = { path = "../../package-gale" }

[build.generators.parser]
module = { path = "../../package-gale/src/generator.wado" }
from = "../../package-gale/tests/grammars/SQLite.g4"
options = { highlight = false }
